- bucket/pluto.json
This PR updates the Pluto manifest to point at the homepage with all of the details rather than the repo which requires the user to click through to the homepage to get any details.
> pluto: Update homepage

- bucket/quick-lint-js.json
> quick-lint-js: Add version 2.4.1

- bucket/nova.json
> nova: Add version 3.0.2

- bucket/dprint.json
> dprint: Add version 0.26.0

- bucket/aztfy.json
> aztfy: Add version 0.2.0

- bucket/podman.json
> podman: Update url to msi url

- bucket/eac3to.json
> eac3to@3.36: fix binary path error

- bucket/cue.json
Add CUE (an open source data constraint language which aims to simplify tasks involving defining and using data).
More info: https://cuelang.org/
> cue: Add version 0.4.3

- bucket/mpd.json
> mpd: Add version 0.23.7

- bucket/lynx.json
fix lynx depends: update the slproweb download url
Closes #XXXX
> fix lynx depends: update the slproweb download url

- bucket/watchman.json
[watchman](https://facebook.github.io/watchman/) is a file watching service by Facebook.
migrate from https://github.com/ScoopInstaller/Extras/pull/8493
> watchman: Add version 2022.05.16.00

- bucket/mandoc.json
> mandoc: Add version 1.13.1

- bucket/gron.json
> gron: Update to version 0.7.1

- bucket/bc.json
> bc: Add version 1.07.1

- bucket/difftastic.json
> difftastic: Add version 0.28.0

- bucket/cvs.json
> cvs: Add version 1.11.22

- bucket/vals.json
Vals, is a configuration values and secrets management tool
> vals: Add version 0.16.2

- bucket/outwit.json
> outwit: Add version 1.25

- bucket/dhall.json
> dhall: Fix `bin` path

- bucket/srvany-ng.json
> srvany-ng: Add version 1.0.0.0

- bucket/gameboosthd.json
[GameBoostHD](https://r1ch.net/projects/gameboosthd) is a tool that can maximize game performance by Dynamically adjust process priority of background applications.
**NOTES**:
* The app is built in **32-bit**.
* *autoupdate* is not needed because the app does not receive updates recently.
> https://r1ch.net/projects/gameboosthd
v1.4 (2021-01-11)
Added Valorant support
NOTE: The exe is no longer digitally signed as my code signing certificate has expired.
v1.32 (2018-05-09)
Workaround a Windows feature that shows a busy cursor for up to two seconds after starting the program.
v1.31 (2018-04-15)
Fixed a crash on startup that could occur since v1.3 due to a bug in the command line parsing.
* **usage** of the app:
> https://r1ch.net/projects/gameboosthd
GameBoostHD has no installer or user …
> gameboosthd: Add version 1.4

- bucket/powersession.json
Introduce Rust implementation
Relates to #3640
> PowerSession: Add notes about PowerSession-rs

- bucket/docto.json
DocTo is a simple command line utility for converting .doc & .xls files to any supported format.
It requires MS Office installed on your PC.
https://github.com/tobya/DocTo
Closes #XXXX
> docto: Add version 1.7

- bucket/dnslookup.json
https://github.com/ameshkov/dnslookup
Simple command line utility to make DNS lookups to the specified server
Signed-off-by: Slach <bloodjazman@gmail.com>
> dnslookup: Add version 1.7.0

- bucket/everything-cli.json
> Everything-cli: add persist file

- bucket/rustup-msvc.json
> rustup-msvc@1.24.3: Update notes

- bucket/latexindent.json
> latexindent@3.17.3: Fix hash

- bucket/jdtls.json
- bucket/vcpkg.json
* Closes #3633
* Relates to #XXXX
> vcpkg: Add version 2022.05.10

- bucket/static-web-server.json
> static-web-server: Add version 2.9.0

- bucket/gitsign.json
This PR adds the [newly announced](https://blog.sigstore.dev/introducing-gitsign-9fd3f1b682aa) Sigstore [gitsign](https://github.com/sigstore/gitsign).
> gitsign: Add version 0.1.0

- bucket/mizu-cli.json
> mizu-cli: Add version 33.1

- bucket/dokka.json
- bucket/jd-cli.json
> (chore): Update dokka and jd-cli

- bucket/units.json
> units: Add version 2.21

- bucket/lego.json
Adds an ACME cli client with support for more DNS providers.
> Add lego: LE/ACME client and library written in Go

- .editorconfig
- .gitattributes
Closes #3692
Relates to https://github.com/ScoopInstaller/Extras/pull/8285
> (chore): Fix git conflicts with line endings

- bucket/detekt.json
Adds [detekt](https://github.com/detekt/detekt) - CLI for detekt static code analysis for Kotlin
> detekt: Add version 1.20.0

- bucket/detekt.json
Small nits to clarify the description of Detekt in the registry
> Clarify the Detekt Description

- bucket/iverilog.json
> iverilog@12-20220611: Fix Hash

- bucket/nixpacks.json
> nixpacks: add version 0.1.0

- bucket/kcptun.json
kcptun
https://github.com/xtaci/kcptun
A Stable & Secure Tunnel based on KCP with N:M multiplexing and FEC.
> kcptun: Add version 20210922

- bucket/mprocs.json
> mprocs: Add version 0.5.0

- bucket/tree-sitter.json
An incremental parsing system for programming tools
> tree-sitter: Add version 0.20.6

- bucket/actionlint.json
> actionlint: Add version 1.6.15 (move from Extras)

- bucket/rust-analyzer.json
> rust-analyzer: Update info and url

- bucket/oh-my-posh.json
- bucket/sqlcl.json
> sqlcl: add version 22.2.0.172.1718

- bucket/upbound-cli.json
This PR add the Upbound CLI `up` to Scoop.
> upbound-cli: Add version 0.11.0

- bucket/qrencode.json
See https://github.com/ScoopInstaller/Main/pull/3754#issuecomment-1186523981 and https://github.com/ScoopInstaller/Main/pull/3754#issuecomment-1186529248.
> qrencode: Switch to mingw-w64 builds

- bucket/tproxy.json
A really lightweight CLI proxy tool to analyse TCP connection traffic.
Closes #3759
Relates to #3759
> tproxy: Add version 0.4.0

- bucket/biodiff.json
- [+] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
biodiff - Hex diff viewer using alignment algorithms from biology
> add biodiff 1.0.3

- bucket/wapm-cli.json
- bucket/wasmer.json
> wapm-cli: Add version 0.5.4

- bucket/python.json
> python@3.10.6: esc compatible with PowerShell 5

- bucket/edgedb.json
Add edgedb version 2.0.2+61917d6
> edgedb: Add edgedb version 2.0.2+61917d6

- bucket/osslsigncode.json
Development has moved over to https://github.com/mtrojnar/osslsigncode.
> osslsigncode: Update to version 2.4

- bucket/unzip.json
- bucket/zip.json
[Info-ZIP](https://spdx.org/licenses/Info-ZIP.html) has its own entry in the SPDX.
> chore: Update Info-Zip licenses

- bucket/insect.json
> insect: Update to version 5.7.0

- bucket/vagrant.json
> vagrant: Update to version 2.3.0 (update url)

- bucket/lua.json
> Update lua.json, change LUA_PATH -> LUA_EXE_PATH

- bucket/rustup.json
> rustup: Update note

- bucket/oha.json
> oha: Add version 0.5.3

- bucket/mingw.json
Also update repo URL
See https://github.com/mingw-w64/mingw-w64.github.io/pull/17
> mingw: Update to version 12.2.0

- bucket/magic-wormhole.json
Binaries from the Chocolatey package https://github.com/aquacash5/magic-wormhole-exe
> magic-wormhole: Add version 0.12.0

- bucket/acorn.json
Adds [Acorn](https://github.com/acorn-io/acorn) to Main.
> acorn: Add version 0.1.5

- bucket/portwarden.json
Add manifest for portwarden: https://github.com/vwxyzjn/portwarden
> Add manifest for portwarden app

- bucket/v2ray.json
> v2ray: Fix install for v5

- bucket/wireproxy.json
Closes #3895
Added a config dir to persist since user is supposed to save their config somewhere.
> wireproxy: Add version 1.0.5

- bucket/arc.json
Added arc 
Archiver and extractor cli software
Closes https://github.com/ScoopInstaller/Main/issues/3889
> arc: Add version 3.5.0

- bucket/dufs.json
> dufs: Add version 0.30.0

- bucket/wgcf.json
> wgcf: Add version 2.2.15

- bucket/cmder.json
> cmder: fix broken homepage url

- bucket/cmder-full.json
> cmder-full: fix homepage url

- bucket/terraform-switcher.json
> terraform-switcher: Add version 0.13.1288

- bucket/z3.json
> z3: Add version 4.11.2

- bucket/qpdf.json
Modified homepage on github repository
> qpdf: Update to version 11.0.0

- bucket/capstone.json
Added capstone.json in the bucket
> capstone: Add version 4.0.2

- bucket/retdec.json
Added retdec.json in the bucket
> retdec: Add version 4.0

- bucket/kubo.json
> Kubo updated to 0.15 and moved to ipfs.tech domain

- bucket/recmd.json
> recmd: fix hash

- bucket/yt-dlp.json
> yt-dlp: Persist "ytdlp_plugins" directory

- bucket/cpufetch.json
- bucket/cvs.json
- bucket/redpen.json
- bucket/xmlstarlet.json
> (chore): Some Refactoring

- bucket/lemminx.json
> Lemminx: Add version 0.19.1-541

- bucket/amass.json
Added amass.json in the bucket
> amass: Add version 3.20.0

- bucket/gitleaks.json
Added gitleaks.json in the bucket
> gitleaks: Add version 8.13.0

- bucket/bombardier.json
Added bombardier.json in the bucket
> bombardier: Add version 1.2.5

- bucket/drmemory.json
Added drmemory.json to the bucket
> drmemory: Add version 2.5.19232

- bucket/dynamorio.json
Added dynamorio.json to the bucket
> dynamorio: Add version 9.0.19255

- bucket/grype.json
Added grype.json in the bucket
> grype: Add version 0.50.2

- bucket/syft.json
> syft: Add version 0.57.0

- bucket/swift.json
> swift: add version 5.7

- bucket/lua-language-server.json
> lua-language-server: Add version 3.5.6

- bucket/scala-cli.json
Adds scala-cli, a command-line tool to interact with the Scala language. It lets you compile, run, test, and package your Scala code (and more!)
> scala-cli: Add version 0.1.15

- bucket/tinygo.json
> tinygo 0.26.0

- bucket/btop-lhm.json
- bucket/btop.json
Also move `extract_dir` outside of architecture.
> btop(-lhm): Add vcredist suggest

- bucket/swift.json
> swift: Fix autoupdate block

- bucket/miniserve.json
/verify
After v0.20，the github release link modified.
Closes #4011
> miniserve: Fix AU URL

- bucket/starship.json
Add arm64-specific sources for the starship package. I tested installation on my Arm-MacBook in a VM.
> starship: Add arm64 architecture

- bucket/actionlint.json
- bucket/chezmoi.json
- bucket/ghq.json
- bucket/go.json
- bucket/hugo.json
- bucket/neo-cowsay.json
- bucket/rust-msvc.json
- bucket/zoxide.json
Add arm64 architecture on some apps I use
> chore: Add arm64 architecture on some apps

- bucket/oh-my-posh.json
> oh-my-posh: Add 32bit and arm64 architecture

- bucket/rust-msvc.json
> rust-msvc: Fix arm64 autoupdate

- bucket/winget.json
> winget: Add ARM64 arch

- bucket/sox.json
> sox: Add 'play' and 'rec'

- bucket/lua-language-server.json
- bucket/nconvert.json
> nconvert: Add version 7.121

- bucket/libjxl
> libjxl: Add version 0.7.0

- bucket/nats-server.json
Closes #3953
I would like to hold on with merging the PR until I've gotten a final response from the NATS team. 
Still like to get feedback and verify it.
> Nats-Server: Add version 2.9.0

- bucket/sqldef.json
> sqldef: Add version 0.13.17

- bucket/alist.json
> alist: Add version 3.2.1

- bucket/topgrade.json
Topgrade author r-darwish recently stopped maintaining topgrade
> This repository is no longer maintained. An effort was made by the community to keep maintaining the project at https://github.com/topgrade-rs/topgrade. I am not involved in this effort nor do I know the people behind it, so I encourage you to inspect their work before using the fork.
> 
> I'm not the owner of the packages that ship Topgrade for various package managers, so their maintainers will need to decide what to do. I'm only the owner of the package in creates.io, which will no longer be updated.
> 
In this manner, r-darwish recently gave the cargo permissions to the team at topgrade-rs and they have now taken over development for topgrade. This PR is to update the upstream sources to the topgrade-rs repo and update …
> topgrade: Update to version 10.0.1 (and change upstream)

- bucket/ttyd.json
- bucket/vhs.json
Also added ttyd, as vhs depends on it to function properly.
Closes ScoopInstaller/Extras#9604
> vhs: Add version 0.1.1

- bucket/tere.json
> tere: Add version 1.3.0

- bucket/r.json
- Relates to https://github.com/ScoopInstaller/Versions/issues/688
> r: Persist 'site-library'

- bucket/latexindent.json
> latexindent@3.19: Fix hash

- bucket/ascii-image-converter.json
> ascii-image-converter: Add version 1.12.0

- bucket/vcpkg.json
> vcpkg: add missing persist directories

- bucket/sad.json
> sad: Add version 0.4.22

- bucket/nanazip.json
7-Zip fork with lots of features. https://github.com/M2Team/NanaZip
This app has a Windows 10/11 style context menu item, but I don't know how to register it.
> nanazip: Add version 2.0.396

- bucket/realcugan-ncnn-vulkan.json
Added [realcugan-ncnn-vulkan](https://github.com/nihui/realcugan-ncnn-vulkan) image upscaling software.
Closes #XXXX
> realcugan-ncnn-vulkan: Add version 20220728

- bucket/realesrgan-ncnn-vulkan.json
Added [realesrgan-ncnn-vulkan](https://github.com/xinntao/Real-ESRGAN) image upscaling software.
Closes #XXXX
> realesrgan-ncnn-vulkan: Add version 0.2.0

- bucket/perfetto.json
Closes https://github.com/ScoopInstaller/Extras/issues/9693
> perfetto: Add version 31.0

- bucket/lf.json
see the issue for details on the typos fixed
fixes issue #3796 
Closes #3796
> fix: lf: add lfcd to shims

- bucket/flaresolverr.json
Closes ScoopInstaller/Extras#9745
> flaresolverr: Add version 2.2.10

- bucket/resvg.json
> resvg: Add version 0.25.0

- bucket/dotnet-sdk.json
> dotnet-sdk: Add arm64 architecture

- bucket/flaresolverr.json
Fixed a typo I saw in the manifest.
> flaresolverr: fix `autoupdate`

- bucket/ossutil.json
This PR adds manifest for [`ossutil`](https://github.com/aliyun/ossutil), the official tool released by Alibaba Cloud to interact with its Object Storage Service.
Closes #4121
> ossutil: Add version 1.7.14

- bucket/sapling.json
Sapling SCM is a cross-platform, highly scalable, Git-compatible source control system.
Closes #4140
> sapling: Add version 0.1.20221118.210929.cfbb68aa

- bucket/rclone.json
> rclone: Add arm64

- bucket/lynx.json
> lynx: Update OpenSSL

- bucket/alist.json
> alist: Update to version 3.5.1

- bucket/git-cliff.json
> git-cliff: Add version 0.10.0

- bucket/fq.json
> fq: Add arm64 architecture

- bucket/clink-completions.json
> clink-completions: Update to version 0.4.2

- bucket/elvish.json
> elvish@0.18.0: Fix hash

- bucket/ouch.json
> ouch: add 0.4.0

- bucket/vulkan.json
- scripts/vulkan/install-vk-layers.ps1
Closes #4218
Implementation follows the advice and discussion in corresponding issue.
> vulkan@1.3.231.1: Add registry notes and cleanup (Fix #4218)

- bucket/qpdf.json
> qpdf: Add fix-qdf.exe to bin

- bucket/qemu.json
> qemu: Fix decompress error

- bucket/tesseract.json
> tesseract: Fix decompress error

- bucket/charm-gum.json
> charm-gum: Add version 0.8.0

- bucket/kube-linter.json
This PR adds [kube-linter](https://github.com/stackrox/kube-linter).
> kube-linter: Add version 0.5.1

- bucket/kubeconform.json
This PR adds [kubeconform](https://github.com/yannh/kubeconform).
> kubeconform: Add version 0.5.0

- bucket/file.json
Switched to a repo that is actually up to date
> file: Add `checkver` and `autoupdate`, Updated to version `5.43`

- bucket/sift.json
> sift: add version 0.9.0

- bucket/twitchdownloader-cli.json
Relates to https://github.com/ScoopInstaller/Extras/issues/10038
> twitchdownloader-cli: Add version 1.51.1

- bucket/silicon.json
> silicon: add 0.5.1

- bucket/nasm.json
> nasm: Remove the "rdoff\**.exe" files

- bucket/dart-sass-embedded.json
We no longer wish to auto-update this app.
> dart-sass-embedded: Remove autoupdate

- bucket/gh.json
> gh: Add arm64

- bucket/atomicparsley.json
- Remove `extract_dir`
- Add 32bit
Closes #4294
> atomicparsley@20221229.172126.d813aa6: Update manifest

- bucket/rathole.json
> rathole: Add version 0.4.7

- bucket/avrdude.json
> avrdude: Update to version 7.0

- bucket/wakatime-cli.json
> wakatime-cli: Fix pre_install for Powershell 5

- bucket/avrdude.json
> Fix JSON syntax in avrdude (Closes: #4312)

- bucket/marksman.json
> marksman(chore): remove trailing comma

- bucket/espanso.json
Update of application to v2.1.8, see https://github.com/espanso/espanso/releases
Closes #XXXX
> espanso: Update to version 2.1.8

- bucket/espanso.json
espanso.exe → espansod.exe
Closes #4321
> espanso: fix shortcut and bin

- bucket/pwsh.json
> Pwsh: add persist Microsoft.VSCode_profile.ps1

- bucket/retdec.json
> retdec: Update to version 5.0

- bucket/fastfetch.json
Like neofetch, but much faster because written in C
Config located in `$USERPROFILE/.config/fastfetch/config.conf`
> fastfetch: Add version 1.8.2

- bucket/d2.json
> d2: Add version v0.1.5

- bucket/helm-chart-releaser.json
This PR adds the Helm [chart-releaser](https://github.com/helm/chart-releaser) CLI.
> chart-releaser: Add version 1.5.0

- bucket/helm-chart-testing.json
This PR adds the Helm [chart-testing](https://github.com/helm/chart-testing) CLI.
> chart-testing: Add version 3.7.1

- bucket/ttyd.json
> ttyd: Update to version 1.7.3

- bucket/swift.json
- Extact `icu.msi`, `runtime.msi` to `$dir\Swift`
- Add `Swift\icu-69.1\usr\bin`, `Swift\runtime-development\usr\bin` to PATH
- Update `bin`
Closes #4373
> swift: Improvements

- bucket/dua.json
> dua@2.19.0: Add 32bit version

- bucket/bat.json
> bat: Add 32bit arch

- bucket/surrealdb.json
> surrealdb: Add version 1.0.0-beta.8

- bucket/agg.json
> agg: Add version 1.3.0

- bucket/act.json
> act: Add arm64 arch

- bucket/innounp.json
Works fine. Mirror is not needed.
> innounp: Use direct sourceforge link

- bucket/rethinkdb.json
Relates to #2848, which linked to https://github.com/rethinkdb/rethinkdb/issues/6814
> Update rethinkdb.json to rethinkdb-2.4.3

- bucket/v2ray.json
Add v2ray's ARM64 build
Closes #XXXX
- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
> v2ray: add arm64 build

- bucket/jwt-cli.json
> jwt-cli: Add version 5.0.3

- bucket/ttyper.json
> ttyper: Add version 1.0.0

- bucket/dfu-util.json
> dfu-util: Add version 0.11

- bucket/luau.json
> luau: Add version 0.562

- bucket/luajit.json
Related to #4074 and https://github.com/ScoopInstaller/Scoop/issues/2508
> luajit: Add version 2.1.0_beta3-4

- bucket/android-payload-dumper.json
- bucket/payload-dumper-go.json
> payload-dumper-go: Add version 1.2.2

- bucket/clipboard.json
Closes https://github.com/ScoopInstaller/Main/issues/4356
> clipboard: Add version 0.3.1

- bucket/chafa.json
> chafa: Add version 1.12.4

- bucket/ipinfo-cli.json
> ipinfo-cli: Add version 2.10.1

- bucket/glslViewer.json
> glslViewer: Add version 3.1.1

- bucket/wingetcreate.json
Official Winget manifest creator tool
Settings are stored in `$env:LOCALAPPDATA\Microsoft\WindowsPackageManagerManifestCreator\settings.json`
> wingetcreate: Add version 1.2.5.0

- bucket/kubent.json
New manifest kubent - https://github.com/doitintl/kube-no-trouble
> kubent: Add version 0.7.0

- bucket/apache.json
> apache@2.4.55: Add "logs" directory to "persist"

- bucket/curl.json
Curl homepage has moved to https://curl.se/
Closes #3593
> curl: Add `arm64` arch, Update URLs, Fix hash url

- bucket/git-quick-stats.json
> git-quick-stats: Add version 2.4.1

- bucket/fastfetch.json
With the introduction of 32bit support, I changed artifact name a bit.
> fastfetch: Update to version 1.10.0

- bucket/nixpacks.json
> fix(nixpacks): fix decompress error

- bucket/dotnet-sdk.json
> dotnet-sdk: Add an uninstall note and fix checkver

- bucket/gitea.json
The checkver link currently redirects to a file directory, so I changed it to use the json file containing the latest version.
> gitea: Fix checkver

- bucket/dnsproxy.json
> dnsproxy: Add version 0.48.0

- bucket/busybox-lean.json
- bucket/busybox.json
Updated checkver to use the latest binary in the archive.
> busybox: Update to version 4882-g6e0a6b7e5

- bucket/draft.json
New releases are hosted in the project's repo. They also reset version numbers at some point.
> draft: Update to version 0.0.30

- bucket/kubeshark.json
Renamed the manifest as the Mizu project renamed to Kubeshark: https://kubeshark.co/mizu-is-now-kubeshark
> kubeshark: Update to version 38.5

- bucket/isx.json
The binary is now provided in release assets.
> isx: Update to version 0.3.7

- bucket/erlang.json
> Use GitHub release assets for Erlang

- bucket/fq.json
Used the checksum file provided in the release.
> fq: Add hash file

- bucket/brotli.json
curl no longer provides new binaries of its dependencies: https://github.com/curl/curl-for-win/commit/893b5f5c806f0cb2f2914ffbb8cde312b87e30af
> brotli: Remove checkver

- bucket/transmission-cli.json
Updates to 4.x, pretty much identical to the manifest in extras though I added hash extraction from their new site.
> transmission-cli: Update to version 4.0.1

- bucket/mpd.json
Adjusts checkver so it doesn't read the version from "myMPD"
> mpd: Fix checkver

- bucket/s3deploy.json
> s3deploy: Update to version 2.9.0 & fix autoupdate

- bucket/nova.json
> nova: Update to version 3.6.2 & fix autoupdate

- bucket/dafny.json
> dafny: Update to version 4.0.0 & fix autoupdate

- bucket/gradle-bin.json
- bucket/gradle.json
> gradle: only set GRADLE_USER_HOME if it had not been set before (#4512)

- bucket/emitter.json
Fixed version tag that no longer exists. Removed autoupdate since newer binaries are not provided.
> emitter: Fix version and remove autoupdate

- bucket/wstunnel.json
> wstunnel: Update to version 5.0

- bucket/redpen.json
Fixed filename used in releases.
> redpen: Fix urls

- bucket/git.json
- bucket/mingit-busybox.json
- bucket/mingit.json
> (min)git: Simplify checkver

- bucket/far.json
> far: semantic versioning

- bucket/selenium-manager.json
> selenium-manager : Add Version 1.0.0-M3

- bucket/cargo-watch.json
> cargo-watch: Add version 8.4.0

- bucket/dotnet-sdk.json
Use more clear JSONPath and CDN
- Relates to https://github.com/ScoopInstaller/Versions/pull/1089
> dotnet-sdk: Tweak manifest

- bucket/erdtree.json
> erdtree: Add version 1.4.1

- bucket/aliyundrive-webdav.json
> aliyundrive-webdav: Add version 2.1.0

- bucket/deepstream.json
> deepstream: Remove extract_dir

- bucket/mingw.json
> mingw : update to version 12.2.0-rt_v10-rev2

- bucket/portal.json
> portal: Add version 1.2.3

- bucket/offlineinsiderenroll.json
> offlineinsiderenroll: update to version 0.6.4

- bucket/lzip.json
Latest available binary is 64bit-only.
> lzip: Update to version 1.22

- bucket/lux.json
* Add arm64 architecture
Closes #XXXX
> lux: Update to version 0.17.2

- bucket/slang.json
Closes #4603 
Upstreamed from my personal bucket: https://github.com/Locietta/sniffer/blob/master/bucket/slang.json
> slang: Add version 0.26.0

- bucket/dxc.json
> dxc: Add version 1.7.2212.1

- bucket/air.json
> air: Add version 1.42.0

- bucket/gactions.json
> gactions: Add version 3.2.1

- bucket/simple-http-server.json
> fix(simple-http-server): autoupdate fix

- bucket/ab.json
> Add ab (Apache HTTP server benchmarking tool)

- bucket/talosctl.json
Adds talosctl version 1.3.6.
Closes https://github.com/siderolabs/talos/issues/5458
> talosctl: Add version 1.3.6

- bucket/juicefs.json
> Juicefs: Add version 1.0.4

- bucket/eva.json
config location: $env:LocalAppData/NerdyPepperconfig
location: $env:AppData/NerdyPepper
Closes #[10515](https://github.com/ScoopInstaller/Extras/issues/10515) https://github.com/ScoopInstaller/Extras/pull/10551
> eva: Add version 0.3.1

- bucket/ahoy.json
> ahoy: Update to version 2.1.1 and add arm64 architecture

- bucket/flux.json
> flux: Add arm64 architecture support

- bucket/git-town.json
> git-town: Update to version 8.0.0 and fix checkver

- bucket/glslviewer.json
> glslviewer: Update to version 3.2.2 and fix autoupdate

- bucket/dnsproxy.json
Update `checkver` section to brief form (since github link used for `homepage`).
> dnsproxy: Update checkver

- bucket/kusion.json
Close https://github.com/ScoopInstaller/Main/issues/4333
Add [kusion](https://github.com/KusionStack/kusion) to Main
> kusion: add version v0.8.0

- bucket/s5cmd.json
> s5cmd: add version 2.0.0

- bucket/ghostscript.json
> ghostscript: Add installation of registry

- bucket/vcluster.json
> vcluster: Add version 0.15.0

- bucket/tickrs.json
[tickrs](https://github.com/tarkah/tickrs) is a TUI to interact with realtime ticker data.
Relates to #4704 (this is a second attempt on a new branch after making some fixes to the manifest).
> tickrs: Add version 0.14.8

- bucket/android-clt.json
- Add suggestion for Java
- Use dir structure of offical docs (https://developer.android.com/tools/sdkmanager)
- Update `env_set` (https://developer.android.com/tools/variables#envar)
- Update persistence, persist dirs cannot persisted by persist function
> android-clt: Update manifest

- bucket/imagemagick-lean.json
- bucket/imagemagick.json
> imagemagick: Add arm64 architecture

- bucket/ytt.json
> ytt@0.45.0: Add arm64 architecture

- bucket/ijhttp.json
> ijhttp: Add version 231.8770.17

- bucket/caddy.json
> caddy: Add arm64 support

- bucket/oscdimg.json
Closes #4665
- [X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
> oscdimg: Add version 2.56

- bucket/cacert.json
Also added hash extraction.
Closes #4753
> cacert: Update domain

- bucket/sapling.json
Version scheme changed slightly: https://github.com/facebook/sapling/commit/d5544ee9c0ea418198a677fcd61b8ca03e701fac
> sapling: Fix checkver

- bucket/tor.json
Fixed checkver and autoupdate due to site and packaging changes. Also added hash extraction.
> tor: Update to version 0.4.7.13-12.0.4

- bucket/vultr.json
> vultr@2.16.2: Add arm64 architecture

- bucket/pget.json
> pget@0.1.1: Add arm64 architecture

- bucket/chromaprint.json
> chromaprint: Add version 1.5.1

- bucket/nmap.json
> nmap: Fix broken bins and shortcuts

- bucket/graphviz.json
> graphviz@8.0.4: add separate shims for different layout engines

- bucket/wkhtmltopdf.json
wkhtmltopdf: couldn't match '/wkhtmltox-([\d.-]+)\.mxe-cross-' in https://github.com/wkhtmltopdf/packaging/releases
> wkhtmltopdf: Fix checkver

- bucket/nova.json
> nova: Update to version 3.6.3

- bucket/glow.json
Version is now omitted from the filename
> glow: Update to version 1.5.1

- bucket/cpufetch.json
> cpufetch: Update to version 1.04

- bucket/simplex-chat.json
Updates to the last available windows build
> simplex-chat: Update to version 5.1.0 and Fix checkver

- bucket/msys2.json
Noticed this was missing after reading https://www.msys2.org/wiki/arm64/
> msys2: Add clang arm shortcut

- bucket/winget-ps.json
> winget-ps: Update to version 0.2.1

- bucket/grep.json
Switch to the actual binary source
> grep: Update to version 3.8

- bucket/sed.json
Also switch to the actual binary source
> sed: Update to version 4.9

- bucket/pwsh.json
> pwsh: Use checksum file for hash extraction

- bucket/powerline-go.json
* Add 32bit architecture
* Add arm64 architecture
Closes #XXXX
> powerline-go: Update to version 1.24

- bucket/qtifw.json
> qtifw: Add version 4.5.2

- bucket/ov.json
🎑Feature-rich terminal-based text viewer. It is a so-called terminal pager.
Homepage: https://github.com/noborus/ov
> ov: Add version 0.15.0

- bucket/jx.json
> jx@3.10.83: Add arm64 architecture

- bucket/fastfetch.json
Repo has moved to https://github.com/fastfetch-cli/fastfetch
> fastfetch: Fix URLs

- bucket/supabase.json
An open source Firebase alternative
> supabase: Add version 1.68.6

- bucket/trippy.json
> trippy: Add version 0.8.0

- bucket/llama.json
> llama: Add version 1.4.0

- bucket/git.json
- bucket/mingit-busybox.json
- bucket/mingit.json
> (min)git(-busybox): Fix checkver, autoupdate

- bucket/jc.json
Add [jc](https://github.com/kellyjonbrazil/jc).
Closes #4910.
> jc: Add version 1.23.3

- bucket/red-view.json
> red-view: Add version 25jun23

- bucket/lefthook.json
- Relates to https://github.com/evilmartians/lefthook/issues/136
Fast and powerful Git hooks manager for any type of projects
> lefthook: Add version 1.4.6

- bucket/tssh.json
> tssh: Add version 0.1.9 (#4962)

- bucket/trzsz.json
> trzsz: Add version 1.1.5 (#4961)

- bucket/wormhole-william.json
> wormhole-william: Add `64bit` arch

- bucket/fastfetch.json
For smaller files to download
Closes #XXXX
> fastfetch@2.0.4: Add arm64

- bucket/whisper-cpp.json
> whisper-cpp: Update shims

- bucket/prqlc.json
A simple, powerful, pipelined SQL replacement
> prqlc: Add version 0.9.3

- bucket/rustic.json
> rustic: Add version 0.5.4

- scripts/python/uninstall-pep-514.reg
> scripts: fix python uninstall-pep-514.reg

- bucket/lsd.json
> lsd: Update to version 1.0.0

- bucket/globalping.json
> globalping: add version 1.1.0

- bucket/bento4.json
Adds Bento4 MP4 tool to scoop bucket: Main
Closes #5054
> bento4: Add version 1.6.0-640

- bucket/gdisk.json
> gdisk: Add version 1.0.9

- bucket/confluent-cli.json
> confluent-cli: Add version 3.28.0

- bucket/stgit.json
> stgit: Add version 2.3.0

- bucket/hugo.json
See https://github.com/gohugoio/hugo/releases/tag/v0.118.2
Include some fix.
Closes #XXXX
> hugo: Update version to 0.118.2

- bucket/sing-box.json
See https://sing-box.sagernet.org/
**sing-box** is an emerging universal proxy platform, provides many useful features.
The repo now has 4.4k stars.
Closes #5032
> sing-box: Add version 1.4.1

- bucket/evans.json
> evans: Add arm64 version

- bucket/mods.json
See https://github.com/charmbracelet/mods#mods
> mods: Add version 0.2.0

- bucket/bbdown.json
> BBDown: Add version 1.5.9

- bucket/trivy.json
Add Trivy: open-source utility to find vulnerabilities & IaC misconfigurations, SBOM discovery, Cloud scanning, Kubernetes security risks, and more.
More info: https://trivy.dev/
Source: https://github.com/aquasecurity/trivy
> trivy: Add version 0.41.0

- bucket/temporal-cli.json
> temporal-cli: Add version 0.10.5

- bucket/mediamtx.json
> mediamtx: Add version 1.0.3

- bucket/luau-lsp.json
> luau-lsp: Add version 1.22.2

- bucket/rye.json
An Experimental Package Management Solution for Python
> rye: Add version 0.8.0

- bucket/aichat.json
> aichat: Add version 0.8.0

- bucket/docker-buildx.json
> docker-buildx: Add version 0.11.2

- bucket/mysql-lts.json
> mysql-lts: Add version 8.0.34

- bucket/ktlint.json
> ktlint: Add version 1.0.0 (Close #5076)

- bucket/eza.json
[eza ](https://github.com/eza-community/eza) is a modern, maintained replacement for ls, built on [exa](https://github.com/ogham/exa).
`eza` has a better experience than PowerShell's `Get-Item`.
> eza: Add version 0.11.0

- bucket/tfsec.json
> tfsec: Add arm64 version

- bucket/eza.json
- URL has changed to `.zip`
- Extract hash from the checksums
> eza: Update to version 0.11.1

- bucket/bbdown.json
> (chore): touch BBDown.data before adding it to persist

- bucket/frp.json
> frp@0.51.3: Add arm64 version

- bucket/ipcalc.json
Calculates IP broadcast, network, Cisco wildcard mask, and host ranges
> ipcalc: Add version 0.51

- bucket/navidrome.json
Adds the navidrome music server to scoop bucket: Main
Closes #4854
> navidrome: add 0.49.3

- bucket/mill.json
> mill : fix url (#5152)

- bucket/mvndaemon.json
> mvndaemon@1.0-m7: fix checkver (#5160)

- bucket/gitlab-runner.json
> gitlab-runner: Update to version 16.4.1

- bucket/youtube-dl.json
Sorry, I read the contribution guidelines after creating this PR, I will create a new branch than using master.
Closes #5140
> youtube-dl: fixed url

- bucket/lobster.json
Add Lobster language compiler and interpreter.
> lobster: Add version 2023.13

- bucket/gut.json
Add [gut](https://github.com/julien040/gut).
Closes #5192.
> gut: Add version 0.2.10

- bucket/vagrant.json
> fix(5191): Simplistic fix for Vagrant 2.4.0 install error

- bucket/taplo.json
taplo-cli: A TOML toolkit written in Rust
> taplo: add version 0.8.1

- bucket/taplo.json
> taplo: Fix format error

- bucket/zls.json
- Update to version 0.11.0
- Add 32bit architecture
- Fix autoupdate
Closes #5212
> zls@0.11.0: Update to version 0.11.0 and fix autoupdate

- bucket/jpegoptim.json
Add [jpegoptim](https://github.com/tjko/jpegoptim).
Closes #4952
> jpegoptim: Add version 1.5.5

- bucket/postgresql.json
> postgresql@16.0: fix checkver (#5224)

- bucket/adb.json
> adb: remove shim for dmtracedump.exe

- bucket/sd.json
- fix manifest
- add checkver
- update to v1.0.0
> sd@1.0.0: fix manifest

- bucket/ugrep.json
Now has a homepage: https://ugrep.com/
> ugrep: Update homepage, Update to version 4.3.2

- bucket/sqlite.json
> sqlite@3.44.0: convert to 64-bit

- bucket/ghcup.json
> ghcup: Add version 0.1.20.0

- bucket/unison.json
> Unison: add shortcut for unison-gui.exe

- bucket/ccat.json
> ccat@1.1.0: Update links

- bucket/ffsend.json
> ffsend: update to 0.2.76

- bucket/quarkus-cli.json
> Fix for Issue #5229

- bucket/openssl.json
> Openssl@3.2.0: Fix checkver method and add ARM64 version

- bucket/ouch.json
> ouch@0.5.1: Add arm64 version

- bucket/bottom.json
> bottom@0.9.6: Update homepage

- bucket/pipx.json
Install and run Python applications in isolated environments
> pipx: Add version 1.3.3

- bucket/dotter.json
- Fix autoupdate.
- Update to version 0.13.1.
> dotter: Update to version 0.13.1

- bucket/jj.json
Adds jj, a Git-compatible DVCS that is both simple and powerful
> jj: Add version 0.12.0

- bucket/openssl.json
Should now work no matter what version of PowerShell or Windows you're on, and not require admin
> openssl: Fix environment variables (2)

- bucket/libjxl.json
Fixes #5383
- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
> libjxl@0.9.0: update list of package binaries

- bucket/cppcheck.json
> Add a shortcut for the GUI version of Cppcheck.

- bucket/diffsitter.json
- Add arm64 version
- Add hash links to autoupdate.
> diffsitter@0.8.1: Add arm64 version

- bucket/syncthing.json
> syncthing@1.27.2: Add arm64 version

- bucket/vgmstream.json
> Added vgmstream

- bucket/sdcc.json
> sdcc: Update to version 4.3.0

- bucket/kotlin.json
> kotlin: Add missing bin

- bucket/mingw.json
> Update mingw.json to 13.2.0-rt_v11-rev1

- bucket/aqua.json
> aqua: Add version 2.21.3

- bucket/tailspin.json
> tailspin: Add version 2.2.0

- bucket/replibyte.json
> replibyte: Add version 0.10.0

- bucket/lrzsz.json
> lrzsz: Add version 0.12.21rc

- bucket/glfw.json
> glfw: Add version 3.3.8

- bucket/libjpeg-turbo.json
> libjpeg-turbo: Add version 3.0.1

- bucket/cc65.json
> cc65: Add version 6842216289

- bucket/termusic.json
> termusic: Add version 0.7.11

- bucket/rain.json
Create the rain.json scoop recipe (first contribution).
Closes #5443
> rain: Add version 1.7.5

- bucket/flow.json
> flow: fix homepage url

- bucket/imagemagick-lean.json
> imagemagick-lean: Fix `extract_dir`

- bucket/px.json
> Px: Add version 0.9.0

- bucket/meta-package-manager.json
> meta-package-manager: Add version 5.14.2

- bucket/oxlint.json
> oxlint: Add version 0.2.5

- bucket/gifski.json
> gifski: (chore) Switch checkver to github

- bucket/fastfetch.json
Update the file name pattern of fastfetch to match the latest version.
> fastfetch: update binary URL

- bucket/wixtoolset.json
> wixtoolset: Update to version 3.14

- bucket/timoni.json
Closes #5492
First contribution, so be gentle, I wasn't 100% certain how to deal with checksums/git versioning, so I used the existing cue.json to get started. Let me know what you think.
> timoni: Add version 0.19.0

- bucket/qaac.json
> qaac: Update to version 2.81

- bucket/unrar.json
Closes #5558
---
Waiting on ScoopInstaller/Binary#23 to be merged first.
> unrar@7.0.0: Fix hash

- bucket/gallery-dl.json
> gallery-dl@v1.26.7: add config to persist

- bucket/eac3to.json
> eac3to@3.50: update from 3.36

- bucket/boost.json
> boost: Add version 1_84_0

- bucket/espeak-ng.json
> espeak-ng: Add version 1.51

- bucket/wget2.json
Added wget2, successor of wget
Closes #XXXX
> wget2: Add version 2.1.0

- bucket/uv.json
uv is an extremely fast Python package installer and resolver, written in Rust.
> uv: Add version 0.1.2

- bucket/realm.json
> realm: Add version 2.5.3

- bucket/autocorrect.json
> autocorrect: Add version 2.9.0

- bucket/libavif.json
> libavif: Update to version 1.0.4

- bucket/eac3to.json
> eac3to: remove extract_dir to fix installation

- bucket/ollama.json
Closes https://github.com/ScoopInstaller/Extras/issues/12900
Closes https://github.com/ScoopInstaller/Nonportable/issues/271
Relates to https://github.com/ollama/ollama/issues/3012
> ollama: Add version 0.1.28

- bucket/mailpit.json
> mailpit: Add version 1.14.3 (Closes #5573)

- bucket/chromedriver.json
> chromedriver@122.0.6261.128: fix auto-update

- bucket/jdtls.json
- Relates to https://github.com/ScoopInstaller/Scoop/pull/5836
> jdtls: Use `Get-Command` in script

- bucket/boost.json
Relates to https://github.com/ScoopInstaller/Main/pull/5644#issuecomment-2024634408
> boost: Fix pre_install

- bucket/rga.json
> rga: Shim `rga-fzf`

- bucket/teleport.json
upgrade to version 15.2.0
change download url to cdn
> Update teleport to version 15.2.0

- bucket/maven.json
> MAVEN: Update download URL

- bucket/shinyproxy.json
- Closes #5703
The `persist` will work after https://github.com/ScoopInstaller/Scoop/pull/5872
> shinyproxy: Add version 3.0.2

- bucket/metabase.json
> metabase: Add version 0.49.4

- bucket/swift.json
- Wait for next version of Scoop when these are released (currently in develop branch): https://github.com/ScoopInstaller/Scoop/pull/5871 and #5552
> swift@5.10: Fix install script

- bucket/rtools.json
> rtools: Update to version 4.4.6104.6039

- bucket/uutils-coreutils.json
This is a trivial PR. It has a dedicated homepage now, which should be preferred over the repo.
Relates to #5743
Relates to https://github.com/uutils/coreutils/pull/2897
> uutils-coreutils@0.0.23: Update homepage

- bucket/winpython.json
> winpython: Fix bins and shortcuts

- bucket/tlrc.json
> tlrc: Add version 1.9.1

- bucket/butler.json
Adds [butler](https://itch.io/docs/butler/) 15.21.0
> butler: add 15.21.0

- bucket/vim.json
> vim: Change checkver config to stable version

- bucket/granted.json
> granted: Add version 0.24.0

- bucket/erlang.json
- bucket/gnupg.json
- bucket/gpg.json
- bucket/qemu.json
- bucket/tesseract.json
- Relates to https://github.com/ScoopInstaller/Scoop/pull/5294
> (chore): Stop removing '*.nsis'

- bucket/pocketbase.json
> Add pocketbase@0.22.10

- bucket/algol68g.json
- Checked the zip file with virustotal manually
> algol68g: Add version 3.5.1

- bucket/mingw-winlibs.json
> mingw-winlibs: Update to version 14.1.0-11.0.1-r1

- bucket/aspell.json
> aspell: Update to version 0.60.8.1-2

- bucket/lynx.json
> lynx@2.9.1: Fix OpenSSL version

- bucket/go.json
> go: Fix GOBIN

- bucket/vfox.json
> vfox: fix hash alway failed.

- bucket/shinyproxy.json
> shinyproxy: Update to version 3.1.0

- bucket/vhs.json
Added `extract_dir`
Closes #5837
> Add extract_dir to vhs.json

- bucket/unrar.json
- Closes #5843
---
Waiting on ScoopInstaller/Binary#24 to be merged first.
> unrar@7.0.1: Fix hash

- bucket/python.json
> python: Tweak manifest

- bucket/busybox.json
> busybox@5301-gda71f7c57: Add arm64 binary

- bucket/busybox-lean.json
> busybox-lean@5301-gda71f7c57: Add arm64 binary

- bucket/fastfetch.json
> fastfetch@2.13.1: Add arm64 binary

- bucket/yazi.json
> yazi@0.25: Add bin `ya.exe`

- bucket/garnet.json
> garnet: Add version 1.0.11

- bucket/ollama.json
> ollama: Add autoupdate.hash

- bucket/ffuf.json
> ffuf: Add version 2.1.0

- bucket/winpython.json
> winpython@3.12.4.1: Fix bins and shortcuts

- bucket/mysql-workbench.json
> mysql-workbench: Fix `extract_dir`

- bucket/reviewdog.json
> reviewdog@0.20.0: Add arm64 version

- bucket/coq.json
> coq: Fix `env_set`

- bucket/bazelisk.json
> bazelisk: Add version 1.2.0

- bucket/subconverter.json
Closes [#13629](https://github.com/ScoopInstaller/Extras/issues/13629)
> subconverter: Add version 0.9.0

- bucket/uv.json
> uv: Add bin `uvx.exe`

- bucket/mprocs.json
- Update to version 0.7.1.
- Fix autoupdate url.
> mprocs: Update to version 0.7.1

- bucket/hostctl.json
> hostctl@1.1.4: Add arm64 version

- bucket/qaac.json
> qaac@2.82: Update autoupdate, and add 2 persists

- bucket/ghcup.json
Fixed the wrong command in ```note``` to the proper one used for setting up ghc.
> ghcup: Fix command tip

- bucket/qemu.json
> qemu: Fix autoupdate.url

- bucket/nim.json
- bucket/stack.json
Should've checked before if there were others with the same potential issue.
Relates to #5806
> nim, stack: Fix deprecated (un)install warnings

- bucket/iroh.json
Another tool created by IPFS team
Closes #XXXX
> iroh: Add version 0.21.0

- bucket/podman.json
> podman@5.2.0: Fix installer.script

- bucket/pget.json
> pget: Update to version 0.2.1

- bucket/slang.json
- [v] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
> slang: Update to version 2024.9.1

- bucket/wcurl.json
---
More details about the script's relationship with the `curl` project:
- https://daniel.haxx.se/blog/2024/07/03/wcurl-is-here/
- https://daniel.haxx.se/blog/2024/08/08/curl-welcomes-wcurl-to-the-team/
> wcurl: Add version 2024.07.10

- bucket/colortool.json
https://github.com/Microsoft/console -> https://github.com/microsoft/terminal
> colortool: Update repo url

- bucket/config-file-validator.json
Cross Platform tool to validate configuration files
> config-file-validator: Add version 1.7.1

- bucket/oidn.json
> oidn: Add version 2.3.0

- bucket/cwrsync.json
> cwrsync: Fix manifest

- bucket/tf.json
This PR adds support for [tf](https://github.com/dex4er/tf) a tool to make Terraform output more usable.
> tf: Add version 2.10.0

- bucket/bicep.json
Bicep also has a ARM64 binary.
<https://github.com/Azure/bicep/releases/tag/v0.29.47>
> bicep@0.30.3: Add arm64

- bucket/kotlin-native.json
> kotlin-native: Update to version 2.0.20 & Fix autoupdate

- bucket/ast-grep.json
> ast-grep: Update to version 0.27.3

- bucket/git-absorb.json
> git-absorb: Add version 0.6.15

- bucket/rye.json
Maintenance of rye has been moved to https://github.com/astral-sh
> rye: Update URLs

- bucket/xming.json
Closes https://github.com/ScoopInstaller/Main/issues/6215
> xming: Fixed the download issue due to invalid characters in filename

- bucket/uv.json
https://github.com/astral-sh/uv/ points to the dedicated homepage, so it should be preferred over the repo itself.
This is a trivial PR. (I feel there's no need to create an issue about it.)
> uv@0.4.17: Update homepage

- bucket/nmap.json
Closes #6247
Relates to #4826 and #4822
> nmap: Fix shortcuts

- bucket/megatools.json
> megatools: Update to version 1.11.1.20241028

- bucket/f2.json
- Update version to v2.0.1.
- Update homepage link to new docs website.
> f2: Update to v2.0.3

- bucket/php-nts.json
- bucket/php.json
> php(-nts)@8.3.14: Allow update to 8.4 by having auto-update look for vs17 builds

- bucket/scala.json
> scala@3.6.2: Use MSI installer and fix checkver.hash

- bucket/process-governor.json
https://github.com/lowleveldesign/process-governor/releases/tag/3.0.24342
><h2>Release notes</h2>
><ul>
><li>Procgov is now <strong>one executable (procgov.exe)</strong>. It is 64-bit (compiled with NativeAOT) but works with both 32-bit and 64-bit applications.</li>
Closes #6368
> process-governor: Fix bins

- bucket/tesseract.json
Tesseract now release win-build via GitHub Workflow, so change its download repo.
> tesseract: Update to version 5.5.0.20241111

- bucket/vcpkg.json
> vcpkg: Disable telemetry by default (Closes #6413)

- bucket/crystal.json
This adds the Crystal Language. Closes #6127
> crystal: Add version 1.40.0

- bucket/dyff.json
This PR adds [dyff](https://github.com/homeport/dyff).
> dyff@1.9.4: Add manifest

- bucket/bat.json
https://github.com/sharkdp/bat#configuration-file
https://github.com/sharkdp/bat?tab=readme-ov-file#adding-new-syntaxes--language-definitions
> bat: Persist configs

- bucket/weasyprint.json
> weasyprint: Add version 63.1

- bucket/oracle-instant-client-odbc.json
- bucket/oracle-instant-client-sdk.json
- bucket/oracle-instant-client-sqlplus.json
- bucket/oracle-instant-client.json
Update to 23.6.0 and remove 32bit.
> oracle-instant-client: Update to version 23.6.0.24.10

- bucket/yamlfmt.json
> yamlfmt: Add version 0.15.0

- bucket/psqlodbc.json
> psqlodbc: Fix 'extract_dir' for 64bit

- bucket/superfile.json
> superfile: Add version 1.1.7.1

- bucket/wixtoolset.json
Don't update to prerelease version.
- Closes #6530
- Closes #6531
> wixtoolset: Revert to version 5.0.2

- bucket/flac.json
Switched to github release,
Updated to 1.5.0
- Closes #6534
- Closes #6529
> flac@1.5.0: Update ver, switched to official xiph/flac git

- bucket/nanazip.json
> nanazip: Update to version 5.0.1252.0

- bucket/helmfile.json
> helmfile@0.171.0: Add arm64 version

- bucket/vegeta.json
> vegeta: Add version 12.12.0

- bucket/sqruff.json
> sqruff: Add version 0.22.0

- bucket/flac.json
- Relates to #6520
- Relates to #6534
> flac@1.5.0: Add autoupdate.hash

- bucket/chroot.json
Added a new manifest for version `2.0` of the `chroot` tool. `chroot` is a popular Linux tool that allows you to run a program that cannot access files outside of a specific file system folder tree.
> chroot: Add version 2.0

- bucket/c3.json
This pr adds `c3` compiler.
[website](https://c3-lang.org/)
[github repo](https://github.com/c3lang/c3c)
> c3: Add version 0.6.6

- bucket/avro-tools.json
Fix the version check for this Apache project by using the GitHub release links.
Previous regex doesn't work anymore due to bad update of the upstream project page.
> avro-tools@1.12.0: Update Manifest

- bucket/opencv.json
> opencv: Add version 4.10.0

- bucket/pkl-cli.json
> pkl-cli: Add version 0.27.1

- bucket/fedify.json
Add [Fedify CLI](https://fedify.dev/cli).
> fedify: Add version 1.4.1

- bucket/hatch.json
Add hatch.
Hatch is a modern, extensible Python project manager.
> hatch@1.14.0: Add hatch

- bucket/popeye.json
> popeye@0.21.5: create new entry for popeye

- bucket/terrascan.json
This PR adds [Terrascan](https://runterrascan.io/).
> terrascan@1.19.9: Add manifest

- bucket/mongodb.json
> mongodb: Fix autoupdate.hash

- bucket/jreleaser.json
> jreleaser: Add version 1.16.0

- bucket/unrar.json
> unrar: Update to version 7.10

- bucket/mdq.json
This PR adds [mdq](https://github.com/yshavit/mdq).
> mdq@0.3.0: Add manifest

- bucket/git-filter-repo.json
> git-filter-repo: Fix bug for Windows PowerShell

- bucket/innounp.json
> innounp: Use GitHub download URL

- bucket/rubberband.json
> rubberband: Add version 4.0.0

- bucket/auto-doc.json
This PR adds [auto-doc](https://github.com/tj-actions/auto-doc).
> auto-doc@3.5.0: Add manifest

- bucket/zigup.json
> zigup@2025_01_02: fix autoupdate

- bucket/garnet.json
> garnet@1.0.60: Fix manifest

- bucket/git.json
> git: Update to version 2.49.0 and remove 32bit

- bucket/magic-wormhole-rs.json
> magic-wormhole-rs: Update to version 0.7.5, Fix `url`

- bucket/selenium-manager.json
> selenium-manager: Update `homepage` to documentation link

- bucket/libavif.json
> libavif@1.2.1: bump and fix autoupdate

- bucket/rtools.json
> rtools: Update to version 4.5.6536.6492

- bucket/podman-tui.json
> podman-tui: Add version 1.5.0

- bucket/macchina.json
- Fix autoupdate.
- Update to the latest version.
> macchina: Update to version 6.4.0, fix autoupdate, add arm64 version

- bucket/dust.json
The tag has the version, none of that is necessary.
> dust: Cleanup `checkver`

- bucket/dive.json
Add arm64 version.
Closes #6651
> dive@0.13.1: Add arm64 version

- bucket/dark.json
- Closes https://github.com/ScoopInstaller/Binary/issues/28
> dark: Update to version 3.14.1

- bucket/kubo.json
kubo@0.33.2: Update to 0.34.1, Remove architecture "32bit", Add architecture 
Closes #6748
- [ x] Use conventional PR title: `<manifest-name[@version]|chore>: <general summary of the pull request>`
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)
> kubo@0.33.2: Update to 0.34.1, Remove architecture "32bit", Add architecture 

- bucket/git-interactive-rebase-tool.json
> git-interactive-rebase-tool: Update to version 2.4.1 and add ARM64

- bucket/pixi.json
add https://github.com/prefix-dev/pixi
Fixes https://github.com/ScoopInstaller/Main/issues/5773
> pixi: Add version 0.45.0

- bucket/oh-my-posh.json
Closes: #6420 
from '.sha256' to 'checksums.txt'
> oh-my-posh: Update autoupdate and pre_install

- bucket/openssl.json
> openssl: Use hardlinks instead of symlinks

- bucket/scons.json
Fixes check version regex.
Closes #6771
> scons: Fix checkver regex

- bucket/mdq.json
This PR fixes MDQ as the release artifact URL was changed.
> mdq@0.7.2: Fix update url

- bucket/presentmon.json
- Addresses:
- https://github.com/ScoopInstaller/Main/issues/6787
- https://github.com/ScoopInstaller/Main/pull/6788
> presentmon: Fix auto update & remove support for 32 bit builds.

- bucket/scoop-shim.json
> scoop-shim: update to v1.1.0

- bucket/nim.json
Shim for [Atlas Package Cloner](https://github.com/nim-lang/atlas/blob/master/doc/atlas.md) added as part of package.
> nim@2.2.4: fix for atlas.exe shim

- bucket/highlight.json
relates to https://github.com/ScoopInstaller/Scoop/issues/6372
requires https://github.com/ScoopInstaller/Scoop/pull/6373
> highlight@4.16: fix extract_dir

- bucket/go-size-analyzer.json
> go-size-analyzer: update to 1.9.2

- bucket/nfpm.json
fix https://github.com/ScoopInstaller/Extras/issues/15452
and https://github.com/ScoopInstaller/Extras/pull/15453#issuecomment-2908106737
let's merge it to allow full features in goreleaser
> nfpm@2.42.1: add nfpm

- bucket/mcfly.json
> mcfly: Add version 0.9.3

- bucket/podman-tui.json
> podman-tui@1.6.1: Fix `extract_dir`

- bucket/uv.json
> uv@0.7.14: Add ARM64 for uv

- bucket/rebar3.json
Closes #4699
I've checked that manifest gets updated automatically.
> rebar3: Add version 3.25.0

- bucket/localstack.json
> localstack: Add version 4.5.0

- bucket/qsv.json
Looks like a big rebrand. Archive comes with a bunch of different builds, I picked the most reasonable one. [See Readme](https://github.com/dathere/qsv?tab=readme-ov-file#variants).
Their Readme mentions Scoop as an installation method, so it's fairly important that this is up to date.
Relates to #773
> qsv: Fix and Update to version 6.0.1

- bucket/coreutils.json
- bucket/findutils.json
- bucket/gzip.json
- bucket/iconv.json
- bucket/msys.json
- bucket/tar.json
- bucket/telnet.json
> (chore): Update all MinGW homepages to point to Sourceforge.

- bucket/yara-x.json
> yara-x: Add version 1.4.0

- bucket/ngrok.json
Updates the description, notes, and license identifier to be correct.
> ngrok@3.25.0: fix: Update description, notes, and license identifier

- bucket/openconnect.json
Open multi-protocol SSL VPN client
P.S., PR #7000 🥳
> openconnect: Add version 9.12

- bucket/c3.json
> c3: Update hash

- bucket/clink.json
- Set environment variable `CLINK_DIR` when installing.
> clink: `env_set` CLINK_DIR

- bucket/whisper-cpp.json
See: https://github.com/ggml-org/whisper.cpp/blob/master/examples/deprecation-warning/README.md
> Whisper-cpp@1.7.6: Binaries have been renamed

- bucket/curlie.json
> curlie: Update `homepage` and `autoupdate`

- bucket/unshield.json
> unshield: Update to version 1.6.2

- bucket/gitoxide.json
> gitoxide: add version 0.45.0
