ScoopInstaller/Main

bucket/unshield.json
* supersedes https://github.com/ScoopInstaller/Extras/pull/8800
* **[Unshield](https://github.com/twogood/unshield)** is a tool and library to extract CAB files from **InstallShield** installers.
**NOTES**:
* This app is in *Main* because it is an **unpacker**.
* In order to update this app, we need to manually build it. I think it's fine because:
(1) *Unshield* does not update very often (about once a year)
(2) This app can be useful for us to **extract the installer** of other apps.
* I built the binary with the following steps:
(1) Download source code from https://github.com/twogood/unshield/releases and extract the file.
(2) Install [main/openssl](https://github.com/ScoopInstaller/Main/blob/master/bucket/openssl.json) and [extras/zlib](https://github.com/ScoopInstaller/Extras/blob/mas …
=> unshield: Add version 1.5.1

bucket/bitwarden-cli.json
Bitwarden consolidated all of their clients (except the mobile application) into a single repository, https://github.com/bitwarden/clients.  All current and future releases of bitwarden-cli will be released there.  As we can no longer assume that a new release on that repo is for the CLI, checkver logic was updated to parse the releases.atom feed. This updated manifest allows scoop to offer current versions of the Bitwarden CLI.
Closes #3793
=> Change Repo of Bitwarden CLI

bucket/octosql.json
- Closes #3803
- Nothing to persist, config and downloaded plugins stored in `~/.octosql/`
=> octosql: Add version 0.9.2

bucket/gotop.json
A terminal based graphical activity monitor inspired by gtop and vtop
=> gotop: Add version 4.1.4

bucket/xmlstarlet.json
Xmlstarlet is distributed as `xmlstarlet` binary under *nix systems but on Windows - it is installed as `xml`. This causes issues with scripts portability between the systems. Adding additional `xmlstarlet` alias to the existing `xml` binary solves the issue.
=> xmlstarlet: *nix compatibility

bucket/nodejs.json
See https://github.com/ScoopInstaller/Main/commit/c4135181190af27ccc1acb02925a1e9d4450fd99#commitcomment-81309371
=> nodejs: Add 32bit support back

bucket/cygwin.json
=> cygwin: Fix `installer.args`

bucket/maven.json
…f www.apache.org so that older versions of maven can be installed easily.
Closes #3836
=> fix(#3836): change maven download URL to archive.apache.org

bucket/avro-tools.json
- Relates to https://github.com/ScoopInstaller/Main/runs/7930355088?check_suite_focus=true#step:3:195
- Untested due to away from computer
- Uses mirror instead of direct from apache.org
=> avro-tools: Update to version 1.11.1, use mirror

bucket/lynx.json
OpenSSL has been updated to 1.1.1q
Closes #3846
=> openssl updated to 1.1.1q

bucket/helmfile.json
Since Helmfile project repository was moved to another owner, updated with correct urls and releases accordingly
=> helmfile: updated urls due to repository migration

bucket/spark.json
Relates to Excavator unable to update to latest version. This is because the default build is now with Hadoop 3. I have opened a PR in Versions bucket to add the version with Hadoop 2, among others.
Merge this after [Versions #624](https://github.com/ScoopInstaller/Versions/pull/624) is merged.
=> spark: Update to version 3.3.0, Hadoop 3

bucket/gsudo.json
Starting at v1.4.0, gsudo have different builds for x86 and x64, each one on it's separate folder.
=> gsudo: Update to version 1.4.0. Support for x86 and x64 platforms (breaking change)

bucket/heroku-cli.json
=> heroku-cli: Fix arguments in `pre_install` script

bucket/nircmd.json
> It's recommended to copy the executable of NirCmd (nircmd.exe) to your windows directory, or to any other folder listed in your PATH environment variable, so you won't need to type the full path of nircmd in each time that you want to use it.
=> nircmd: Add `nircmd.exe` to `bin`

bucket/genact.json
genact has been updated to 1.0.0. 
- Github release: https://github.com/svenstaro/genact/releases/tag/v1.0.0
---
=> genact: Update to version 1.0.0

bucket/elixir.json
Use Elixir 1.14 from hex.pm instead of from github release page. The package is version that compiled lowest OTP. In this case, it's OTP 23.
Closes #3886
=> elixir@1.14.0: make Elixir 1.14 work as expected

bucket/elixir.json
Relates to #3921 
It seems that the first match group is taken as sha1? We don't want that.
Tested on a tmp bucket https://github.com/princemaple/tmp-bucket. Manged to install `@1.14.0-otp-25`.
=> fix(elixir): make install elixir@1.14.0-otp-25 work

bucket/rizin.json
some of to rizin tools are not created in `shims/`
this PR adds
- `rz-agent.exe`
- `rz-asm.exe`
- `rz-sign.exe`
- `rz-test.exe`
to `bin` field in `bucket/rizin.json`
```
> dir %userprofile%\scoop\apps\rizin\current\bin\rz-*.exe
rz-agent.exe
rz-asm.exe
rz-ax.exe
rz-bin.exe
rz-diff.exe
rz-find.exe
rz-gg.exe
rz-hash.exe
rz-run.exe
rz-sign.exe
rz-test.exe
```
```
> dir %userprofile%\scoop\shims\rz-*.exe
rz-ax.exe
rz-bin.exe
rz-diff.exe
rz-find.exe
rz-gg.exe
rz-hash.exe
rz-run.exe    
```
=> rizin: Add missing command line tools to PATH

bucket/winget.json
- Update Url to Stable Release
- use checkver: "github"
=> winget: Update to version 1.3.2091 (Stable)

bucket/pyenv.json
When trying to use pyenv with another tool called pyenv-win, I found out it was not working because `PYENV_HOME` env var was missing. 
This led me to look at the setup instruction (https://github.com/pyenv-win/pyenv-win#add-system-settings), I found the following: 
* `PYENV_ROOT` and `PYENV_HOME` are expected to be set
* `pyenv-win/bin` should be in PATH because it contains already all the necessary script for powershell, CMD and Git bash. 
Regarding the second point, I don't think there should be any `bin` in the manifest, as no shims are required. 
This seem to be the way to handle such tools (see my question https://github.com/ScoopInstaller/Scoop/discussions/5156 for details)
With this updated manifest, I can correctly use [pyenv-win-venv](https://github.com/pyenv-win/pyenv-win-venv) …
=> pyenv@3.1.1: Improve manifest according to pyenv setup instruction

bucket/tfsec.json
Added tfsec.json in the bucket
=> tfsec: Add version 1.28.0

bucket/gosec.json
Added gosec.json in the bucket
=> gosec: Add version 2.13.1

bucket/jx.json
Adds custom regex to filter out .sbom file
Prevents grabbing the wrong hash for jx by providing a custom regex to the manifest. Issue is that the default regex is actually grabbing the `.zip.sbom` hash since it shows up first in the `jx-checksums.txt` file.  
```sh
Searching hash for jx-windows-amd64.zip in https://github.com/jenkins-x/jx/releases/download/v3.5.33/jx-checksums.txt
DEBUG[1664466355] $regex = ^\s*([a-fA-F0-9]+)\s*$ -> C:\Users\..\scoop\apps\scoop\current\lib\autoupdate.ps1:53:5
Found: 66a631587dc1c59b8be25290c245783eeec9a4d1ab5cddbb7247156ea0989c1a using Extract Mode
```
```sh
Searching hash for jx-windows-amd64.zip in https://github.com/jenkins-x/jx/releases/download/v3.5.33/jx-checksums.txt
DEBUG[1664466410] $regex = …
```
=> jx: Adds hash regex

bucket/tealdeer.json
The `TEALDEER_CACHE_DIR` env variable is now deprecated, use the `cache_dir` option in the config file instead.
Changelog:
[https://github.com/dbrgn/tealdeer/blob/main/CHANGELOG.md](https://github.com/dbrgn/tealdeer/blob/main/CHANGELOG.md)
=> tealdeer: Remove TEALDEER_CACHE_DIR environment variable

bucket/git.json
The new scalar.exe that is now bundled with git can also be used when installed with scoop.
=> git: add scalar.exe to bin entry

bucket/biber.json
Adds the biber binary for use with latex installations. Does not require perl as it is already compiled with MSVC.
=> Biber: Add Version 2.18

bucket/wakatime-cli.json
Adds the wakatime-cli, a command line interface to [WakaTime](http://wakatime.com/) used by all WakaTime [text editor plugins](http://wakatime.com/editors).
=> wakatime-cli: Add version 1.55.2

bucket/7zip.json
- `7zFM.exe`: Useful if you want to open the GUI file manager from the command line.
- `7zG.exe`: This is similar to `7z.exe`, except that it displays the progress in a separate GUI window, instead of the console.
=> 7zip: Add `7zFM.exe` and `7zG.exe` to bin entry

bucket/fzf.json
So what would the order of architecture be with `arm64`? Something like: `64bit`, `32bit`, `arm64`?
=> fzf: Add `arm64` architecture

bucket/gobuster.json
The structure of the releases has changed with the latest version. Additionally, an arm64 binary is now available.
https://github.com/OJ/gobuster/releases
=> gobuster: Fix urls and add arm64 architecture

bucket/7zip.json
7-zip doesn't provides MSI installer for ARM64, so use 7zr as bridge.
=> 7zip: Add ARM64 arch

bucket/procs.json
Fix procs manifes by removing `extract_dir` ([since v0.13.3](https://github.com/dalance/procs/blob/master/CHANGELOG.md) release zip for Windows has the exe at toplevel).
=> procs@0.13.3: Remove extract_dir

bucket/cheat.json
* For the cheatsheets path to be set correctly, the configuration file should be initialized after the environment variables are set.
* Set `pager` to more, 'more' is recommended on Windows.
=> cheat: Fix install

bucket/v2ray.json
- Scoop already hash-checked the downloaded files
- This step caused some distress for the main users of the app
- Removing the verification will not cause security issue
Closes #4057
=> v2ray: Remove binary verification step(installer.script)

bucket/q-dns.json
There are [some other projects](https://github.com/search?q=q) called q too, and it is called q-dns in its own  linux package repositories.
So I named the file as q-dns.json
Closes #4045
=> q-dns: Add version 0.8.3

bucket/zig.json
Update zig to version 0.10.0
The [official download](https://ziglang.org/download/) page doesn't have a 32 bit build for Windows platform anymore (nor the [official Github repo](https://github.com/ziglang/zig/releases)) so I removed that from the manifest.
=> zig: update to version 0.10.0

bucket/sqlcl.json
- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
Already Verified:
> sql -v
> SQLcl: Release 22.3.1.0 Production Build: 22.3.1.285.1828
=> sqlcl: update to 22.3.1.285.1825

bucket/rust-msvc.json, bucket/rust.json
https://blog.rust-lang.org/2022/07/01/RLS-deprecation.html
Fixes:
```
Creating shim for 'rls'.
Can't shim 'bin\rls.exe': File doesn't exist.
```
=> rust, rust-msvc: Remove rls bin

bucket/pwsh.json
This allows installing native arm64 binaries on arm64 systems.
=> Add arm64 version to pwsh

bucket/doggo.json
Add [doggo](https://github.com/mr-karan/doggo/), a command-line DNS client.
Closes #4044.
=> doggo: Add version 0.5.4

bucket/jo.json
Fixes:
```
Can't shim 'jo.exe': File doesn't exist.
```
=> jo: Fix bin

bucket/postgresql.json
A problem, caused by using the old line `Invoke-ExternalCommand -FilePath \"$dir\\bin\\initdb.exe\" -ArgumentList \"--username=postgres --encoding=UTF8 --locale=en --lc-collate=C\" | Out-Null`, occurs in Windows so that people could not login by the default superuser Id "postgres"
By migration to the new line `Invoke-ExternalCommand -FilePath \"$dir\\bin\\initdb.exe\" -ArgumentList @('--username=postgres', '--encoding=UTF8', '--locale=en', '--lc-collate=C') | Out-Null`, the issue is eliminated.
Relates to #3832
=> Fix "FATAL: role "postgres" does not exist"

bucket/ddosify.json, bucket/duf.json, bucket/fx.json, bucket/gron.json, bucket/hopp-cli.json, bucket/octosql.json
Add arm64 architecture for some apps.
=> chore: Add arm64 architecture for some apps

bucket/mdcat.json
Since mdcat moved back to github from [codeberg](https://codeberg.org/flausch/mdcat), and binaries release restored.
As per [v0.29.0 release notes](https://github.com/lunaryorn/mdcat/releases/tag/mdcat-0.29.0).
Closes #3914.
=> mdcat: Update links

bucket/python.json, scripts/python/install-pep-514.reg
----
I added a new variable named `$py_archLabel` in `pre_install` script as `$bit` is not enough to distinguish ARM64 from x64.
| `$architecture` | `$py_archLabel` | `$bit` | `DisplayName`[^1]        | `SysArchitecture`[^2] |
|-----------------|-----------------|--------|--------------------------|-----------------------|
| `64bit`         | `64-bit`        | `64`   | `Python 3.11.0 (64-bit)` | `64bit`               |
| `32bit`         | `32-bit`        | `32`   | `Python 3.11.0 (32-bit)` | `32bit`               |
| `arm64`         | `ARM64`         | `64`   | `Python 3.11.0 (ARM64)`  | `64bit`               |
[^1]: Those architecture names in parentheses follow the names used in [Python 3.11.0 release note][1].
[^2]: Those `SysArchitecture` values are intended to be read by [CPython's …
=> python: Add arm64 architecture

bucket/neovim.json
Currently the tag for the latest release is stable and cannot be versioned, so checkver will be modified and updated to v0.8.1.
=> neovim: Fix checkver and update to version 0.8.1

bucket/ytt.json
This PR adds manifest for [ytt](https://github.com/vmware-tanzu/carvel-ytt), YAML templating tool that works on YAML structure instead of text.
Closes #4137
=> ytt: Add version 0.44.0

bucket/dotnet-sdk.json
Dotnet 7 has been released at the beginning of November. Autoupdate didn't work because Microsoft [renamed the release type current to sts](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#release-types) (Standard Term Support).
This PR also updates dotnet-sdk version to 7.0.100.
I tested these changes on my local install (x64).
=> dotnet-sdk: Update to version 7.0.100 and fix autoupdate

bucket/base64.json
Added freeware base64.exe, which is a conversion of the linux utility
=> base64: Add version 1.1.0

bucket/fio.json
The current `fio` manifest uses https://bsdio.com/fio as its `checkver` distribution source, and this is no longer in sync with latest releases.
The `fio` maintainer started self-publishing releases of its Windows installer via GitHub, as recently as Aug 9 2022 (starting at version 3.31). 
View the maintainer's official GitHub repository here: https://github.com/axboe/fio/releases (mirror of https://git.kernel.dk/cgit/fio)
1. Closes #4157 
2. Updates `fio` manifest version to `3.33`
=> fio: change source for checkver/autoupdate to GitHub releases

bucket/sapling.json
Since the version schema is `VERSION.%Y%m%d-%H%M%S-HASH` format, checkver parses version, date, time and hash.
[#208](https://github.com/facebook/sapling/pull/208) shows `VERSION-%Y%m%d-%H%M%S-HASH` but it is actually `VERSION.%Y%m%d-%H%M%S-HASH`  by [tag-name.sh](https://github.com/facebook/sapling/blob/main/ci/tag-name.sh#L10) is parsed.
=> sapling: Fix checkver

bucket/glab.json
*I read the `CONTRIBUTING` document, and it seemed that issues are meant for deciding whether a new package gets accepted or for changes to the core. If I misunderstood, please close this MR, and I'll create an issue to discuss this update.*
This PR updates the `glab` Scoop bucket.
- `glab` is updated to version `1.23.0`
Apart from updating the package, this PR also changes the origin (ownership) of the formula
GitLab is now the official maintainer of the `glab` package.
- Archived original repo: https://github.com/profclems/glab
- Announcement issue: https://github.com/profclems/glab/issues/983
- The new home for the project https://gitlab.com/gitlab-org/cli
- Release mentioned in this PR https://gitlab.com/gitlab-org/cli/-/releases/v1.23.0
I've made similar PR for homebrew: …
=> glab@1.23.0 - move to GitLab and update version

bucket/sapling.json
Updated so that commands in notes can be copied and pasted as they are.
=> sapling: updated commands in notes

bucket/dart-sass-embedded.json
Move to main to satisfy future dependency requirement from app in main.
Related to https://github.com/ScoopInstaller/Extras/pull/9875, https://github.com/ScoopInstaller/Extras/pull/9857, https://github.com/ScoopInstaller/Extras/issues/9856
=> dart-sass-embedded: Move from extras to main

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/hash-error.yml
Enable blank issues when the new template is not used by default in Scoop Core.
I'll commit to other official buckets when this is merged.
Please see https://github.com/niheaven/scoop-sysinternals/issues/new?template=hash-error.yml&title=process-explorer%4017.02%3a+hash+check+failed for the new template.
=> (chore): Add new 'hash-error' issue template

bucket/certstrap.json
=> certstrap: Add version 1.3.0

bucket/traefik.json
Fixes for traefik:
- fix checkver (removed previously in 62d7fec);
- update to actual version;
- add arm64 architecture.
=> traefik: Fix checkver, add arm64

bucket/gopass.json
Fixes for gopass:
- add hash regex to filter out .sbom files;
- add arm64 architecture.
Prevents grabbing the wrong hash for gopass by using a custom regex in the manifest. The issue is that the default regex is actually grabbing the `*.zip.sbom` hash since it appears first in the `gopass_$version_SHA256SUMS` file:
```
0830842e11b5079d0d31ad6d60374c8b0d6142d2bdc9ce26b3de93316c2701f8  gopass-1.15.0-windows-amd64.zip.sbom
...
fa914a3dd607bab15cf7d70099b705ce20d95359bd91b6ce03c177bb099ee672  gopass-1.15.0-windows-amd64.zip
```
This should prevent repeating hash issues on autoupdate (#3800, #3909, #4105, #4171, #4194).
Relates to #4105.
=> gopass: Add hash regex, add arm64

bucket/imagemagick-lean.json, bucket/imagemagick.json
Fixes https://github.com/ScoopInstaller/Main/issues/4214  
ImageMagick deleted version 7.1.0-53 so scoop wasn't be able to install it so I did change version number and download URL.
=> ImageMagick@7.1.0-54: Update since ImageMagick deleted previous version so installation fails

bucket/sapling.json
* sapling has changed version schema from `MAJOR.MINOR-%Y%m%d-%H%M%S-HASH` to `MAJOR.MINOR-%Y%m%d-%H%M%S-rHASH`. [360873f](https://github.com/facebook/sapling/commit/360873f1498a5a8fe313f861f273bd2b49eb9940)
* sapling has changed versioning schema from from `MAJOR.MINOR-%Y%m%d-%H%M%S-rHASH` to `MAJOR.MINOR-%Y%m%d-%H%M%S-hHASH`. [388343c](https://github.com/facebook/sapling/commit/388343cc8b14039e12a952a2f56c451ccdd0181e)
* sapling: Update version to 0.1.20221213.150011.h9b0acf12
Closes #XXXX
=> sapling: fix checkver.regex and update version

bucket/passbolt-cli.json
adds manifest for passbolt-cli starting at v0.1.9
Closes #4221
=> passbolt-cli: adds v0.1.9

bucket/osv-scanner.json
This PR adds the new Google [osv-scanner](https://github.com/google/osv-scanner) a tool to enable looking up vulnerabilities from project dependencies.
I'll link an [Article](https://www.theregister.com/2022/12/15/google_debuts_osvscanner_a_gobased/) from [The Register](https://www.theregister.com/) for context.
=> osv-scanner: Add version 1.0.0

bucket/nircmd.json
`nircmd.exe` creates a brief ghost window on silent commands (such as `execmd`) due to the shim; adding it directly to path fixes the problem.
=> nircmd: Add to path instead of shimming

bucket/ouch.json
The executable file is not at the top level causing the shim creation to fail.
=> ouch: Add `extract_dir`

bucket/rhash.json
A console utility for computing and verifying hash sums of files.
Config file is located at `$env:USERPROFILE\rhashrc` or `$env:APPDATA\RHash\rhashrc`.
=> rhash: Add version 1.4.3

bucket/scrcpy.json
Closes #4268 
Seems like in 1.25 scrcpy is packed in a dir in the zip file
=> scrcpy: fix shim error

bucket/gpac.json
MP4Client is being removed from GPAC since 2.2-rev0. See [GPAC 2.2](https://gpac.wp.imt.fr/2022/12/19/gpac-2-2/).
=> gpac: Remove mp4client.exe

bucket/git.json
Resolve warning when using git:
warning: git-credential-manager-core was renamed to git-credential-manager
warning: see https://aka.ms/gcm/rename for more information
=> git@2.39.0.windows.2: update notes

bucket/qrencode.json
PowerShell 5 only supports line breaks after pipe symbols (without a backtick).
Fixes #4263
=> qrencode: Fix installation for PowerShell 5

bucket/glslang.json
It works only on 64-bit Windows.
=> glslang: Restrict to 64-bit

bucket/mtn.json
It works only on 64-bit Windows.
=> mtn: Restrict to 64-bit

bucket/ktx-software.json
It works only on 64-bit Windows.
=> ktx-software: Restrict to 64-bit

bucket/unison.json
It works only on 64-bit Windows.
=> unison: Restrict to 64-bit

bucket/latexindent.json
Signed-off-by: qidi1 <1083369179@qq.com>
Closes https://github.com/ScoopInstaller/Scoop/issues/5315
=> latexindent@3.20:Fix Can't shim 'latexindent.exe': File doesn't exist

bucket/flyctl.json
Some updates for flyctl:
- add arm64 architecture;
- add autoupdate hash extraction.
=> flyctl: Add arm64 architecture

bucket/flyway.json
=> flyway: use Maven metadata for checkver

bucket/marksman.json
Adds manifest for marksman, a language server for Markdown documents.
Closes #4286
=> marksman: Add version 2022-12-28

bucket/nano.json
Fix nano download URL and file hash
=> Update download URL and file hash for nano

bucket/istioctl.json
This PR adds [istioctl](https://istio.io/latest/docs/reference/commands/istioctl/) to the main bucket.
PR https://github.com/ScoopInstaller/Extras/pull/10233 removes `istio` from the extras bucket in favour of this.
=> istioctl: Add version 1.16.1

bucket/fission-cli.json
Adds manifest for fission-cli
Closes #4346
=> fission-cli: Add version 1.17.0

bucket/rust-gnu.json, bucket/rust-msvc.json, bucket/rust.json, bucket/rustup-gnu.json, bucket/rustup-msvc.json, bucket/rustup.json
Changes rust and rustup packages to use MSVC toolchain by default, as this is generally the better supported (and default) choice.
In the rustup package, the MSVC version is always used (the GCC build of rustup provides no benefits, and the MSVC version can be used to install GCC toolchains). The --default-host flag has been removed, so new installs will use the rustup default (MSVC) but existing installs will have a configuration file indicating GCC is the default; a note was added to the rustup packages stating how to change this.
The rust-gnu package was added, to allow using the GCC toolchain without rustup, and a note was added to all rust packages indicating that rustup can be used to more easily manage multiple toolchains (and is the primary install method; see …
=> rust, rustup: Use MSVC by default

bucket/perl.json
This commit changes the URLs for perl to use https, instead of http.
Closes #4379
=> [update]: Upgrade Perl links to HTTPS

bucket/winget-ps.json
PowerShell Module that comes with the latest release of Winget.
=> winget-ps: Add version 1.4.10173

bucket/git-filter-repo.json
As suggested by @goigle in #3471 the simplest way seems to let the app point directly to the git-filter-repo file instead of the symbolic link. This fixes the issue on my windows machine
Closes #3471
=> (fix) fix git symlink related error #3471

bucket/less.json
From the [latest release](https://github.com/jftuga/less-Windows/releases):
> **Note:** Standalone binaries will no longer be provided for the next release. Make sure to point your links to the provided zip files.
Additional 32-bit and arm64 binaries have also been provided.
=> less: Use zip binaries, Add `32bit` and `arm64` arch

bucket/hyperfine.json
hyperfine is now dual-licensed with MIT
=> hyperfine: Update license

.github/workflows/ci.yml, bucket/nano.json
The current source points to GNU nano v7.1-12, but the current one is 7.2-6.  This new source fixes the issue and also meets the recommended template.
- added specific installation for 32 and 64 bits removing the other package.
- Improved autoupdate regex to avoid missing new releases.
- Improved configuration, enabling the default nano features that were not activated.
=> nano: Update to 7.2-9-10164, add UTF-8 support, mouse support, etc.

bucket/keptn-cli.json
Adds keptn-cli support at version 1.1.0
Closes #4411
=> keptn: adds at v1.1.0

bucket/uutils-coreutils.json
- [v0.0.14][]: The `dir` and `vdir` utilities where added as aliases for `ls` and `ls -l`, respectively.
- [v0.0.17][]: `uname` is now available for all supported platforms, instead of Unix-like platforms only.
[v0.0.17]: https://github.com/uutils/coreutils/releases/tag/0.0.17
[v0.0.14]: https://github.com/uutils/coreutils/releases/tag/0.0.14
Closes: #4414
Relates-to: #3482
[^auto-update]: It can't update shim list automatically either. However I think it's OK, as it won't change frequently.
=> uutils-coreutils@0.0.17: Add shims for dir, uname, vdir

bucket/adb.json
`systrace` is removed since 33.0.1. From https://developer.android.com/studio/releases/platform-tools:
> This package used to contain `systrace`, but that has been obsoleted in favor of Studio Profiler, gpuinspector.dev, or Perfetto.
=> adb: Update description

bucket/rdiff-backup.json
- `architecture`: 64-bit version since [v2.2.0](https://github.com/rdiff-backup/rdiff-backup/releases/tag/v2.2.0). Installing a wrong version can make [ssh undiscoverable](https://github.com/rdiff-backup/rdiff-backup/blob/386732002e8956329421fb6f7c55a3222092e87a/docs/Windows-README.adoc#using-microsofts-openssh-client-on-windows-10).
- `extract_dir`: There's a 64/32 tail now. (e.g. `rdiff-backup-$version` → `rdiff-backup-$version-64`)
- `notes`: Add Windows doc.
Closes #4423
=> rdiff-backup@2.2.2: release format changed

bucket/chkcpu.json
Add version v2.15 and change download links to correct ones because it looks like urls have changed after looking on chkcpu website download links listed on chkcpu website: [http://web.inter.nl.net/hcc/J.Steunebrink/chkcpu.htm](http://web.inter.nl.net/hcc/J.Steunebrink/chkcpu.htm)
Closes #4437
=> chkcpu: Update chkcpu to version v2.15

bucket/cloud-sql-proxy.json
Google has changed the URLs for the executables resulting in scoop not being able to grab the latest files.
=> cloud-sql-proxy@2.0.0: autoupdate urls changed

bucket/ruff.json
Add [ruff](https://github.com/charliermarsh/ruff)
> Ruff is extremely actively developed and used in major open-source projects like:
> * [pandas](https://github.com/pandas-dev/pandas)
> * [FastAPI](https://github.com/tiangolo/fastapi)
> * [Transformers (Hugging Face)](https://github.com/huggingface/transformers)
> * [Apache Airflow](https://github.com/apache/airflow)
> * [SciPy](https://github.com/scipy/scipy)
>
> ...and many more.
=> ruff: Add version 0.0.251

bucket/highs.json
Compared to previous versions, the unpacking error is still reported, but it does not affect the smooth completion of the installation, which is the same behaviour as manually (even if the user unpacks manually, the error is still reported)
Closes #3936 
Related #3972
=> highs: Add version 1.4.2+0

bucket/chafa.json
License is `LGPL-3.0-or-later` as stated in the [readme](https://github.com/hpjansson/chafa/blob/master/README):
> Both library and frontend tools are covered by the Lesser GPL license, version 3 or later (LGPLv3+).
- [x I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> chafa: Update license

bucket/dart-sass-embedded.json
Updating dart-sass-embedded from v1.57.1 to 1.58.3
=> dart-sass-embedded: Update v1.57.1 => 1.58.3

bucket/railway.json
This updates the manifest since a new version of the Railway CLI was released and it uses new executable names.
=> railway@v3.0.5: update manifest to new binary names

bucket/nano.json
Nano:
- added ARM version
- added hashes file
- separate download per architecture
- package has migrated from 7z to zip
=> Nano: updated package from 7z to zip, separate download per arch, +ARM version, + hashes file

bucket/kafka.json
Fixed autoupdate to use downloads subdomain.
=> kafka: Update to version 3.4.0

bucket/datree.json
Add datree into scoop as given in this [issue](https://github.com/datreeio/datree/issues/799)
=> datree: add version 1.8.37

bucket/staticcheck.json
Fixed checkver as the release tag format went back to normal.
=> staticcheck: Update to version 2023.1.2

bucket/sqldef.json
Drop auto-update for 32bit system
=> sqldef: Update to version 0.15.15

bucket/gnupg.json, bucket/gpg.json
Adds an alias for `gpg2` in the `gpg` and `gnupg` apps by copying the binary `gpg.exe` into `gpg2.exe` in the install script.
`"Copy-Item \"$dir\\bin\\gpg.exe\" \"$dir\\bin\\gpg2.exe\""`
Closes #4548
=> (chore): add gpg2 alias for gpg and gnupg

bucket/xxcopy.json
`xxcopy.com` appears to be a dead domain, so I switched all links to the Internet Archive. (I'm unsure if I should be adding it to https://github.com/ScoopInstaller/Binary instead)
=> xxcopy: Use archived links

bucket/resvg.json
Removed usvg from autoupdate as it's no longer provided in releases:
https://github.com/RazrFalcon/resvg/blob/master/CHANGELOG.md#0280---2022-12-03
>Removed
>  - usvg CLI binary. No alternatives for now.
=> resvg: Update to version 0.29.0

bucket/typst.json
Adds typst, a markup-based typesetter that was open-sourced on March 21, 2023.  
See https://typst.app
=> typst: Add version 22-03-21-2

bucket/gnuplot.json
Gnuplot 5.4.6 released some bugfix version with "-2" appended to 7z file name. There is no good way to construct the filename for the "autoupdate" feature, so I left it as-is. The filename will most likely go back to its original naming scheme with the next release.
Closes #4586
=> gnuplot: One-time URL update for v5.4.6

bucket/syncthing.json
Syncthing's notes links to their docs website instead of their GitHub template, which is parsed incorrectly.
Closes #4607
=> syncthing@1.23.2: Link to actual docs

bucket/gsudo.json
gsudo v2.0.6 has arm64 binaries and the artifact was renamed, so this fix is needed.
=> gsudo: Fix for artifact renamed on v2.0.6, added arm64.

bucket/edgedriver.json
I noticed checkver was getting the latest canary version instead of stable.
Also added the ARM64 variant and fixed the license link.
=> edgedriver: Use stable version

bucket/redis.json
The current source of unofficial binaries has not had a release in over a year, so I have changed the source to one that has.
https://github.com/zkteco-home/redis-windows - binaries are uploaded to git instead of releases; build process not open
https://github.com/redis-windows/redis-windows - automated build process; less popular
Used the first source for now since it appears to be more popular.
Closes #4092
=> redis: Update to version 7.0.9

bucket/zstd.json
The internal directory organization of the .zip file has changed since v1.5.5.
- Closes #4630.
- Closes #4631.
=> zstd: Specify `extract_dir`

bucket/xxcopy.json
Avoids the use of the internet archive for the binary url.
Relates to https://github.com/ScoopInstaller/Binary/pull/18
=> xxcopy: Use ScoopInstaller/Binary

bucket/git-crypt.json
Change git-crypt's repository to its original, update version to 0.7.0
Closes #4655
=> git-crypt@0.7.0: Change repository to its original, update version to 0.7.0

bucket/static-web-server.json
`static-web-server` package links and descriptions have been changed since the latest `v2.14.0`.
So this PR just keeps the manifest content aligned.
=> static-web-server@2.15.0: update package links and description

bucket/qemu.json
32-bit builds were dropped which broke autoupdate: https://qemu.weilnetz.de/
>2023-04-07: New QEMU installers (8.0.0-rc0). Build only 64 bit installer.
Closes #4649
=> qemu: Update to version 8.0.0-rc2

bucket/dotnet-sdk.json
The excavator seems to be reading both the sts and lts versions as one value which breaks autoupdating (though it works fine locally). Added in regex just to get the first value in the set.
Relates to https://github.com/ScoopInstaller/Main/actions/runs/4715223507/jobs/8362070792#step:3:398
=> dotnet-sdk: Fix checkver

bucket/adb.json
Relates to https://repology.org/repository/scoop/problems
Homepage link https://developer.android.com/studio/releases/platform-tools.html is [dead](https://repology.org/link/https://developer.android.com/studio/releases/platform-tools.html) (HTTP 404) for more than a month and should be replaced by alive link (see other packages for hints, or link to [archive.org](https://archive.org/) as a last resort).
=> adb: Fix homepage

bucket/nodejs.json
From the latest release: https://github.com/nodejs/node/releases/tag/v20.0.0
>Official support for ARM64 Windows
>
>Node.js now includes binaries for ARM64 Windows, allowing for native execution on the platform.
>The MSI, zip/7z packages, and executable are available from the Node.js download site along with all other platforms.
>The CI system was updated and all changes are now fully tested on ARM64 Windows, to prevent regressions and ensure compatibility.
=> nodejs: Add arm64 architecture

bucket/certigo.json
Closes https://github.com/ScoopInstaller/Extras/pull/10916
=> certigo: add version 1.16.0

bucket/p4.json
Apparently this binary was updated upstream (both x86 and x64 changed):
```
Checking hash of p4.exe ... ERROR Hash check failed!
App:         main/p4
URL:         https://cdist2.perforce.com/perforce/r22.1/bin.ntx64/p4.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:   46c32ed0d3041f7478d05f4d7504014dd3a5b27a16989f8ea46d585c2d49d4f5
Actual:      ea3bad48619489f71a451e8bab2e028177dbae3d3f22d2fc16ffd82fee1760cf
```
=> p4: Update to version 2022.2-2407422 (64bit) | 2022.1-2409226 (32bit)

bucket/ktx-software.json
Fixed autoupdate and added arm64 variant from the latest update:
https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.1.0
=> ktx-software: Update to version 4.1.0

bucket/cmake.json
Binaries were added in version 3.24:
https://cmake.org/cmake/help/latest/release/3.24.html#other-changes
=> cmake: Add arm64 architecture

bucket/elvish.json
It seems that SHA256 checksums of Elvish binary archives have officially changed. See:
- 64-bit: https://dl.elv.sh/windows-amd64/elvish-v0.19.2.zip.sha256sum
- 32-bit: https://dl.elv.sh/windows-386/elvish-v0.19.2.zip.sha256sum
We should update them in the app manifest.
=> elvish: Fix hash

bucket/avr-gcc.json
Just adding the included avrdude.exe and make.exe to shims list.
these executables are already distributed with the package.
this saves the hassle of having to shim them manually or install them separately.
=> avr-gcc: add internal avrdude.exe and make.exe to shims list

bucket/erdtree.json
As of version `2.0.0` erdtree now uses bin name `erd` instead of `et`. See [here](https://github.com/solidiquis/erdtree/blob/v2.0.0/Cargo.toml#L22).
=> erdtree: Add version 2.0.0

bucket/alist.json
=> alist@3.16.1: Add arm64 architecture

bucket/mdcat.json
I renamed my Github account a while ago, this change updates the URLs accordingly.
Also note that the `autoupdate.hash.url` field is not correct anymore; I no longer have SHA512 hashes in the release pipeline but only b2 under `B2SUMS.txt`.  Haven't updated that field though, because I don't understand what it's for, and whether b2 hashes are okay there.
=> Fix upstream URL for mdcat

bucket/devspace.json
Provide a new app manifest for [DevSpace](https://devspace.sh)
Relates to https://github.com/devspace-sh/devspace/issues/2629
=> DevSpace: Add version 6.3.2

bucket/red.json
red: couldn't match 'Red\s+([\d.]+)\s+for' in http://static.red-lang.org/download.html
=> red: Update to version 30apr23 and fix autoupdate

bucket/win32yank.json
win32yank: 0.1.1 (scoop version is 0.0.4) autoupdate available
Autoupdating win32yank
Downloading win32yank-x86.zip to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 5229-byte response of content type application/json
VERBOSE: Content encoding: utf-8
Downloading https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x86.zip (356.0 KB)...
Computed hash: 820274883786affd19ec180392e3a32c1acfbe5dbf9daff2f90fad78d56aab86
ERROR You cannot call a method on a null-valued expression.
=> win32yank: Update to version 0.1.1

bucket/ijhttp.json
The bin shim points to `%SCOOP_INSTALLATION_PATH%/apps/ijhttp/current/ijhttp.bat`, but the dist file is unzipped in `%SCOOP_INSTALLATION_PATH%/apps/ijhttp/current/ijhttp`. So `ijhttp.bat` could not be found.
This PR fixes the problem.
Relates to #4724
=> ijhttp: Fix extract directory

bucket/clipboard.json
Can't shim 'clipboard.exe': File doesn't exist.
=> clipboard: Fix bin

bucket/unison.json
unison: 2.53.3 (scoop version is 2.53.0) autoupdate available
Autoupdating unison
Downloading unison-v2.53.3 ocaml-4.12.1 x86_64.windows.zip to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 5240-byte response of content type application/json
VERBOSE: Content encoding: utf-8
The remote server returned an error: (404) Not Found.
URL https://github.com/bcpierce00/unison/releases/download/v2.53.3/unison-v2.53.3+ocaml-4.12.1+x86_64.windows.zip is not valid
ERROR Could not update unison, hash for unison-v2.53.3+ocaml-4.12.1+x86_64.windows.zip failed!
=> unison: Update to version 2.53.3 and fix autoupdate

bucket/openssl-mingw.json
https://github.com/curl/curl-for-win/issues/33
Because upstream [no longer](https://github.com/curl/curl-for-win/commit/893b5f5c806f0cb2f2914ffbb8cde312b87e30af) ship a full OpenSSL distro, only static libs and headers.
=> openssl-mingw: Remove autoupdate

bucket/kubescape.json
- `kubescape` has got moved into `kubescape` org.
- `kubescape-windows-latest` is getting deprecated: https://github.com/kubescape/kubescape/issues/1168
=> kubescape: Update url and binary naming

bucket/gpac.json
gpac: couldn't match 'gpac-([\w.-]+)-(?<commit>\w+)-master-x64\.exe' in https://gpac.wp.imt.fr/downloads/
=> gpac: Update to version 2.2.1-rev0 and fix autoupdate

bucket/hexed.json
hexed: 1.1 (scoop version is 1.0.32) autoupdate available
Autoupdating hexed
Downloading hexed.exe to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 5096-byte response of content type application/json
VERBOSE: Content encoding: utf-8
The remote server returned an error: (404) Not Found.
URL https://github.com/samizzo/hexed/releases/download/1.1/hexed.exe is not valid
ERROR Could not update hexed, hash for hexed.exe failed!
=> hexed: Update to version 1.1 and fix autoupdate

bucket/bazel-buildtools.json
bazel-buildtools: 6.1.2 (scoop version is 6.1.1) autoupdate available
Autoupdating bazel-buildtools
Downloading buildifier-windows-amd64.exe to compute hashes!
VERBOSE: GET with 0-byte payload
VERBOSE: received 6403-byte response of content type application/json
VERBOSE: Content encoding: utf-8
The remote server returned an error: (404) Not Found.
URL https://github.com/bazelbuild/buildtools/releases/download/6.1.2/buildifier-windows-amd64.exe#/buildifier.exe is not valid
ERROR Could not update bazel-buildtools, hash for buildifier-windows-amd64.exe failed!
https://github.com/bazelbuild/buildtools/releases/tag/v6.1.2 Version tag on GitHub now start with v, e.g. v6.1.2 for the current release.
=> bazel-buildtools: Update to version 6.1.2 and fix autoupdate

bucket/zig.json
Hashes are no longer shown on the download page.
=> zig: Fix hash extraction

bucket/gosec.json
=> gosec@2.16.0: Add arm64 architecture

bucket/doctl.json
=> doctl@1.96.0: Add arm64 architecture

bucket/vhs.json
Updates VHS to v0.5.0.
On v0.5, the archive names changed, so autoupdate is not working. This PR fixes the autoupdate URLs as well.
Relates to https://github.com/charmbracelet/vhs/issues/309
=> vhs: Update to version 0.5.0

bucket/7zip.json
=> 7zip: Revert to version 22.01 and Fix checkver

bucket/zvm.json
Adds zvm (Zig Version Manager): https://github.com/tristanisham/zvm
Notably I generated this manifest with ChatGPT 4. I find creating manifests a bit tedious, but reviewing and testing them is really simple. 
I gave ChatGPT the github repo address and the URLs of the release files and it happily generated a valid manifest. I asked it to generate the previous version with blank hashes so that I could use the autoupdate script. Worked perfectly 👌 All I had to update was the project description.
=> zvm: add version 0.2.2

bucket/dfu-util.json
- Keep files such as help(man), license, etc. as well
Closes #4865
=> dfu-util: Fix installation for powershell 5.x

bucket/tektoncd-cli.json
=> tektoncd-cli@0.31.1: Add arm64 architecture

bucket/eksctl.json
=> eksctl@0.146.0: Add arm64 architecture

bucket/7zip.json
This upgrades 7-zip to latest stable version 23.01.
It also changes the auto-update url back to the https://www.7-zip.org/ website using a regex that should exclude beta versions. Another reason is that the current stable version 23.01 has not been published (yet?) on https://sourceforge.net/projects/sevenzip/files/7-Zip/
When there are multiple versions,  download links appear like this on the website:
```
Download 7-Zip 22.01 (2022-07-15) for Windows:
Download 7-Zip 23.00 (beta) (2023-05-07) for Windows:
Download 7-Zip 19.00 (2019-02-21) for Windows:
Download 7-Zip 21.03 beta (2021-07-20) for Windows:
Download 7-Zip 21.02 alpha (2021-05-06) for Windows:
Download 7-Zip 21.00 alpha for Windows ARM64:
```
The updated regex will only match the stable versions 19.00 and 22.01.
For examples …
=> upgrade 7-zip to 23.01

bucket/kaf.json
=> kaf@0.2.6: Add arm64 architecture

bucket/dvc.json
The scoop autoupdate looks at an outdated link.
Some sleuthing brought me to https://github.com/iterative/dvc-exe/blob/main/upload.py and that confirms that the AWS S3 bucket https link is used in future as well, see the Windows specific download link on homepage
=> dvc: update to 3.4 and new download URL

bucket/helix.json
I added the "--config" parameter to the Helix shims to point to a config file that can be stored in the persis directory.
Closes #4948
=> helix: Scooping config file path

bucket/updatecli.json
>updatecli when added as a shim does not execute.
Fixes #4992
```
psh ❯ scoop install updatecli
Installing 'updatecli' (0.55.0) [64bit] from main bucket
Loading updatecli_Windows_x86_64.zip from cache.
Checking hash of updatecli_Windows_x86_64.zip ... ok.
Extracting updatecli_Windows_x86_64.zip ... done.
Linking ~\scoop\apps\updatecli\current => ~\scoop\apps\updatecli\0.55.0
Creating shim for 'updatecli'.
Creating shim for 'upd8cli'.
psh ❯ .\updatecli.exe
... At this point a elevated command prompt windows opens, if you click yes, then updatecli runs in another window; if you click no then...
ResourceUnavailable: Program 'updatecli.exe' failed to run: An error occurred trying to start process 'C:\Users\Lewin.Chan\scoop\shims\updatecli.exe' with working directory …
```
=> updatecli: add to path, remove shim

bucket/chromedriver.json
Closes #4981
Relates to https://github.com/ScoopInstaller/Versions/pull/1313
=> chromedriver: Update to version 115.0.5790.102

bucket/gibo.json
v3.0 was a re-write in Go, hence we now need `gibo.exe` instead of `gibo.bat` on Windows. The version tag now also has a `v` prefix (e.g. `v3.0.5` compared with `2.2.8`).
Disclaimer: I don't have access to a Windows PC, so haven't been able to test this.
Closes #XXXX
=> gibo: Update to version 3.0.5

bucket/powershell-beautifier.json
This PR adds the PowerShell-Beautifier module, a whitespace reformatter and code cleaner for Windows PowerShell and PowerShell Core that is compatible with all OSes.
This change was previously raised in ScoopInstaller/Extras#11652, but is being raised into Main as suggested by @HUMORCE.
=> powershell-beautifier: Add version 1.2.5

bucket/go-feature-flag.json
Adding GO Feature Flag inside the scoop extra bucket.
fixes https://github.com/thomaspoignant/go-feature-flag/issues/817
=> go-feature-flag: Add version 1.14.1

bucket/python.json
Revert accidental commit afb001c8f526ffd0d77fb430937f82924c582d98 changing the PATH entry for Scripts to an inorrect directory, causing pip.exe, among others, to not be found anymore.
Closes #5025
=> python@3.11.4: revert accidental change of env_add_path

bucket/jenkins-lts.json, bucket/jenkins.json
Jenkins does no longer support Java 8, therefore I replaced the suggestion with Java 17, because Jenkins operates on Java 11 and 17 nowadays.
=> (chore): Update Jenkins Java recommendations for Java 17

bucket/powershell-yaml.json
This PR adds the powershell-yaml module, a PowerShell module for serializing and deserializing YAML.
For more on this module, check out the repo [cloudbase/powershell-yaml](https://github.com/cloudbase/powershell-yaml).
=> powershell-yaml: Add version 0.4.7

bucket/ko.json
This pull requests adds Ko, a software to easily create multi-arch container images for Go binary files. Ko is a CNCF sandbox project and is a great tool for DevOps and developers.
Closes #5031
=> Ko: Add version 0.14.1

bucket/circleci-cli.json
=> circleci-cli: Add arm64 version

bucket/rdiff-backup.json
This PR removes the `(possibly outdated)` in notes, which was added in #4424. The maintainer has refreshed the documentation in https://github.com/rdiff-backup/rdiff-backup/pull/879, so it's no longer obsolete.
Relates to https://github.com/rdiff-backup/rdiff-backup/pull/879
=> (chore): Windows README for rdiff-backup is no longer obsolete

bucket/jq.json
The jq repository has been moved to https://github.com/jqlang/jq.
Also, jq maintainers changed the executable name rule to support various CPU architectures.
Previously something like `jq-win32.exe` and `jq-win64.exe` but now `jq-windows-i386.exe` and `jq-windows-amd64.exe`.
They temporarily added the executable with old names to fix for the latest URLs (https://github.com/jqlang/jq/issues/2877).
But they might not retain the executable with the old names in the next release.
=> jq: Download from new jqlang organization and new executable names

bucket/bbdown.json
`bbdown` 's `BBDown.data` file stores BiliBili login Cookies which is created in `bbdown login`, and should be kept as persist.
=> (chore): `BBDown.data` (login data) should be kept as persist

bucket/mask.json
Closes #5097
Dependent on https://github.com/jacobdeichert/mask/pull/103 to be merged for SHA checksums
=> Add `mask`

bucket/cppcryptfsctl.json
Adding this to Main since it is recommended by gocryptfs
=> cppcryptfsctl: Add version 1.4.4.1

bucket/helm-docs.json
This PR updates the manifest for [helm-docs](https://github.com/norwoodj/helm-docs) to fix a breaking change to the artifact naming and update the package to the latest version `v1.11.2`.
=> helm-docs: Fixed binary name change for v1.11.2

bucket/monero-cli.json
Fixes:
```pwsh
Installing 'monero-cli' (0.18.2.2) [64bit] from main bucket
Loading monero-win-x64-v0.18.2.2.zip from cache.
Checking hash of monero-win-x64-v0.18.2.2.zip ... ok.
Extracting monero-win-x64-v0.18.2.2.zip ... DEBUG[1695345424] $stdoutTask.Result = -------------------------------------------------------------------------------
ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------
Started : Thursday, September 21, 2023 9:17:04 PM
Source : ~\scoop\apps\monero-cli\0.18.2.2\monero-x86_64-w64-mingw32\
Dest : ~\scoop\apps\monero-cli\0.18.2.2\
Files : *.*
Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30
------------------------------------------------------------------------------
2023/09/21 …
```
=> monero-cli: Fix `extract_dir` and `autoupdate`

bucket/erlang.json
Change checkver to erlang downloads page as it always lists the latest version as first regex match
Closes #5119
=> erlang: Fix checkver to get latest version

bucket/swift.json
Fix the pre_install script because the msi file and the path to be expanded have changed.
Closes #5133 
=> swift@5.9: Fix pre_install

bucket/resticprofile.json
Provide a manifest for resticprofile 0.23.0
Closes #5125
=> Initial manifest for resticprofile

bucket/pdf2svg.json
A simple PDF to SVG converter using the Poppler and Cairo libraries. This is a basic library required for many apps, like Inkscape TexText (latex plugin) and the latextools python library.
Closes #XXXX
=> add pdf2svg

bucket/numbat.json
History and Config are both stored in Appdata/Roaming/numbat (elaborated [here](https://docs.rs/dirs/latest/src/dirs/lib.rs.html#122-124), methods data_dir() and config_dir() both resolve to `Appdata/Roaming/` on windows), so no persist is required.
Closes #5151
=> numbat: Add version 1.6.3

bucket/mods.json
The manifest is now architecture independent because since `mods` v1.0.0 there's no `32bit` architecture binary preventing the Excavator from auto-updating it.
=> mods: Adjust manifest to new release scheme

bucket/lab.json
=> lab@0.25.1: Add arm64 version

bucket/llvm.json
Some projects ask for these env vars to be set
=> llvm: Add `env_set.LIBCLANG_PATH` & `env_set.LLVM_LIB_DIR`

bucket/hurl.json
- Fix `autoupdate` url since release artifact name changed.
- Update to version 4.1.0.
Relates to Orange-OpenSource/hurl#1951.
=> hurl: Fix autoupdate, update to version 4.1.0

bucket/terraform.json
This PR aims to resolve the license discrepancy for Terraform to properly annotate its Business Software License 1.1 status.
https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license
It may even be worth reviewing Homebrew's stance on this, given they have frozen at `1.5.7` due to the implications of this license change:  https://github.com/Homebrew/homebrew-core/pull/139538
Closes #5182
=> fix(5182): Update Terraform license to BUSL-1.1

bucket/helm-docs.json
This PR updates the manifest for [helm-docs](https://github.com/norwoodj/helm-docs) to fix a breaking change to the artifact naming and update the package to the latest version `v1.11.3`.
=> helm-docs: Fixed binary name change for v1.11.3

bucket/nu.json
=> nu@0.86.0: Use the full binary for nushell

bucket/perl.json
Update Strawberry Perl to version 5.38.0.1. I have modified `autoupdate` so that it picks up the new releases distributed via GitHub.
Note that there is no 32bit version at the moment. I am not sure if there will be one in the future (see https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/96)
=> perl@5.38.0.1: update (drops 32bit, new autoupdate)

bucket/wstunnel.json
- Fix `autoupdate` url since release artifact name changed.
- Add checksums file.
- Update to version 7.2.0.
=> wstunnel: Fix autoupdate, update to version 7.2.0

bucket/arc.json, bucket/aws.json, bucket/azure-ps.json, bucket/bbdown.json, bucket/coq.json, bucket/detekt.json, bucket/dust.json, bucket/flux.json, bucket/git.json, bucket/grails.json, bucket/grpcurl.json, bucket/hashlink.json, bucket/haskell.json, bucket/ipinfo-cli.json, bucket/kim.json, bucket/kotlin-native.json, bucket/libavif.json, bucket/mingit-busybox.json, bucket/mingit.json, bucket/neovim.json, bucket/openshift-okd-client.json, bucket/pdf2djvu.json, bucket/pester.json, bucket/pnpm.json, bucket/sapling.json, bucket/simplex-chat.json, bucket/terraform-provider-ibm.json, bucket/upbound-cli.json, bucket/v.json, bucket/wkhtmltopdf.json
Repo names are subject to change, IDs aren't
Relates to https://github.com/ScoopInstaller/Extras/pull/12093 https://github.com/ScoopInstaller/Versions/pull/1429
=> chore (GitHub API): Use repo ID, instead of repo name

bucket/influxdb.json
URL was changed, and `extract_dir` was removed.
=> influxdb@2.7.3: Fix URL

bucket/yazi.json
fixes extract_dir, bin, autoupdate
=> yazi: update to 0.1.5

bucket/binaryen.json
Binaryen added a new `wasm-merge` tool recently ([docs](https://github.com/WebAssembly/binaryen#wasm-merge)). Scoop installs it correctly already but no shim is made to make it available in the PATH. This fixes that.
I read in CONTRIBUTING that you dislike PRs without issues, but the issue here is so mundane that I hope it's okay.
ps. I struggled to get through the issue reporting mechanism. This is neither a bug in Scoop, nor a "package request" because the package already exists, so I wasn't even sure which kind of issue to make. So I picked "bug" cause it was the least wrong, but started strongly doubting that I did it right when it asked for my powershell configuration and whatnot.
=> binaryen@116: add shim for `wasm-merge`

bucket/optipng.json
Now OptiPNG provides 64-bit version.
=> OptiPNG@0.7.8: Add 64-bit

bucket/pdfbox.json
Add support for the latest major version of Apache PDFBox, v3.0.0.
=> pdfbox@3.0.0: New major version

bucket/listmonk.json
- Update `checkver` to use github releases.
=> listmonk@2.5.1: Add arm64 version

bucket/dcmtk.json
Adds DCMTK 3.6.7 for 32bit and 64bit.
Closes #5283
=> DCMTK: Add version 3.6.7

bucket/qsv.json
Add [qsv](https://github.com/jqnatividad/qsv) - a command line CSV data-wrangling toolkit.
Closes #5284.
=> qsv: Add version 0.119.0

bucket/vale.json
Replace https://docs.errata.ai/vale/about (now NXDOMAIN) to https://vale.sh .
Relates-to: https://github.com/errata-ai/vale/commit/a2c38e0c20698b8b0ce36bfd6968f936496b84cc
Resolves #5302
=> vale@2.29.7: Update homepage

bucket/static-web-server.json
**Static Web Server** officially provides ARM64 binaries on the latest `v2.24.0`, so this PR just adds support for it.
=> static-web-server: Add ARM64 support

bucket/frp.json
Drop 32bit support and migrate to `toml` config
Starting from version 0.52.0, frp no longer releases builds for the 386 platform, and the default configuration file format has been changed to TOML instead of INI.
Closes #5238
=> frp@0.52.3: Drop 32bit support and migrate to `toml` config

bucket/ascii-image-converter.json
=> ascii-image-converter@1.13.1: Add arm64 version

bucket/quarkus-cli.json
My current quarkus-cli is still at quarkus-cli 3.2.4 event after updating using `scoop update *`
This PR provides an intermediary fix to #5229 where we update quarkus-cli to the latest LTS (3.2.9 at this time).
Relates to #5229
=> Update quarkus-cli.json to 3.2.9.Final

bucket/ptags.json
Latest upstream release changed the location of ptags.exe requiring a new `extract_dir` directive in the app manifist
Closes #XXXX
=> ptags: Add extract_dir to fix installation

bucket/rga.json
- Add list of dependencies.
- Add `rga-preproc` to binaries list.
- Update `checkver` to filter alpha-versions.
Closes #5310.
=> rga@0.9.6: Add runtime dependencies

bucket/go-swagger.json
- Add `hash` section for autoupdate.
=> go-swagger@0.30.5: Add arm64 version

bucket/vcpkg.json
Adds `VCPKG_ROOT` as an environment variable pointing to the current installed `vcpkg`.
Closes #5189 
I'd just like to say, that it could be an idea to set even more of the environment variables, because otherwise this is very tedious to use, but let's start with one.
=> vcpkg: Add root directory as env variable

bucket/openssl.json
slpro no longer handles /lib for you, `pre_install` required
I had a discussion with the maintainer, and they mentioned they no longer wanted to handle this
Quote from email exchanges:
> Starting with 3.2.0, a new build/package/deploy system is being used 
because I was starting to go insane due to the regular barrage of 
upstream releases.  The new system will be used going forward for ALL 
releases - including the next 3.0.x and 3.1.x.  As part of this change, 
the 'lib' directory structure was completely redone.
Added `OPENSSL_ROOT_DIR`, now works with cmake OOTB
=> openssl: Fix environment variables

bucket/k9s.json
- Update link to checksums file.
- Add hash regex to filter out `.sbom` files.
=> k9s@0.29.1: Fix hash check

bucket/protolint.json
- Fix autoupdate.
- Update to version 0.46.3.
=> protolint: Update to version 0.46.3

bucket/kubeshark.json
- Fix autoupdate.
- Update to version 51.0.39.
=> kubeshark: Update to version 51.0.39

bucket/kustomize.json
Closes https://github.com/ScoopInstaller/Main/issues/5345
This bug has been present since [Kustomize 5.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.2.0), which was the first version with .zip (see also https://github.com/kubernetes-sigs/kustomize/issues/5116).
=> fix: kustomize has changed to .zip from .tar.gz

bucket/kubectl.json
=> kubectl@1.29.0: update homepage, hashes, arm64, and exposing kubectl-convert.exe

bucket/jaq.json
Add [jaq](https://github.com/01mf02/jaq) - a jq clone focused on correctness, speed, and simplicity.
Closes #5307.
=> jaq: Add version 1.2

bucket/k9s.json
Scoop persist folder is used to persist k9s config and logs.
Closes #5388
=> k9s: Persist config and logs

bucket/zookeeper.json
- Update urls for binary/checkver/autoupdate since path for artifacts download changed.
From Excavator logs:
> zookeeper: couldn't match 'zookeeper-([\d.]+)/' in https://www.apache.org/dist/zookeeper/
=> zookeeper@3.9.1: Fix checkver

bucket/arduino-cli.json
- Fix autoupdate, add hash section.
- Update to version 0.35.0.
=> arduino-cli: Update to version 0.35.0, fix autoupdate

bucket/hledger.json
The 1.32.2 release of `hledger` features a new Windows binary named `hledger-ui.exe`.  Unfortunately, the initial release .zip file did not include this binary. A new .zip was uploaded but the release version was not updated. So the download hash has changed.
This PR adds the `hledger-ui.exe` shim, and updates the hash for the updated .zip file.
=> hledger: 1.32.2 added a new binary hledger-ui.exe

bucket/go-sqlcmd.json
This PR will add the sqlcmd standalone implementation. sqlcmd is the standard Microsoft command line experience for Microsoft SQL Server and Azure SQL
Closes #5367
- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> go-sqlcmd: Add version 1.5.0

bucket/opentofu.json
This PR adds support for [OpenTofu](https://opentofu.org/) which has just reached [GA status](https://opentofu.org/blog/opentofu-is-going-ga). _OpenTofu_ is an OSS fork of _Terraform_.
=> opentofu: Add version 1.6.0

bucket/hashcat.json
The potfile contains hashes and passwords that should be persisted.
=> hashcat@6.2.6: Persist potfile

bucket/windows-application-driver.json
Two fixes to streamline the use of Windows Application Driver aka WinAppDriver aka WAD:
- move supporting dlls from System folder next to WinAppDriver.exe: otherwise the supporting dlls are not in path and WAD fails to run
- set APPIUM_WAD_PATH environment variable with custom WAD location: appium-windows-driver can use WAD as installed by the installer, but needs to be informed of the location of the scoop installed version
These two fixes allow to transparently replace WAD installed by the installer with WAD installed by scoop.
=> Windows application driver fix

bucket/kubecolor.json
=> kubecolor: Add version 0.2.1

bucket/gnutls.json
Adding manifest for GnuTLS library and tools.
-----
I've tested locally the install, update, forced update and uninstall.
I've also tested manifest autoupdate with `chekver`.
=> gnutls: Add version 3.8.2

bucket/openfga.json
Adds manifest to support OpenFGA cli. 
Supports 32bit, 64bit, arm64. 
Closes #5330
=> openfga: Add version 0.2.3

bucket/ssh3.json
Currently on Windows, it's only a client
=> ssh3: Add version 0.1.5-rc5

bucket/sqlpage.json
Closes #5240 
See SQLPage [website](https://sql.ophir.dev/) and [repo](https://github.com/lovasoa/SQLpage).
=> sqlpage: Add version 0.17.1

bucket/wakatime-cli.json
- Add arm64 version
- Add hash link to autoupdate.
=> wakatime-cli: Add arm64 version

bucket/unrar.json
For people who need `unrar.exe` desperately: `scoop bucket add extras; scoop install extras/winrar`
---
- Update to version 7.00 (**7.00 beta 3**).
- Fix `autoupdate` link since no [unrarw32.exe](https://www.rarlab.com/rar/unrarw32.exe) is available but only [unrarw64.exe](https://www.rarlab.com/rar/unrarw64.exe) instead.
- Change `checkver` regex to track the latest/newest available version (including beta) since the only downloadable binary for unrar - [unrarw64.exe](https://www.rarlab.com/rar/unrarw64.exe) - reports its version as **7.00 beta 3** (i.e. latest at the moment) but not **6.24** (i.e. previous stable). Looks like there is no possibility to define what version has the downloadable binary: link is always the same - https://www.rarlab.com/rar/unrarw64.exe - and doesn't content …
=> unrar: Update to version 7.00, fix autoupdate link

bucket/git-town.json
Starting at v11, the assets in Git Town releases have new names.
Closes #5437
=> Update to the new asset names in Git Town v11

bucket/chafa.json
This fixes a crash in the MS Windows build.
See https://github.com/hpjansson/chafa/issues/182.
=> chafa: Update to 1.14.0-2 build

bucket/rustic.json
Not sure, why the hash didn't get updated, did it now manually, but the address, that should be called is available with that hash. 🤔
Fixes https://github.com/ScoopInstaller/Main/issues/5495
=> rustic: (chore) Remove pre_install

bucket/boxes.json
It looks like the binary downloads were updated but the release number kept the same resulting in an incorrect hash for the new binaries.
gh: https://github.com/ascii-boxes/boxes/
Closes #5487
=> boxes: update incorrect hash

bucket/cargo-binstall.json
=> cargo-binstall: Add version 1.6.0

bucket/bat.json
As stated in bat README.md (https://github.com/sharkdp/bat?tab=readme-ov-file#prerequisites), Visual C++ Redistributable must be installed.
I noticed that when I installed bat on fresh Windows: bat fails to run without it.
=> bat: suggest installing vcredist2022

bucket/supabase.json
=> supabase@1.145.4: Add arm64 version

bucket/roswell.json
Update to 23.10.14.114 and attempt to fix autoupdate by specifying "latest" github link and less potentially ambiguous hash regex.
=> roswell@23.10.14.114: fix autoupdate

bucket/radius.json
This change adds the [radius](https://github.com/radius-project/radius) CLI tool to the bucket.
Closes #5474
As pointed out in the issue, there is another instance of this manifest for comparison [here](https://github.com/hoilc/scoop-lemon/blob/master/bucket/radius.json). I learned some tips to simplify the manifest from that instance.
=> radius: Add version 0.31.0

bucket/gsudo.json
---
* Switch to the portable `.zip` version.
* Add license `url`
* Update field order to match the latest contribution guidelines
=> gsudo@2.4.4: Update download type & field order

bucket/gifsicle.json
=> gifsicle: Fix `extract_dir`

bucket/cpufetch.json
- Update to version 1.05.
- Fix autoupdate (windows binary naming still changeable from release to release).
Relates to #4496, #4795.
=> cpufetch: Update to version 1.05

bucket/tectonic.json
From Excavator logs:
```
tectonic: couldn't match 'releases/tag/tectonic%40([\d.]+)' in https://github.com/tectonic-typesetting/tectonic/releases
```
=> tectonic: Update checkver

bucket/libjpeg-turbo.json
As from libjpeg-turbo [official page](https://libjpeg-turbo.org/) / [sourceforge ](https://sourceforge.net/projects/libjpeg-turbo/files/repodata/) / [mailing list](https://groups.google.com/g/libjpeg-turbo-announce/c/bAYKnuX1HHk/m/f65q1kgZAgAJ):
> 2023-11-29: Official Releases Moved to GitHub and packagecloud
> Existing releases (3.0.1 and earlier) will remain available on
> SourceForge and in the old (SourceForge-hosted) YUM repository, but new
> releases from this point on will be uploaded only to GitHub and packagecloud.
- Update to version 3.0.2.
- Switch to github releases.
- Update homepage.
=> libjpeg-turbo: Update to version 3.0.2, switch to github releases

bucket/git-machete.json
Adding manifest for [git-machete](https://github.com/VirtusLab/git-machete), as suggested by one of the users (CC @ppasieka).
This project has ~800 stars but only ~40 forks &mdash; does it qualify for Main bucket?
Note that it's in an equivalent of main bucket in multiple package managers, including Homebrew... see [the full list of known packages](https://github.com/VirtusLab/git-machete/blob/master/PACKAGES.md).
JSON mostly taken from [Extras -> cruft](https://github.com/ScoopInstaller/Extras/blob/master/bucket/cruft.json).
Checked that installation & autoupdate works on a CI Windows VM: [build log](https://app.circleci.com/pipelines/github/VirtusLab/git-machete/4723/workflows/f907da7b-f7b3-4dc1-9a56-899f99230cdc/jobs/28783).
=> git-machete: Add version 3.23.2

bucket/mtn.json
```
mtn: 3.4.2 -> 3.5.0
Updating one outdated app:
Updating 'mtn' (3.4.2 -> 3.5.0)
Downloading new version
Downloading https://bitbucket.org/wahibre/mtn/downloads/mtn-3.5.0-win64.zip (42.2 MB)...
Checking hash of mtn-3.5.0-win64.zip ... ok.
Uninstalling 'mtn' (3.4.2)
Removing shim 'mtn.shim'.
Removing shim 'mtn.exe'.
Unlinking D:\Scoop\apps\mtn\current
Installing 'mtn' (3.5.0) [64bit] from main bucket
Loading mtn-3.5.0-win64.zip from cache
Extracting mtn-3.5.0-win64.zip ... done.
Linking D:\Scoop\apps\mtn\current => D:\Scoop\apps\mtn\3.5.0
Creating shim for 'mtn'.
Can't shim 'bin\mtn.exe': File doesn't exist.
```
New `bin` path to exe in ZIP is `mtn.exe`.
=> mtn: Fix bin path for v3.5.0

bucket/gig.json
This PR adds `gig`, a command-line application to generate `.gitignore` files using the [_toptal/gitignore_](/toptal/gitignore) repository of `.gitignore` templates.
For more on this module, check out the repo [_shihanng/gig_](/shihanng/gig).
=> gig: Add version 0.8.3

bucket/exercism.json
Previous autoupdate URLs no longer work for [exercism CLI v3.3.0](https://github.com/exercism/cli/releases). Tested locally, installs as expected.
=> exercism: Fix URLs for v3.3.0

bucket/winget-ps.json
https://github.com/microsoft/winget-cli/issues/3183 has been resolved, which means the module now works properly on Powershell 5.1.
=> winget-ps: Remove `pwsh` dependency

bucket/bflat.json
[bflat](https://github.com/bflattened/bflat) is a C# compiler that can produce [Native AOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/) binaries without the need of the [.NET](https://dotnet.microsoft.com) SDK.
=> bflat: Add version 8.0.2

bucket/capnp.json
Adds Cap'n protocol to main bucket
Create manifest, with the autoupdate, of the [Cap'n Proto](https://capnproto.org/).
=> Add capnp.json manifest to Main bucket

bucket/sbt.json
From excavator logs:
```
sbt: couldn't match '/sbt-([\d.]+)\.zip' in https://www.scala-sbt.org/download.html`
```
=> sbt@1.9.8: Fix checkver url

bucket/gig.json
#5569 was merged last week, but I have since discovered that [`fzf`](/ScoopInstaller/Main/tree/master/bucket/fzf.json) should have been listed under the `depends` section of this manifest. Updating the manifest accordingly.
For more on this module, check out the repo [_shihanng/gig_](/shihanng/gig).
=> gig: Update manifest with "fzf" as dependency.

bucket/croc.json
- Update to version 9.6.9.
- Fix autoupdate urls.
- Remove arm64 option (since not available in the recent releases).
=> croc: Update to version 9.6.11, fix autoupdate

bucket/git-cliff.json
This is a trivial PR. git-cliff now has a dedicated homepage, and it should be preferred over the repo.
Relates-to: #4161
=> git-cliff@2.1.2: Update homepage

bucket/swift.json
Fix the pre_install script because the msi file and the path to be expanded have changed.
Closes #5581
=> swift@5.10: Fix pre_install

bucket/mods.json
Fixes broken `mods` manifest for `1.2.2`. See https://github.com/charmbracelet/mods/discussions/238#discussion-6403901
=> FIX: adjusted `mods` manifest to the new ZIP structure

bucket/redis.json
The Redis windows package changed URLs and suddenly stopped working. This commit adds a new updated manifest that installs the msys2 version of redis-windows.
Closes #5634
Closes #5633
=> redis@7.2.4: fix download+autoupdate URL

bucket/bun-baseline.json, bucket/bun.json
Closes https://github.com/ScoopInstaller/Main/issues/5092
=> bun(-baseline): Add version 1.1.0

bucket/nodejs-lts.json, bucket/nodejs.json
Due to the [redesign](https://nodejs.org/en/blog/announcements/diving-into-the-nodejs-website-redesign) of the Node.js website, the checkver of the nodejs-lts package is broken, this pull request fixes it, and also adds the arm64 version
=> nodejs-lts: fix checkver and add arm64 version

bucket/zstd.json
There may be a simpler method, but this fix extracts the zip within the zip and then moves its contents to `$dir`. Tested locally.
Closes #5658
=> zstd: Add 32-bit architecture

bucket/mozjpeg.json
Mozjpeg builds by Gary Zhang ( https://github.com/garyzyg/mozjpeg-windows ) has been stuck on v4.1.1 in Scoop, but v4.1.5 is available.
I found a change to "checkver" that made "checkver.ps1" return correct new version.
Fixes issue: #5681
=> Fix mozjpeg auto update

bucket/imagemagick-lean.json
Currently errors on install, fails to shim bins (bins were removed). Sorry for the duplicate PR, I forgot that renaming branches doesn't sync.
=> imagemagick-lean: Fix bins

bucket/cht.json
cht was still on version `0.6` but is currently at `0.7.2` which fixes, for example https://github.com/tpanj/cht.exe/issues/7#issue-1458740110. This PR also adds auto-update to the cht manifest.
> I have not created a seperate issue for this, since it is not a new package or a bug with the manifest but just an update to the already available version.
=> cht@0.7.2: Update cht.exe to 0.7.2 and add auto update.

bucket/vim.json
Switch to the Vim Win32 Repository
Found the link for the same on https://www.vim.org/download.php
WinGet also uses the same 
https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/vim/vim/9.1.0211
The current Vim version is very old too
Closes #XXXX
- *[x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> vim: Update to version 9.1.0228

bucket/flamingo.json
**Prerequisites**
**Criteria**
**Name**
Flamingo
**Description**
Flamingo enhances [ArgoCD](https://github.com/argoproj/argo-cd) by providing [Flux](https://github.com/fluxcd/flux2) subsystem capabilities, enabling visualization and management of Flux workloads alongside ArgoCD while ensuring timely backporting of CVEs for a secure environment.
**Homepage**
https://github.com/flux-subsystem-argo/flamingo
**Download Link(s)**
https://github.com/flux-subsystem-argo/flamingo/releases/download/v0.10.2/flamingo_0.10.2_windows_amd64.zip
**Some Indication of Popularity/Repute**
GitHub stars: 560
GitHub forks: 39
=> flamingo: Add version 0.10.2

bucket/px.json
Initialize px.ini before persist directive to avoid creating a px.ini folder.
Configure PX_CONFIG environment variable to point to persist/px/px.ini.
Closes https://github.com/ScoopInstaller/Main/issues/5609
=> px: fix px.ini creation for persist directive

bucket/haskell.json
The GitHub ghc mirror seems outdated (newest release there is 9.4.1).
This PR will thus switch to [ghc from haskell.org](https://www.haskell.org/ghc/download.html) and also update the haskell package to 9.8.2.
=> haskell: use haskell.org instead of ghc github mirror and update to version 9.8.2

bucket/ab.json, bucket/apache.json
Update Apache version to 2.4.59 since 2.4.58 is gone.
Closes #5714
=> apache: Update to version 2.4.59

bucket/uutils-coreutils-lean.json
This is a trivial PR. It has a dedicated homepage now, which should be preferred over the repo.
Relates to #5742
Relates to https://github.com/uutils/coreutils/pull/2897
=> uutils-coreutils-lean@0.0.23: Update homepage

bucket/zls.json
zls.exe is no longer in bin/ directory so installation fails on shim creation as file is not found.
=> Fix exe location in zls.json for version 0.12.0

bucket/mysql-lts.json, bucket/mysql-shell.json, bucket/mysql.json
> Removed the deprecated mysqlpump utility along with its associated lz4_decompress and zlib_decompress helper utilities.
ref: https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html
- Closes #5777
- Relates to not tested update #5775
=> Update mysql.json - fixes #5777

bucket/yt-dlp.json
According to [document](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installing-plugins), there is another path for loading plugins.
=> yt-dlp: add plugins directory

bucket/go.json
```
Updating 'go' (1.22.2 -> 1.22.3)
Downloading new version
Starting download with aria2 ...
Download: 05/07 20:49:22 [WARN] --file-allocation=falloc will use SetFileValidData() API, and aria2 uses uninitialized disk space which may contain confidential data as the download file space. If it is undesirable, --file-allocation=preallocDownload: ). File will be allocated by filling zero, which blocks whole aria2 execution. Run aria2 as an administrator orDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 07f2c6|OK  |    19MiB/s|~/scoop/cache/go#1.22.3#da5209a.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of go1.22.3.windows-amd64.zip ... ok. …
```
=> go: Fix (un)install warnings

bucket/gdrive.json
Updates gdrive CLI from v2 to v3
v2 repo: https://github.com/prasmussen/gdrive
v3 repo: https://github.com/glotlabs/gdrive
Technically speaking it's a major change and a new manifest should be used. However gdrive2 isn't really functional anymore and doesn't seem to be breaking changes if updated directly from v2 to v3. 
**Major change:** x64 version only, no more 32-bit version
Closes #5764
=> gdrive: Update to version 3.9.1

bucket/neovim.json
Remove nvim-qt.exe from nvim-win64.zip from json as it has been removed.
https://github.com/neovim/neovim/pull/23668
Closes #5835
=> neovim: Remove nvim-qt

bucket/tesseract.json
```
❯ ls (scoop prefix tesseract)
Directory: ~\scoop\apps\tesseract\current
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---        2024-05-03  12:06 PM       50790128   dl.7z_
```
=> tesseract: Fix extraction

bucket/gradle-bin.json, bucket/gradle.json, bucket/python.json, bucket/tesseract.json
```
WARN  "env" will be deprecated. Please change your code/manifest to use "Set-EnvVar"
```
=> chore: Replace deprecated `env` function with `(Set|Get)-EnvVar`

bucket/gnuplot.json
This pull request can fix [[Bug]: The gnuplot in the main bucket has not been updated to 6.0.0.](https://github.com/ScoopInstaller/Main/issues/5403)
Relates to #5403
=> Update gnuplot to 6.0.0

bucket/go-size-analyzer.json
go-size-analyzer is a tool for analyzing the dependencies in compiled Golang binaries, providing insight into their impact on the final build.
See https://github.com/Zxilly/go-size-analyzer for details.
=> go-size-analyzer: Add version 1.1.0

bucket/charm-gum.json
Newer version (updated in https://github.com/ScoopInstaller/Main/commit/340b2b61bfff7942c1038005d036af037830c89f today) of charm-gum has a directory in its archive.
Fixes #5781
=> charm-gum@0.14.1: Fix `extract_dir`

bucket/rustup.json
rustup@1.27.1: Add arm64 binary
According to rust-lang/rustup#3406, there is an available arm64 build for rustup.
=> rustup@1.27.1: Add arm64 binary

bucket/dafny.json
dafny has removed DafnyLanguageServer.exe since 4.4.0, currently installing dafny will fail with the message:
```
Installing 'dafny' (4.6.0) [64bit] from 'main' bucket
Loading dafny-4.6.0-x64-windows-2019.zip from cache.
Checking hash of dafny-4.6.0-x64-windows-2019.zip ... ok.
Extracting dafny-4.6.0-x64-windows-2019.zip ... done.
Linking ~\scoop\apps\dafny\current => ~\scoop\apps\dafny\4.6.0
Creating shim for 'Dafny'.
Creating shim for 'DafnyLanguageServer'.
Get-Command: C:\Users\(user)\scoop\apps\scoop\current\lib\install.ps1:783
Line |
783 |              $bin = (Get-Command $target).Source
|                      ~~~~~~~~~~~~~~~~~~~
| The term 'DafnyLanguageServer.exe' is not recognized as a name of a cmdlet, function, script file, or executable
| program. Check the spelling of the …
```
=> dafny: Remove `DafnyLanguageServer` bin

bucket/mutagen.json
=> mutagen: Add arm64 build and autoupdate.hash

bucket/mutagen-compose.json
This adds the mutagen-compose CLI. Mutagen CLI already exists, so I used the same app manifest config.
https://github.com/mutagen-io/mutagen-compose
https://mutagen.io/documentation/orchestration/compose
=> mutagen-compose: Add v0.17.6

bucket/azure-cli.json
Switch Azure CLI to use ZIP instead of MSI.
Seems ZIP has been available since 2024-01-30, ref <https://github.com/Azure/azure-cli/pull/27911>.
Benefits:
* Should be faster to install and should create shorter paths which might help with #5300.
* Less complex to extract a ZIP vs. MSI.
~~Cons:~~ Edit: No cons as I see it.
* Only x64 is available as ZIP, not x86.
* Related feature request: <https://github.com/Azure/azure-cli/issues/29104>
* Edit: Not a problem, Azure CLI authors recommends against using x86.
* Download is much slower because Azure CLI ZIP is not available through a CDN, but an Azure Storage Account in US West only.
* Related feature request: <https://github.com/Azure/azure-cli/issues/28856>
* Edit: Not a con because ScoopInstaller/Main points to the same Azure Storage …
=> azure-cli: Use zip archive

bucket/doggo.json
They changed the URLs and dropped the arm64 build.
=> doggo: Update to version 1.0.4

bucket/doggo.json
the bin path depends on the zip file name
=> doggo: Fix bin path

bucket/fzf.json
Tag name have changed from 9.9.9 to v9.9.9 in version 0.54.0.
Closes #6012
Closes #6013
=> fzf: Update to version 0.54.0

bucket/atmos.json
Terraform Orchestration Tool for DevOps. Keep environment configuration DRY with hierarchical imports of configurations, inheritance, and WAY more. Native support for Terraform and Helmfile.
https://atmos.tools/
=> atmos: Add version 1.84.0

bucket/scala.json
The repository for Scala 3 has been transfered to the [`scala`](https://github.com/scala/) organisation under the [`scala3`](https://github.com/scala/scala3) name.
=> scala: Update repo link

bucket/exiftool.json
Closes #XXXX
Updates the manifest to version 12.89, which is the latest version,
but I don't know how to verify the file with sha1...
so I changed the hashing method to sha256 which I copy from the "extras/office-tool-plus" manifest...
=> exiftool: Update to version 12.89

bucket/terraform-switcher.json
terraform-switcher changed their packaging format from .zip to .tar.gz at some point in the past, which appears to have broken scoop autoupdate. The latest release is 1.2.2 but scoop still shows 0.13.1308. This PR should fix the autoupdate behavior.
Relates to #3910
=> terraform-switcher: Fix autoupdate urls

bucket/nu.json
The dataframe feature was removed on 0.94.0. To reinstate this feature, use the polars plugin
See https://github.com/nushell/nushell/commit/905e3d0715ad82fbf837e059ad7cd5184ea77f89
See https://www.nushell.sh/book/plugins.html for information on how to install plugins
Closes #5894
Closes #5875
=> nu@0.95.0: Fix removed dataframe feature

bucket/shadowsocks-rust.json
Release includes 6 binaries but only 4 of them are linked, this PR adds missing `ssservice.exe` and `sswinservice.exe` to `bin`.
=> shadowsocks-rust: Add missing bins

bucket/lua.json
The original sourceforge project is no longer building the latest binaries. I've updated the manifest to download the latest binary from msys2 and added auto-update for future versions. Package has been tested locally and works.
Relates to #3511
=> lua: Update to version 5.4.7-2

bucket/vapoursynth.json
Changes expected file extensions from .7z (used until VapourSynth R65) to .zip (R66-RC1 and later)
~~This does not update the package itself. I'll let the bot do that.~~
Closes #5863
---
```
 ScoopInstaller.Main  .\bin\checkver.ps1 vapoursynth
vapoursynth: 68 (scoop version is 65) autoupdate available
```
```
 ScoopInstaller.Main  .\bin\checkver.ps1 vapoursynth -u
vapoursynth: 68 (scoop version is 65) autoupdate available
Autoupdating vapoursynth
Downloading VapourSynth64-Portable-R68.zip to compute hashes!
VapourSynth64-Portable-R68.zip (8.5 MB) [=====================================================================================================] 100%
Computed hash: 911d22e6c52886b043194bc17f232f4e054f9e76259c72b66dfc679e7409304b
Downloading VapourSynth64-Portable-R68.zip to compute …
```
=> vapoursynth: Update to version 69

bucket/oauth2c.json
oauth2c: Add version 1.13.0
https://github.com/cloudentity/oauth2c
=> oauth2c: Add version 1.15.0

bucket/git-with-openssh.json
As per the release notes for https://github.com/git-for-windows/git/releases/tag/v2.46.0.windows.1:
> The server-side component of OpenSSH, which had been shipped with Git for Windows for historical reasons only, is [now no longer distributed with it](https://github.com/git-for-windows/build-extra/pull/571).
I have confirmed locally that I can update from 2.45.2.windows.1 when removing the shim for `sshd.exe`.
=> git-with-openssh@2.46.0.windows.1: Remove sshd.exe

bucket/osv-scanner.json
OSV-Scanner changed the binary naming to remove the version number from the binary name in the GitHub release. This updates the autoupdate rules to also follow that. I also updated it manually to the latest version 1.8.3.
Closes #5580
=> (chore): update osv-scanner.json to fit new binary naming scheme

bucket/tenv.json
This PR adds [tenv](https://github.com/tofuutils/tenv); a versatile version manager for [OpenTofu](https://opentofu.org/), [Terraform](https://www.terraform.io/), [Terragrunt](https://terragrunt.gruntwork.io/) and [Atmos](https://atmos.tools/), written in Go.
=> tenv: Add version 3.1.0

bucket/git-bug.json
git-bug: change upstream source to git-bug/git-bug
git-bug has moved into [the git-bug organization][0]. This change
updates the package to fetch directly from git-bug/git-bug instead of
relying on what is now a 301 redirection (that lives only at GitHub's
discretion).
[0]: https://github.com/git-bug/git-bug
Closes: ScoopInstaller/Main#6134
Closes: git-bug/git-bug#1255
=> git-bug: change upstream source to git-bug/git-bug

bucket/lynx.json
Current URL 404s
Updates to latest working URL from https://slproweb.com which is v3.3.2:
https://slproweb.com/download/Win32OpenSSL_Light-3_3_2.exe
=> Fix OpenSSL Light URL

bucket/naiveproxy.json
naiveproxy: add win-arm64 support
=> naiveproxy@v128.0.6613.40-1: add win-arm64 support

bucket/glow.json
Glow hasn't been updated in a while because their release format changed.
This PR makes it work again
(reopened because I reorganized my branches)
=> glow@2.0.0: Update checkver to new release format

bucket/stlink.json
Closes #6164
Looks like they only provide 32bit binaries now, so removed the architecture section.
Added multiple shims for the various utilities, instead of modifying env PATH as before.
=> stlink: fix manifest for v1.8.0

bucket/kubeadm.json, bucket/kubectl.json, bucket/kubelet.json
=> kube(adm|ctl|let): Migrate to `dl.k8s.io`

bucket/postgrest.json
Downloads DLLs postgrest.exe is linked against making postgrest work out of the box
Closes #5959 (see screenshot below)
=> postgrest: install required DLLs

bucket/git-cliff.json
=> git-cliff@2.6.1: Add arm64 version

bucket/nodejs.json
Relates to https://github.com/ScoopInstaller/Versions/pull/1997
Closes #6257
- [Removing support for Windows 32-bit systems](https://github.com/nodejs/node/releases/tag/v23.0.0)
=> nodejs: Deprecate 32bit & Update to version 23.0.0

bucket/glab.json
- Fix `autoupdate` in accordance with the changed binaries naming.
- Update to the latest version.
Closes #6240
=> glab: Update to version 1.48.0, fix autoupdate

bucket/lychee.json
- Update to the latest version.
- Fix `checkver` & `autoupdate` in accordance with the new release naming.
=> lychee: Update to version 0.16.1, fix checkver & autoupdate

bucket/sqldef.json
* Upstream dropped support for i386 with v0.14.0 ; See https://github.com/sqldef/sqldef/blob/master/CHANGELOG.md#v0140
* Distributing v0.13.23 for x86 when the manifest claims v0.17.20 is bad UX and wrong
* `scoop info` currently fails to parse the manifest with the error: `data did not match any variant of untagged enum TOrArrayOfTs at line 30 column 9`
=> sqldef: Remove obsolete 32bit architecture

bucket/mingw-winlibs.json
It makes sense to use UCRT instead of MSVCRT in 2024, as suggested on the home page:
> MSVCRT or UCRT runtime library?
> 
> Traditionally the MinGW-w64 compiler used MSVCRT as runtime library, which is available on all versions of Windows.
> 
> Since Windows 10 Universal C Runtime (UCRT) is available as an alternative to MSVCRT.
> Universal C Runtime can also be installed on earlier versions of Windows (see: [Update for Universal C Runtime in Windows](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c)).
> 
> Unless you are targetting older versions of Windows, UCRT as runtime library is the better choice, as it was written to better support recent Windows versions as well as provide better standards conformance (see …
=> mingw-winlibs: Use UCRT instead of MSVCRT

bucket/git-town.json
=> git-town@16.4.1: Add arm64 version & hash autoupdate

bucket/mariadb.json
=> mariadb@11.5.2: Fix download url & autoupdate

bucket/innounp.json
Original version [Innounp](http://sourceforge.net/projects/innounp) (can be used up to InnoSetup 6.1)
Updated Unicode version [Innounp-1](https://github.com/jrathlev/InnoUnpacker-Windows-GUI/blob/master/innounp-1) (can be used up to InnoSetup 6.3)
Innounp-1 supports Inno Setup versions 2.0.7 to 6.3.1
In my opinion, the new version should be used by default, and the old version should be placed in the versions repository.
To fix install/decompress errors for inno installers, use this until PR merge:
```
scoop bucket add versions
scoop install versions/innounp-unicode
```
fix ScoopInstaller/Extras#14242, fix ScoopInstaller/Extras#14235, fix ScoopInstaller/Extras#14126, fix ScoopInstaller/Extras#14255, fix ScoopInstaller/Extras#14256, fix ScoopInstaller/Extras#14120, fix …
=> innounp@0.50: switch to maintained fork and update to v1.75

bucket/juliaup.json
Julia installer and version multiplexer. 
Closes #6209
=> juliaup: Add version 1.17.4

bucket/hjson.json
- Update to the latest version.
- Bring back `checkver` (removed for some reason in 4ed2a9f).
- Update homepage (fixes #6282).
=> hjson: Update to version 4.4.0, add checkver & arm64, fix homepage

bucket/openssh.json
=> openssh: Update to version 9.8.0.0p1

bucket/spicetify-cli.json
=> spicetify-cli@2.38.4: Update URLs to organization repo

bucket/bom.json
The PR adds support for the _Kubernetes SIGs_ [`bom`](https://kubernetes-sigs.github.io/bom/) tool.
=> bom: Add version 0.6.0

bucket/podman.json
The change in `filePath.EvalSymlinks()` behavior in Go 1.23 has resulted in Podman versions after 5.3.0 being unable to locate `win-sshagent.exe`. Temporary fix refer to https://github.com/containers/podman/issues/24557#issuecomment-2490996716.
- Closes #6327
=> podman: Fix 'winsymlink' error

bucket/lazydocker.json
=> lazydocker@0.24.1: Add arm64 version

bucket/portainer.json
Update to last portainer version blocked by changed github pattern.
=> portainer: update to 2.21.4

bucket/prqlc.json
Fixes the autoupdate URL since "v" was removed from the version string.
=> prqlc: Fix autoupdate and update to version 0.13.2

bucket/kotlin.json
This file is not present in the bin folder
- Fix #6344
- Close #6350
=> Remove kotlin-dce-js.bat from Kotlin 2.1.0

bucket/fastfetch.json
Newer version of fastfetch no longer provides 32bit binaries.
Closes #6372
=> fastfetch: drop 32bit support

bucket/lua-language-server.json
retrieve lua-language-server releases under the organization LuaLS instead of sumneko
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)
=> lua-language-server@3.13.3: releases are now stored under the organization LuaLS instead of sumneko

bucket/deno.json
Adds autoupdate hash URL so Scoop does not have to download the artifact to calculate checksum.
=> deno@2.1.2: Add autoupdate hash url

bucket/xcaddy.json
Add [xcaddy](https://github.com/caddyserver/xcaddy).
Command line tool and associated Go package makes it easy to make custom builds of the Caddy Web Server.
=> xcaddy@0.4.4: Add xcaddy

bucket/pomsky.json
Pomsky is a portable, modern regular expression language, see more info at [here](https://pomsky-lang.org/).
And pomsky is dual-licensed under the [MIT license](https://opensource.org/licenses/MIT) or the [Apache 2.0 license](https://opensource.org/licenses/Apache-2.0).
This is a clean pr with commit history pruned, and closed #6227 as mentioned.
=> pomsky@0.11: Add manifest

bucket/dotnet-sdk.json
Microsoft urges users of the domains "dotnetcli.azureedge.net" and "dotnetbuilds.azureedge.net" to replace them with "builds.dotnet.microsoft.com", because Edgio (CDN) is bankrupt and Microsoft says these domains are likely to stop functioning.
* 2024-12-24: <https://github.com/dotnet/core/issues/9671>
* 2024-12-26: <https://devblogs.microsoft.com/dotnet/critical-dotnet-install-links-are-changing/>
* 2024-12-30: <https://www.bleepingcomputer.com/news/microsoft/microsoft-issues-urgent-dev-warning-to-update-net-installer-link/>
=> dotnet-sdk@9.0.101: Replaced domains because Edgio (CDN) is bankrupt

bucket/osslsigncode.json
=> osslsigncode: Update to version 2.9, drop 32bit support

bucket/qpdf.json
Change download URL to GitHub, as it's more robust.
=> qpdf: Use GitHub as download URLs

bucket/crystal.json
Adds the crystal language package manager `shards.exe` to the system path, closes #6447.
=> crystal: add package manager `shards.exe` to the system path

bucket/mise.json
Included manifest changes suggested by @chawyehsu in PR comment which sets the internal mise configurable env var MISE_DATA_DIR to a directory that scoop persists
Relates to #6374
- removed install/uninstall scripts
- set env var `MISE_DATA_DIR` to a directory inside scoop and persist it
- add the directory mise places its own shims to the Path env var
- set env var `MISE_GLOBAL_CONFIG_FILE` to file inside app install dir and persist it
- added pre_install script to check mise config.toml exists or is created as a file
- added note about configuring specific shells with link to mise docs
=> mise: manifest updated to more portable config

bucket/minisign.json
=> minisign@0.12: add arm64 architecture

bucket/git.json
=> git@2.47.1.2: Add arm64 version

bucket/podman.json
Podman 5.4 includes a proper fix for #6327
and the workaround introduced in #6335 can
be reverted
=> podman: revert workaround needed for v5.3

bucket/jsign.json
Java implementation of Microsoft Authenticode for signing Windows executables, installers & scripts
=> jsign: Add version 7.0

bucket/lsix.json
Like "ls", but for images. Shows thumbnails in terminal using [sixel](https://en.wikipedia.org/wiki/Sixel) graphics.
=> lsix: Add version 1.9.1

bucket/git-filter-repo.json
Use `Expand-ZipArchive` instead of `Expand-7zArchive` to resolve #6451.
Closes #6451
Relates to #6519
=> git-filter-repo: Fix decompress error

bucket/nu.json
This PR adds:
* Shortcut "Nushell" that opens to `~`
* Similar to <https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json>.
* Logic for `scoop uninstall --purge` that remove leftovers.
Nushell maintainers did not oppose these changes:
* <https://github.com/nushell/nushell/issues/14787>
=> nu@0.101.0: Add 1) shortcut 2) uninstall `--purge` logic

bucket/nuclei.json, bucket/nucleis.json
Adding [Nuclei](https://github.com/projectdiscovery/nuclei)
=> Nucleis: Add version 3.3.1

bucket/jnv.json
Add a manifest for the `jnv` cli tool.
Closes #6183
=> jnv: Add version 0.4.0

bucket/mergiraf.json
Add [mergiraf](https://mergiraf.org/) 0.2.0: A syntax-aware git merge driver for a growing collection of programming languages and file formats.
=> mergiraf: Add version 0.2.0

bucket/jprq.json
This PR adds a new manifest for `jprq` version 2.4.
**Project URL:** [jprq GitHub Repository](https://github.com/azimjohn/jprq)  
**Supersedes:** [#6593](https://github.com/ScoopInstaller/Main/pull/6593) (old PR)
- Added a new manifest file for `jprq`.
- Ensured proper JSON formatting.
- Included proper binary shims.
- Supersedes the previous broken PR: [#6593](https://github.com/ScoopInstaller/Main/pull/6593).
=> Jprq.io support

bucket/gpth.json
Closes #6613
Two things:
- I am not 100% sure if this binary is for `x86_64`. Though, for sure, this is a Dart app and a quick search yields that it is impossible to compile for `x86` AOT in Dart... Please note that I may be very wrong due to the unfamiliarity with Dart.
- I am aware that this bucket is for developer tools only. Personally, I think that `gpth` lies in the gray zone between the developer and non-developer tools... Therefore, I would like to know whether the app fits here.
=> gpth: Add version 3.4.3

bucket/railway.json
=> railway@3.22.2: Add arm64 version

bucket/pueue.json
Updated the auto-update URL.
Closes #6621
=> pueue@4.0.0: fix autoupdate url

bucket/tealdeer.json
Homepage and documentation page has changed to https://tealdeer-rs.github.io/tealdeer/
- [ x ] Use conventional PR title: `<manifest-name[@version]|chore>: <general summary of the pull request>`
- [ x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)
=> tealdeer@1.7.2: fix homepage url

bucket/vivetool.json
=> vivetool@0.3.4: fix autoupdate url, update to 0.3.4

bucket/stylua.json
Relates to scoop being unable to find the latest versions of stylua due to a file name change introduced in [v2.0.0](https://github.com/JohnnyMorganz/StyLua/releases/tag/v2.0.0).
Fixes #6550.
=> stylua@v2.0.2: update to version 2.0.2, fix autoupdate

bucket/git-absorb.json
=> git-absorb@0.6.17: Bump

bucket/pulumi.json
Pulumi depends on additional exe files to perform certain tasks.  If these files are not in the PATH, pulumi is unable to find them and throws errors.
Closes #6511
=> pulumi@3.148.0: 🐛 Add pulumi exe files to bin

bucket/ast-grep.json
unfortunately this binary name change is due to another operating system
see https://ast-grep.github.io/guide/quick-start.html#installation
related to https://github.com/ast-grep/ast-grep/issues/56
related to https://github.com/ast-grep/ast-grep-vscode/issues/451
=> ast-grep@0.36.2: change binary name to ast-grep

bucket/rustup-gnu.json, bucket/rustup-msvc.json, bucket/rustup.json
The rust-lang.org /archive/ endpoint does not provide the *current* version, only previous versions. This prevented scoop from auto-updating until a new version was released (always one version behind).
This commit also adds arm64 architecture to the rustup-msvc and rustup-gnu manifests.
As rustup.json and rustup-msvc.json are identical, I suggest that they be consolidated into one.
That can be done on a different PR after discussion
Fixes: #6605
=> rustup@1.28.2: Fix update urls, add arm to rustup-{msvc,gnu}

bucket/sed.json
Upstream broke their tag naming scheme, and pushed a fixed build for x64 specifically.
Manually updated the download url for v4.9 only. Hashes of the x86 release did not change.
Also fixed an issue in checkver that would prevent future automatic updates (assuming upstream tags nicely).
Fixes #6643
=> sed@4.9: Fix x64 release URL

bucket/sops.json
Release naming format changed, now supporting amd64 and arm64 architecture. 
Fixes: #6701
=> sops@3.10.2: fix release url & add arm64

bucket/gallery-dl.json
Use the correct SPDX license identifier in the gallery-dl manifest
Closes #6711
=> gallery-dl: fix license

bucket/clink-completions.json
The path installed via `clink installscripts` was different for each
version of clink-completions, creating issues as the same script was
loaded multiple times (with different version).
This change makes the path consistent across versions, making sure only
the latest one is loaded.
Closes #6576
=> clink-completions@0.6.2: fix clink script path

bucket/rust-analyzer.json
Fix the `rust-analyzer` manifest to account for the change from `gz` to `zip` in the download url.
=> rust-analyzer@2025-03-24: Fix manifest

bucket/confluent-cli.json
Confluent changed the filename of the checksum txt file.
=> confluent-cli@4.16.0: fix checksum url

bucket/mergiraf.json
Thanks for packaging Mergiraf!
I noticed that the license is wrong (see https://codeberg.org/mergiraf/mergiraf/src/branch/main/LICENSE.txt), so here is a PR to fix that.
Follow up to #6312 by @nithinphilips.
=> mergiraf: Correct license

bucket/rustup-gnu.json, bucket/rustup-msvc.json, bucket/rustup.json
- Updated the rustup `checkver.url` to script link `https://sh.rustup.rs`.
- Modified the regex pattern to match rustup version from the installation script.
Relates to #6442
---
=> rustup: fix regex patterns `checkver` field

bucket/biome.json
Switches to using the github api feed for releases
Needs to match tags of the form: `cli/v1.9.4` but NOT `cli/v1.9.5-nightly.4713c52`. See: [regexr](https://regexr.com/8e71o)
There may be better regex to use, but matching on a literal `"` worked for me. 
Fixes Excavator checkver error [(log)](https://github.com/ScoopInstaller/Main/actions/runs/14580811575/job/40896917043#step:3:531)
=> biome: Fix checkver regex to avoid nightly tags

bucket/clipboard.json
Fixes failure to update to 0.10.0
Upstream has (~temporaily?~) dropped support for Windows Arm64 as of 0.9.1
Also updates the homepage url to project website.
Closes: #6514
=> clipboard: Remove unsupported ARM build

bucket/mise.json
Fixes #6477
- Removes `env_set` and `persist` properties from `mise.json` to allow mise to use its default locations for `config.toml` and `$MISE_DATA_DIR`
=> mise: use default config/data locations

bucket/mise.json
Relates to #6677 
- Since config and data dirs been reverted to default, `mise\shims` no longer exists and should be removed alongside
=> mise: remove unused PATH env

bucket/vulkan.json
Relates to scoop being unable to find the latest version of Vulkan due to a file name changed introduced in 1.4.313.0.
Fixes #6802
=> vulkan@1.4.313.0: update to version 1.4.313.0 and fix autoupdate

bucket/android-payload-dumper.json
Original manifest autoupdate not correctly configured.
This PR fix autoupdate, update to 1.3.0 and change to 64 bit only. (and format fix)
Closes #6810
=> android-payload-dumper@1.2.2: update to 1.3.0, fix autoupdate, change to 64bit only

bucket/azcopy.json
Closes #6821.
---
`azcopy` has caused many issues due to a) the download URL used up until this PR lags behind new GitHub releases, and b) the download URL has been static, leading to hash mismatch.
* <https://github.com/ScoopInstaller/Main/issues?q=is%3Aissue%20azcopy>
This is a more permanent fix.
---
=> azcopy@10.29.1: Add ARM64 + change download URL to GitHub releases

bucket/zig.json
=> zig: fix extract_dir

bucket/isx.json
Fix isx autoupdate wrong file name
=> isx: Update to version 0.3.10

bucket/1password-cli.json
relates to https://www.1password.community/discussions/developers/1password-cli-not-working/155988
=> 1password-cli: revert to 2.30.1 and disable autoupdate

bucket/jaq.json
Fix download links in manifest. 
Closes #6849
=> jaq@2.2.0: fix download link in manifest

bucket/1password-cli.json
Reverts changes made in #6841, op published a fix in version 2.31.1
see: https://www.1password.community/discussions/developers/1password-cli-not-working/155988
=> 1password-cli: revert pin at 2.30.1

bucket/uv.json
I recently [added](https://github.com/astral-sh/uv/pull/11786) a new "uvw.exe" binary to the uv repo. It is similar to what pythonw.exe does, which hides console window for uv. I believe it could be useful to add it for shim.
The binary is released since [uv 0.7.9](https://github.com/astral-sh/uv/releases/tag/0.7.9).
=> uv: Add the "uvw" binary for shim

bucket/biome.json
Update checkver and autoupdate URLs to match new Biome project version tagging format.
Closes #6916
=> biome@1.9.4: Update version tag format for v2+

bucket/vulkan.json
This PR addresses the following:
1. Fixes #6805 . The new Vulkan installer does not allow complete extraction of the install tree through 7zip. This changes the logic to instead calling the installer directly. See the note below.
2. Adds support for arm64 installers and removes 32-bit support. Vulkan deprecated 32-bit years ago, so the code is no longer relevant.
3. Adds a QoL improvement by linking `vkconfig-gui.exe` and `vulkanCapsViewer.exe` to the start menu so users can easily configure validation layers as well as check supported features on their GPUs.
There is a bug in the installer where attempting to run it with the `copy_only` flag still causes an uninstall entry to be added in the registry. The bug has been logged and can be found …
=> vulkan@1.4.313.0: update package manifest to correctly handle new installers

bucket/yt-dlp.json
=> yt-dlp@2025.06.09: switch to SHA256 for virustotal compatibility

bucket/ghdl.json
This PR adds [GHDL](https://github.com/ghdl/ghdl):
> VHDL analyzer, compiler, simulator and (experimental) synthesizer
GHDL is an open source command line tool to analyze and simulate [VHDL](https://en.wikipedia.org/wiki/VHDL).
It has 2.3k stars on GitHub and is likely the most widely known/used open source VHDL simulator.
As suggested by @jack-mil I have created this PR relating to the following issues/PRs:
Closes #5991 
and
Relates to https://github.com/ScoopInstaller/Extras/pull/13541
=> ghdl: add version v5.0.1

bucket/edgedriver.json
This PR fixes the broken URLs in the edgedriver manifest, which broke due to a DNS configuration change by Microsoft. It also updates the package to the latest available version, 138.0.3351.95.
For more, refer to <https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver>.
=> edgedriver: Fix url and update to 138.0.3351.95

bucket/espanso.json
Add `espanso.cmd` to bin for the CLI. For example, the [Espanso docs ask you to run `espanso path` to find your config files](https://espanso.org/docs/get-started/#configuration).
=> espanso: Add `espanso.cmd` to bin for CLI

bucket/go-feature-flag.json
Actual version of the GO Feature Flag scoop is not valid anymore because we have changed the release process for the binaries.
This new manifest is updated to be compatible with the actual process.
=> go-feature-flag: Fix and update to v1.45.5

bucket/flyway.json
maven.org is two minor versions behind.
Change URL to download.red-gate.com.
=> flyway@11.10.4: correct URL, update

bucket/balena-cli.json
Fixes 404 errors in CI Excavator.
Apparently they have completely changed the distribution format and contents. A standalone executable is no longer provided, instead a cmd/bash script uses a redistributable node executable to execute the JS/TS app. Upstream recommends the installer for Windows.
Seems like no one has noticed this for 2 months, maybe should be removed from scoop?
Relates to #773
=> balena-cli: Fix and update to version 22.1.4

bucket/tenv.json
Closes #7033
I thought ARM64 was missing, but it wasn't. So added x86 instead.
=> tenv@4.7.6: Add x86

bucket/dart.json
The manifest was failing to update because Dart removed ia32 (32-bit) packages from 3.8.0 onwards.
Relates to #7067.
=> dart@3.8.0: Remove 32bit installer sections

bucket/typstyle.json
This pr add support for [typstyle](https://github.com/typstyle-rs/typstyle), a beautiful and reliable [typst](https://typst.app) code formatter.
Relates to #6123, and it may also relate to #6746.
=> typstyle: Add version 0.13.17

bucket/gig.json
This PR makes the following changes:
- `(chore)`: Run formatjson.ps1 for all manifests.
Relates to:
- https://github.com/ScoopInstaller/GithubActions/pull/61
To avoid existing manifests with lint issues also modified and appear in the commit list when contributors format manifests, I am now submitting a PR to format them all.
=> (chore): Run formatjson.ps1 for all manifests
