ScoopInstaller/Main

bucket/aws-iam-authenticator.json
Extra quote is causing `checkver` to fail.
=> aws-iam-authenticator: Fix checkver

bucket/neovim-nightly.json
Add a new neovim-nightly.json to allow users to install the nightly
builds of neovim, instead of just the stable/release builds.
=> Neovim: Add nightly version.

bucket/innounp.json
Merge after https://github.com/ScoopInstaller/Binary/pull/7
https://github.com/lukesampson/scoop-extras/commit/7a8a8438515ebca830f96333b028f1ac7605b0bb should be reverted.
=> innounp: Update to 0.49

bucket/srvman.json
On https://sysprogs.com/legacy/
> The products listed on this page are not actively developed or maintained. We have published the source code for all the legacy products and are open to contributions from the community, however we ourselves do not maintain them anymore.
So remove `checkver`.
=> srvman: Fix extract_dir and remove checkver

bucket/git-annex.json
```
Checking hash of git-annex-installer.exe ... ERROR Hash check failed!
App:         main/git-annex
URL:         https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    863a77032182121c3a1933e8068388d7c4f4264f49b94907a0716f65ff7109ef
Actual:      22320f6e15c6dc5a9fd1a3407c2eab18b7993c3600ce5fa3a2e789dd61d665dc
```
https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe.info
```
GitAnnexDistribution {distributionUrl = "https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe", distributionKey = Key {keyName = "22320f6e15c6dc5a9fd1a3407c2eab18b7993c3600ce5fa3a2e789dd61d665dc.exe", keyVariety = SHA2Key (HashSize 256) (HasExt True), keySize = Just 15074004, …
```
=> git-annex 7.20190507: fix hash

bucket/neovim.json
neovim's release 0.3.5 is refreshed at 2019-05-25T20:29:02Z, and hashes change again...
Close #86
=> neovim: Fix hash

bucket/msys2.json
Close https://github.com/lukesampson/scoop/issues/2884
For `MSYS2_ROOT`, I haven't found ref for this env path, and for the newest `msys2_shell.cmd`, any other envs is not needed.
For original `env_add_path`, all binaries in root path are ported (`autorebase.bat` is only needed by 32bit msys2), and remove adding root to env.
=> msys2: Add shortcuts and persist, fix bins and path

bucket/git-interactive-rebase-tool.json
No 32bit binaries have been provided in the `1.0-RC` or `1.0.x` releases. Dropping support in favor of bumping to the stable `1.0.0` release.
https://github.com/MitMaro/git-interactive-rebase-tool/releases
=> git-interactive-rebase-tool: Update to version 1.0.0

bucket/git-tfs.json
Version deviates from standard naming convention (missing patch version):
https://github.com/git-tfs/git-tfs/releases
Manual update in anticipation of future releases returning to consistent pattern.
=> git-tfs: Update to version 0.30

bucket/racket.json
```
ERROR Download failed! (Error 3) Resource was not found
ERROR https://www.cs.utah.edu/plt/installers/7.3/racket-7.3-x86_64-win32.exe#/dl.7z
referer=https://www.cs.utah.edu/plt/installers/7.3/racket-7.3-x86_64-win32.exe#/
dir=C:\Users\foo\scoop\cache
out=racket#7.3#https_www.cs.utah.edu_plt_installers_7.3_racket-7.3-x86_64-win32.exe_dl.7z
ERROR & 'C:\Users\foo\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\foo\scoop\cache\racket.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=16 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https …
```
=> Racket: use official url instead of mirror's

bucket/redpen.json
I added RedPen, which was a proofreading tool for writers or programmers.
According to [the comment](https://github.com/lukesampson/scoop-extras/pull/2159#issuecomment-493436103) by @Ash258 in https://github.com/lukesampson/scoop-extras/pull/2159, I sent this PR to this main bucket.
=> RedPen: Add version 1.10.1

bucket/caddy.json
Upgrade caddy to v1.0.0 from v0.11.5.
Official [github release page](https://github.com/mholt/caddy/releases) don't offer 32-bit caddy, so I changed the download url for 32-bit.
More to see mholt/caddy#2628.
=> caddy: Update to version 1.0.0 and fix 32bit URL

bucket/nim.json
Nim devs updated the zip files, and new hashes are needed:
PS > Get-FileHash .\nim-0.20.0_x32.zip
Algorithm       Hash                                                              
---------       ----                                                                   
SHA256          01801B88A8BA4974656B202C7AD6349C08D69D2E35456DF3F065D20A11C18ABC       
PS > Get-FileHash .\nim-0.20.0_x64.zip
Algorithm       Hash                                                           
---------       ----                                                                
SHA256          47CE2A7E77C6BA65266EB35A3319CAFE24E6845947BFBDCAE929E57892CA1491
=> Update nim.json: official ZIP files were updated for version 0.20

bucket/win-acme.json
Didn't have any.
homepage seems to be elsewhere in the json for other projects.
=> win-acme: Add description

bucket/helm.json
Along with helm executable there is also tiller executable, which should also be installed.
Originally Helm was designed to run tiller component inside the Kubernetes clusters, but for security reasons (as then it runs with e.g. cluster-admin permissions, which means that each user running helm client in the end have cluster-admin permissions) it is better to run tiller locally. This is supported and documented at https://helm.sh/docs/using_helm/#running-tiller-locally-1. To be able to use this approach, tiller component should be installed with helm.
=> helm: Add tiller.exe binary

bucket/jdupes.json
I tested this locally, and it works:
````
jdupes: 1.13.1 (scoop version is 1.12) autoupdate available
Autoupdating jdupes
Downloading jdupes-1.13.1-win32.zip to compute hashes!
jdupes-1.13.1-win32.zip (201.6 KB) [=============================================================================================================================================================================================================================================================================] 100%
Computed hash: c18aaf14c1e8c5e51bba17cdafc473b23916f50dc498e640e1c8aae22cf39de6
Downloading jdupes-1.13.1-win64.zip to compute hashes!
jdupes-1.13.1-win64.zip (138.5 KB) [============================================================================================================================================ …
```
=> jdupes: Fix autoupdate URLs

bucket/openssl.json
New location of win32_openssl_hashes.json found on https://slproweb.com/products/Win32OpenSSL.html
=> openssl: Fix autoupdate hash URL

bucket/maven.json
From the README located in `lib/ext`:
> Use this directory to contribute 3rd-party extensions to the Maven core. These extensions can either extend or override Maven's default implementation.
It would be nice if this folder could be persisted between updates.
=> Maven: persist lib/ext

bucket/winpython.json
Example of `innosetup: true` w/ `extract_dir`.
Please MERGE AFTER https://github.com/lukesampson/scoop/commit/e6b2e3d31e246d2af70bd32807159b761fb65e0d merged into `master`
PS: I don't like this manifest that use WinPython as pure Python distribution is a waste.
=> winpython: Add 'extract_dir'

bucket/dotnet-sdk.json
This helps with e.g. making global tools work correctly; see [this blog post][1] for more details.
[1]: https://natemcmaster.com/blog/2018/05/12/dotnet-global-tools/#installing-the-net-core-cli-into-a-non-default-location
=> Set DOTNET_ROOT upon install of the dotnet SDK

bucket/openresty.json
CLI tool. Ref: https://github.com/lukesampson/scoop-extras/pull/2325
- Add `64bit`
- Add missing `bin`
- Add `suggest`
=> openresty: Move from 'extras'

bucket/gsl-shell.json
- "homepage": "http://www.nongnu.org/gsl-shell/"
- "version": "2.3.2"
- "license": "GPL-3.0-or-later"
- "description": "GSL library shell based on LuaJIT2"
`gsl-shell-gui.exe` is just a GUI shell for `gsl-shell.exe`
=> gsl-shell: Add version 2.3.2

bucket/terraform.json
This allows scoop to handle terraform plugins (providers, etc). Plugin example manifest:
```JSON
"architecture": {
"64bit": {
"installer": {
"script": [
"Copy-Item \"$dir\\terraform-provider_v$version.exe\" \"$Env:APPDATA\\terraform.d\\plugins\\windows_amd64\""
]
},
"uninstaller": {
"script": [
"Remove-Item \"$Env:APPDATA\\terraform.d\\plugins\\windows_amd64\\terraform-provider_v$version.exe\""
]
}
}
},
```
=> Terraform: Handle plugin directory

bucket/lame.json
Fixes:
```
lame: couldn't match 'http://www.rarewares.org/files/mp3/lame([\d.]+).zip' in http://www.rarewares.org/mp3-lame-bundle.php
```
in https://scoop.r15.ch/main/mud-20190621-050001.log
=> lame: Update to 3.100-20190620 (manually)

bucket/xmake.json
https://github.com/xmake-io/xmake/releases/download/v2.2.7/xmake-v2.2.7.win64.sha256
https://github.com/xmake-io/xmake/releases/download/v2.2.7/xmake-v2.2.7.win32.sha256
=> xmake: fix hash

bucket/kubefwd.json
It just adds `v` before tag version
=> kubefwd: Fix autoupdate

bucket/radare2.json
Windows edition is released later than other, and don't have hash in hash file. So use webpage to get hash is better.
=> radare2: Fix au.hash

bucket/connect.json
> connect --- simple relaying command via proxy.
The program is no longer available so I created a [pull request](https://github.com/ScoopInstaller/Binary/pull/8) to Scoop's binary mirror.
=> connect: Add version 1.100

bucket/latex.json
Close #102, close https://github.com/lukesampson/scoop/issues/3497
MiKTeX has 64bit installer, but with different `env_add_path`, so after a small hotfix of scoop-core, 64bit will add to the manifest. Now 32bit works fine.
=> latex: Fix manifest and update to 2.9.7086

bucket/latex.json
Fix json validator error by https://github.com/lukesampson/scoop/pull/3503
Manifest installed well even if above PR not merged.
Sidenote: @r15ch13 Excavator will get the right hashes for installer, so autoupdate works correctly. During installation, redirection to nearest mirror is much more preferred. For those users that redirected to `http` mirror and failed downloading, manually downloading the file and moving and renaming it to cache folder should works. This case should be rare since most servers provide `https` protocol. (ref: https://miktex.org/pkg/repositories)
=> latex: Add 64bit installer

bucket/jx.json
Starting from version 2.0.340, the executable is named just `jx.exe`, not `jx-windows-amd64.exe`. Due to this change, a shim for the executable is not correctly created, which results in an incomplete installation. This pull request should fix this behaviour.
=> jx: updated executable name in shim definition

bucket/bison.json, bucket/btyacc.json, bucket/byacc.json, bucket/winflexbison.json
Notes:
* `GNUWin32` has been frozen since 2010. Therefore **checkver** and **autoupdate** is not used in this package.
=> Add bison, byacc, btyacc (from GNUWin32) and winflexbison

bucket/xxcopy.json
Binary files in package:
- xxcopy.exe     ; Win XP/Vista/2003/Win7/Win8/2008 (xxcopy.exe)
- xxcopysu.exe   ; Win XP/Vista/2003/Win7/Win8/2008(std user)
- xxpbar64.exe   ; The Progress Bar display module
- xxconsole.exe  ; a Super Console Generator
`xxcopy` needs installation (write Registry) while `xxcopysu` needn't, and `xxcopy` can't be used in standard user env. So port `xxcopysu` as `xxcopy` and all work fine.
=> xxcopy: Add version 3.33.3

bucket/doctl.json
Fix #248
The `sha256` file is the hash of executive inside...
=> doctl: Fix hashes

bucket/git-annex.json
In fact, it can't pass its test on my machine. Maybe because it needs 32bit git to work, see https://git-annex.branchable.com/install/Windows/. Anyway, it can be downloaded correctly now. If there is anyone who use git-annex with scoop, please try to fix it.
=> git-annex: fix checkver and au.hash

bucket/yarn.json
"Prefix" was changed to "Global-Folder" but "Prefix" is still required for global tools to set up their commands into the correct location rather than localappdata. Example is azure-functions-core-tools.
Both options can be specified concurrently and safely.
=> Yarn: Re-Add Prefix Global Directory Argument

bucket/bind.json, bucket/dig.json
`dig` has been in scoop and it's a part of `bind` . Should I remove `dig.json` ? There is a `vcredist` in dir, could use it or must use `suggest` ?
=> BIND: Add version 9.14.3

bucket/zstd.json
Fixes #256 
It's a console app, so a shortcut is meaningless.
=> zstd: Add extract_dir, remove shortcut

bucket/winpython.json
```
$ scoop  install winpython
Installing 'winpython' (3.7.4.0) [64bit]
Loading WinPython64-3.7.4.0Zero.exe from cache
Checking hash of WinPython64-3.7.4.0Zero.exe ... ok.
Extracting WinPython64-3.7.4.0Zero.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Chen\scoop\apps\winpython\3.7.4.0\WinPython64-3.7.4.0Zero.exe.
Log file:
~\scoop\apps\winpython\3.7.4.0\innounp.log
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=winpython%403.7.4.0%3a+decompress+error
```
In winpython@3.7.4.0    innounp can not extract it.
=> fix winpython extract error

bucket/chromedriver.json
Update ChromeDriver from 75.0.3770.140 to 76.0.3809.68. Required to update Homepage-URL and especially the pattern to check for a new version. This is because between ChromeDriver and the corresponding version a non-breakable-space is rendered, which
did not match the previous `\s*` pattern.
=> ChromeDriver Update 76.0.3809.68

bucket/win-acme.json
=> win-acme: Fix au.url (double v)

bucket/llvm.json
#150. (Outstanding Excavator issues)
**LLVM** has changed their download url, which causes the 404 error.
=> llvm: Fix autoupdate

bucket/y-cruncher.json
**y-cruncher** ([homepage](http://www.numberworld.org/y-cruncher/)) is a multi-threaded benchmark program that calculate Pi and other constants to trillions of digits.
Notes:
* The website (www.numberworld.org) does not support HTTPS.
=> y-cruncher: Add version 0.7.7.9501

bucket/iverilog.json
close https://github.com/lukesampson/scoop-extras/issues/2591
**Icarus VeriLog** (iVeriLog) ([homepage](http://bleyer.org/icarus/)) is a free compiler for IEEE-1364 Verilog hardware description language.
=> iVeriLog: Add version 11-20190327

bucket/pypy2.json, bucket/pypy3.json
https://github.com/lukesampson/scoop-extras/pull/2684
Maybe pypy2 should be moved into version and rename pypy3 as pypy?
=> pypy: Move from extras

bucket/go.json
go 1.13 [no longer provides](https://golang.org/doc/go1.13#godoc) one out of the box
=> Removed godoc binary

bucket/radare2.json
Extract dir changed and should not contain the _dyn suffix
=> radare2: Fix 'extract_dir'

bucket/llvm.json
It was removed in the 9.0.0 release.
=> llvm: Remove lldb-test.exe shim

bucket/saml2aws.json
I've created a package for [saml2aws](https://github.com/Versent/saml2aws). This would be used with *aws* and possibly *aws-iam-authnticator* which are both already in the main bucket. It is currently only available from Chocolatey.
=> Add saml2aws package

bucket/px.json
This is a Pull request to update Genotrance PC the latest (stable) release.
https://github.com/genotrance/px/releases
=> Update Genotrance PX to latest (stable) release

bucket/nmap-portable.json, bucket/nmap.json
This provides a nmap installation without priviliges.
- Some small fixes for the nmap manifest
- Closes https://github.com/lukesampson/scoop/issues/1799
=> nmap-portable: Add version 7.80

bucket/dotnet-sdk.json
OmniSharp isn't able to find SDKs otherwise (see https://github.com/OmniSharp/omnisharp-vscode/issues/2970#issuecomment-524292461)
=> dotnet-sdk: Set MSBuildSDKsPath environment

bucket/iverilog.json
close lukesampson/scoop-extras#2980
I am not familiar with **iVeriLog**,  but it seems that we have to add `bin` to `Env:path` for **iVeriLog** to work properly, according to the user who suggested adding it to the bucket. 
Ref:
lukesampson/scoop-extras#2591
lukesampson/scoop-extras#2980
=> iVeriLog: Add env_add_path

bucket/doctl.json
The pre_install script used to rename "doctl" to "doctl.exe", but this isn't necessary since https://github.com/digitalocean/doctl/releases/tag/v1.30.0, and will produce an error:
```
Rename-Item : Cannot rename because item at 'C:\Users\Pedro\scoop\apps\doctl\1.33.0\doctl' does not exist.
At line:1 char:1
+ Rename-Item "$dir\doctl" 'doctl.exe'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Rename-Item], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand
```
=> doctl: Remove unnecessary pre_install

bucket/lynx.json
I reomve openssl(53M) dependency and download openssl light(3M) directly. The origin manifest doesn't works for me because
1. lynx need `libcrypto-1_1.dll` and `libssl-1_1.dll` but following script try to copy `libcrypto-1_1,1.dll` and `libssl-1_1,1.dll` which do not exist. 
```
"   cp \"$(appdir openssl $global)/current/libcrypto-1_1,1.dll\" \"$dir/libcrypto-1_1,1.dll\"",
"   cp \"$(appdir openssl $global)/current/libssl-1_1,1.dll\" \"$dir/libssl-1_1,1.dll\"",
```
2. There is no cacert.pem in openssl dir. 
3. There is no msvcr120.dll in vcredist2012.
However it still doesn't work with https for some unknown reason. ( I got `SSL error:Can't find common name in certificate-Continue? (n)` ). As I'm not a lynx user I can't solve this problem.
By the way, scoop decompress openssl installer …
=> lynx: remove openssl dependency

bucket/winpython.json
=> winpython: Fix checkver

bucket/yarn.json
By default, `require` function doesn't look in the folder where global modules are installed by yarn, so only global modules installed by npm can be require properly. Add the path of global modules folder to the NODE_PATH environment variable to solve this.
=> yarn: Add env_set

bucket/watchexec.json
Moved from `gnu` to `msvc` builds.
#150
=> watchexec: Update to version 1.11.1

bucket/just.json
#150 (Outstanding Excavator issues)
The file name was changed because [Just](https://github.com/casey/just/releases) changed their toolchain from `gnu` to `msvc`.
=> just: Update to version 0.4.5 (manually)

bucket/nu.json
#150 (Outstanding Excavator issues)
The download URL was changed because [nushell](https://github.com/nushell/nushell/releases) changed their version tag pattern from `0.5.0` to `0_5_0`
=> nu: Update to version 0.5.0 (manually)

bucket/rtools.json
R is in the main bucket but Rtools is not.
This file adds Rtools. Rtools is the collection of compiler tools for compiling R or some R projects that uses external C, C++ or Fortran libraries.
=> rtools: Add version 3.5.0.4

bucket/nircmd.json
The field `"extract_dir": ".",` in the manifest was causing nothing to extract to the app directory, so the install would fail.
- Closes lukesampson/scoop#3726
=> nircmd: removed "." extract_dir that broke install

bucket/kubefwd.json
#150 (Outstanding Excavator issues)
The download URL is changed from `releases/download/v$version/xxx` to `releases/download/$version/xxx`.
(See: https://github.com/txn2/kubefwd/releases/)
=> kubefwd: Update to version 1.9.5 (manually)

bucket/lazydocker.json
Lazydocker is "The lazier way to manage everything docker".
It is widely used with >36k downloads and >12k stars on GitHub.
As of version 0.7.5 it supports windows as platform.
See: https://github.com/jesseduffield/lazydocker/releases/tag/v0.7.5
=> lazydocker: Add version 0.7.5

bucket/radare2.json
Fix #551 
There's new binary zip with new name, but not sure it is permanent or not.
=> radare2: Fix download url and hash

bucket/youtube-dl.json
This would be convenient, as I use ffmpeg-nightly instead of ffmpeg. I've also seen other manifests in the known repos do it this way.
I also reordered the manifest to the recommended order.
**EDIT:** As far as I can tell, youtube-dl doesn't strictly need FFmpeg to run.
=> youtube-dl: Suggest ffmpeg instead of depending on it

bucket/nomad.json
According to https://releases.hashicorp.com/nomad/0.10.1/nomad_0.10.1_SHA256SUMS 
```
00531dc66f33051aeccca8a644fdb0fa4a9276ef889b7748cd31cd3f821a76d4  ./nomad_0.10.1_windows_386.zip
227b753a1f4407d16714e86506f503be576f6b2203ecc35e5c9f37bd7a62af91  ./nomad_0.10.1_windows_amd64.zip
```
=> nomad@0.10.1: Fix hash

bucket/k6.json
https://k6.io/
moved here from this [PR in extras](https://github.com/lukesampson/scoop-extras/pull/3231) as requested
- Closes lukesampson/scoop-extras#3220
=> k6: Add version 0.25.1

bucket/git-filter-repo.json
**git-filter-repo** is a tool for rewriting Git history, alternative to the `git filter-branch` command.
Endorsed by git itself:
```
$ git filter-branch
WARNING: git-filter-branch has a glut of gotchas generating mangled history
rewrites.  Hit Ctrl-C before proceeding to abort, then use an
alternative filtering tool such as 'git filter-repo'
(https://github.com/newren/git-filter-repo/) instead.  See the
filter-branch manual page for more details; to squelch this warning,
set FILTER_BRANCH_SQUELCH_WARNING=1.
```
A few things to note:
1. Not sure whether `depend` on Python or `suggest` it.
2. Not sure whether call `python3` or just `python` in the ps1 shim.
The tool itself apparently expects Python 3.
=> git-filter-repo: Add version 2.24.0

bucket/git-with-openssh.json, bucket/git.json
I remove the note because openssh.json is out of date. git-with-ssh should be a better choice. (Related: https://github.com/lukesampson/scoop/issues/2414)
=> git: Add more shortcuts

bucket/axel.json
There will not be an official build for Windows in a near future. See https://github.com/axel-download-accelerator/axel/issues/108 . 2.16.1-1 is still out of date but much better than 2.4 .
=> axel: Update to version 2.16.1-1, use Unix Utils ported to Windows build

bucket/unbound.json
Those bin.args come from help output.
About the origin pre_install, see https://github.com/lukesampson/scoop/pull/1513#issuecomment-304188246
About the origin post_install, there is only one cmd file in the package now.
=> unbound: Update to version 1.9.5

bucket/youtube-dl.json
GitHub thankfully redirects rg3 just fine, but this is cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scoopinstaller/main/616)
=> youtube-dl: Update GitHub owner to ytdl-org

bucket/ie11webdriver.json
[Here](https://github.com/SeleniumHQ/selenium/tree/master/cpp/iedriverserver) is the source code.
=> ie11webdriver: Update to version 3.150.1

bucket/scrcpy.json
scrcpy-server.jar is renamed to scrcpy-server in version 1.11 . It works well without the env variable so I remove the env_set.
=> scrcpy: remove env_set

bucket/cormanlisp.json
Adds in Corman Lisp with all the proper initialization from the MSI installer.
The icon has to be downloaded separately because it's a byte array in the Icon table in the MSI, but the MSI extractor deletes that before we can do anything with it in `pre_` or `post_install`, and it also would be extracted normally via `dark -x`, but #3502 isn't merged yet, and it's present in the `CormanLisp.exe` Portable Executable, but there are no interfaces to `kernel32.dll` FindResource/LoadResource in .NET and extracting and recreating the `.ico` from here would require C#, `DllImport`, and more, or an ungodly section of PowerShell code, and overall we can't have nice things. So we download the `.ico` once again for the REPL shortcut to have the nice icon its supposed to have.
---
This change is [<img …
=> cormanlisp: Add version 3.1.2b

bucket/dnscrypt-proxy.json
- Closes #636
About localhost.pem, see https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Local-DoH
=> dnscrypt-proxy: fix hash, change url, persist localhost.pem and polish

bucket/haskell.json
Stack in Haskell is outdated, so using seperate `stack` is preferred.
=> haskell: Remove 'stack.exe' bin

bucket/dmg2img.json
**dmg2img** ([homepage](http://vu1tur.eu.org/tools/)) is a command-line tool that converts Apple's DMG disk image file to IMG image file.
Notes:
* The `GPL-2.0-or-later` license is contained in the archive. (dmg2img-1.6.7-win32.zip)
=> dmg2img: Add version 1.6.7

bucket/k2tf.json
> `k2tf` is a tool for converting Kubernetes API Objects (in YAML format) into HashiCorp's Terraform configuration language.
> 
> The converted `.tf` files are suitable for use with the Terraform Kubernetes Provider
See: https://github.com/sl1pm4t/k2tf
> `k2tf` is a tool for converting Kubernetes API Objects (in YAML format) into HashiCorp's Terraform configuration language.
> 
> The converted `.tf` files are suitable for use with the Terraform Kubernetes Provider
See: https://github.com/sl1pm4t/k2tf
Initially opened this PR for the `extras` bucket, but was redirected here.
=> k2tf: Add version 0.3.0

bucket/aws-iam-authenticator.json
This PR conflicts with #658 to solve #150 for `aws-iam-authenticator` with a (hopefully) more robust approach.
Instead of fetching the executable from Amazon's well-hidden download link in their documentation, this gets it from their GitHub project.
=> aws-iam-authenticator: Use GitHub repository

bucket/gsudo.json
gsudo: A sudo for windows with similar user experience as *nix sudo and credentials cache (avoid repeated UAC popups)
Migrated from scoop-extras to main repo: lukesampson/scoop-extras#3369 as per https://github.com/lukesampson/scoop-extras/pull/3369#pullrequestreview-335592819
=> gsudo: Add version 0.4.1

bucket/isx.json
**ISx** ([Github repo](https://github.com/lifenjoiner/ISx)) is an InstallShield installer extractor.
=> isx: Add version 0.3.2

bucket/broot.json
> broot: A new way to see and navigate directory trees
> https://dystroy.org/broot/
> https://github.com/Canop/broot
=> broot: Add version 0.11.7

bucket/chuck.json
ChucK is a strongly-timed, music oriented programming language.
**Considerations:**
- The installer comes with a GUI tool (`miniAudicle.exe`). A shortcut was not added, although it might be a good idea to do so given it's usefulness (but clearly not required to be able to work with it!);
- At the moment, ChucK is distributed by two universities: [Stanford](http://chuck.stanford.edu) and [Princeton](https://chuck.cs.princeton.edu). While the former is apparently the "official" one, the latter is (from my testing) faster + supports https.
=> chuck: Add version 1.4.0.0

bucket/highlight.json
Idea: would it be nice to validate `extract_dir` when, e.g., calculating the package hash?
=> hightlight@3.55: Fix extract dir

bucket/minio-client.json, bucket/minio.json
MinIO officially using **min.io** as the main URL , now
=> minio(-client): Use official URL

bucket/bind.json
Remove 32bit. https://github.com/ScoopInstaller/Main/issues/150
fix https://github.com/ScoopInstaller/Main/issues/710
dig in bind 9.14.9 works without msvcr110.dll . I don't know why 9.14.8 need that.
Should I remove or fix dig manifest?
=> bind: Update to version 9.14.9

bucket/lwc.json
Adds `lwc`, a simple CLI tool writen in Go.
In case `lwc` is a bit too niche, i'll gladly open a PR for the extra bucket.
=> lwc: Add version 0.4.5

bucket/zenhan.json
[zenhan](https://github.com/iuchim/zenhan): Switch the mode of input method editor from terminal. 
This is a tool similar to [im-select](https://github.com/daipeihust/im-select). zenhan switches IME mode instead of switching IME like im-select.
You can use zenhan from autoSwitchIM function of VSCodeVim.
https://github.com/VSCodeVim/Vim#input-method
=> zenhan: Add version 0.0.1

bucket/shasum.json
To quiet spurious log entry. See #150
=> shasum: Update to 0.2020.01.26 (version only)

bucket/z.lua.json
> z.lua is a faster way to navigate your filesystem. It tracks your most used directories, based on 'frecency'. After a short learning phase, z will take you to the most 'frecent' directory that matches ALL of the regexes given on the command line, in order.
I have tested the App Manifest locally for install/uninstall/autoupdate.
=> z.lua: Add version 1.7.4

bucket/vim-nightly.json, bucket/vim.json
- Closes #749 
Next to _vimrc, there is also a vimrc file that is loaded before any other configs, which is sometimes needed to modify for example the HOME variable or the rtp. See issue #749 for more information.
=> vim(-nightly): Add vimrc persist

bucket/espanso.json
Fixes #781 
Ran autoupdate locally; hash calc by Extract Mode and subsequent installation worked as expected.
=> espanso@0.5.0: Fix hash

bucket/packer.json
Updated hashes for both x86 and x64 installers.
=> packer@1.5.2: Fix hash

bucket/openssl.json
This adds the `bin` directory to `PATH` to make provided libraries discoverable.
This is according to https://github.com/timvisee/ffsend/issues/106#issuecomment-584661412, and is needed because `ffsend` currently fails to find the installed OpenSSL libraries.
I'm not sure whether to increase a version number or anything in this manifest as well, to force-update and apply the `PATH` variable on current systems.
=> openssl: Add to PATH to make libraries discoverable

bucket/pandoc.json
As the pandoc executables now are located deeper inside another level of the path, an extract_dir is needed.
=> pandoc@2.9.2: Fix installation

bucket/migrate.json
This is a very useful CLI when working with databases.
It is used to migrate/rollback database changes over time.
~~The current version (4.8.0) is only released as a 64-bit windows exe, so this bucket only supports 64-bit installs.~~
~~I asked if upstream could provide 32-bit windows binaries in the future in golang-migrate/migrate#339~~
=> migrate: Add version 4.9.1

bucket/ziglang.json
Zig compiler does not start when `vcruntime400_1.dll` is not present on the system. Since shim gives no output, it is very confusing behavior and user gets impression that there is something fishy with zig. It's preventable by suggesting vcredist2019.
=> ziglang: Suggest vcredist

bucket/cuda.json
env variable **CUDA_PATH** should be set to the installation path, not `.`. This fixes the problem.
=> cuda@10.2.89_441.22: Fix env variables

bucket/byenow.json
[byenow](https://iobureau.com/byenow/) is a command-line Windows utility for faster folder removal.
fixes #831
=> byenow: Add version 0.2

bucket/moonscript.json
close https://github.com/lukesampson/scoop/issues/3041
**MoonScript** ([homepage](https://moonscript.org/)) is a dynamic scripting language that compiles into *Lua*.
Notes:
* The *MIT license* can be found in the `LICENSE` file in the archive.
* *checkver/autoupdate* is not needed because *MoonScript* has not been updated since 2016.
* Usage of `moon.exe` and `moonc.exe` can be found [here](https://leafo.net/posts/getting_started_with_moonscript.html#creating-programs/compiling-and-running).
=> moonscript: Add version 0.5.0

bucket/win-acme.json
#150 
Updated version, github page moved, and new website.
https://github.com/win-acme/win-acme/releases/tag/v2.1.5
> * For those who hadn't noticed yet, we have moved to our own Github organisation and our own domain name https://win-acme.com/
There may be a problem with the autoupdate URLs though. As you can see this release is v2.1.5 but still includes the build number `...download/v2.1.5/win-acme.v2.1.5.742.x...` which doesn't match the pattern, and most likely won't in the future either.
=> win-acme: Update to version 2.1.5.742

bucket/sass.json
There is an official alias `dart-sass` alias for the sass package I added to the manifest for compatibility reasons. 
Check https://github.com/sass/dart-sass/blob/master/pubspec.yaml
```yaml
executables:
dart-sass: sass
sass: sass
```
=> sass: Add dart-sass shim

bucket/python.json, scripts/python/install-pep-514.reg, scripts/python/uninstall-pep-514.reg
- Closes #128
PEP 514 specifies how python should be added to the registry so
third-party installers, binary packages depending on python (vim), and
pre-compiled binary extension packages (kivy, Pillow, PyGame) can find
python.
I think it also helps resolve python finding 32-bit vs 64-bit
executables.
Seems that python requires the "PythonCore" key. Testing with gvim:
gvim +"py3 print(3)"
crashes with "Scoop" but works with "PythonCore". We're installing
python built by the Python Software Foundation, so it might be matching
that name somewhere inside of python.exe.
Since the manifest uses github urls, it won't work until merged into master. If you want to check it out, I made [a testing branch that points to itself](https://github.com/idbrii/scoop-bucket-main/tree/py-registry-testing-agai …
=> python: Add registry configuration

bucket/shellcheck.json
koalaman/shellcheck#1871
> From now on, you can download precompiled binaries from GitHub Releases where they're uploaded as assets on each release.
=> shellcheck: Use github releases

bucket/hostctl.json
This CLI tool allows you to manage your hosts file by profiles with ease. Check [hostctl home](https://github.com/guumaster/hostctl)
=> hostctl: Add version 0.5.3

bucket/gh.json
Maybe there is a better way but I manually edited this file and downloaded the files manually and checked their hash via powershell
```ps
> get-filehash -path .\gh_0.6.3_windows_amd64.zip  -Algorithm SHA256 | format-list
```
=> gh: Update to version 0.6.3

bucket/git-with-openssh.json, bucket/git.json
gitk does not work from the shortcut, it runs as a cli tool. The shortcut was introduced in #546
=> git: remove gitk shortcut

bucket/tesseract.json
`tesseract` requires env var `SCROLLVIEW_PATH` to be set to call .jar files (see [here](https://tesseract-ocr.github.io/tessdoc/ViewerDebugging.html)).
=> tesseract: set new env var SCROLLVIEW_PATH

bucket/ack.json
The path passed to perl.exe must be quoted. Otherwise running `ack` fails if the scoop install path has spaces (e.g. `C:\Users\William Ellis\scoop`).
=> ack: Quote path in order to support spaces in path

bucket/gcc.json
Close #928
This needs to update manually.
Or should I move this to `versions` bucket?
=> gcc: Update to 9.3.0-1 using MSYS2's build

bucket/cmder-full.json, bucket/cmder.json
Move the folder "bin" into persist.
Fix https://github.com/ScoopInstaller/Main/issues/1027.
=> cmder: Persist "bin"

bucket/roswell.json
I would like to add roswell to the main bucket if possible.
The installation and autoupdate are working perfectly.
I already contacted the roswell devs and they even added the checksums to the release page so i could add it 
https://github.com/roswell/roswell/issues/419
Thank you!
=> roswell: Add version 20.04.14.105

bucket/cdrtools.json
cdrtools (at least schily-cdrtools-3.02a09.7z) only contains a win32 dir,
so don't specify architecture
closes https://github.com/lukesampson/scoop/issues/3856
=> cdrtools: Fix installation

bucket/minio-client.json, bucket/minio.json
I updated the url accordingly to the min.io servers.
I also updated minio-client to the latest version while I was on it.
Cheers
=> minio: Use archive URL

bucket/mill.json
The current version does not support auto-updating to "in-between" versions like 0.6.2-7-f10b89. This change allows such versions to be installed as well.
=> mill: Support auto-update for in-between versions.

bucket/stack.json
#150
https://github.com/commercialhaskell/stack/releases/tag/v2.3.1
> We have reduced the number of platforms that we support with binary releases.
The reason behind this is that we've been slowed down in our release process
until now with issues trying to build binaries for less common platforms. In
order to make sure we can address issues more quickly (like supporting new
GHC versions), we're limiting support from the Stack team to:
>Linux 64-bit (static)
>macOS
>Windows 64-bit
=> stack: Update to version 2.3.1

bucket/spotbugs.json
[SpotBugs](https://spotbugs.github.io/) is a static analysis tool for Java code. It comes with a command-line interface and a GUI.
=> spotbugs: Add version 4.0.2

bucket/ffsend.json
The `openssl` dependency is not needed anymore.
=> ffsend: Remove OpenSSL dependency

bucket/wixtoolset.json
environment variable for WixToolPath added
=> fix: WixToolPath not added to env Variables

bucket/less.json
It appears as though the upstream source for this package is dead: `www.guysalias.tk` (parked domain?).  It also points to an older version of `less`.
I have created this repo to address this problem:
https://github.com/jftuga/less-Windows/
I am using `AppVeyor` for automatic nightly builds of `less`.  The `version_compare.py` script will run once per day.  It compares the version this repo is hosting against the [official less version](http://greenwoodsoftware.com/less/download.html).  If there is a new version, then `build.py` will download, compile, and create a new GitHub release containing `less.exe` and `lesskey.exe`.  If the versions are the same, then nothing will be updated.
I am currently tracking the `BETA` instead of the `RECOMMENDED` version as `v561` fixes a bug in which …
=> less: new upstream, version 561

bucket/kubectx.json, bucket/kubectxwin.json
https://github.com/ahmetb/kubectx
kubectx is a utility to manage and switch between kubectl(1) contexts.
Ref: https://github.com/ScoopInstaller/Main/pull/995#issuecomment-635066207
=> kubectx: Add version 0.9.0

bucket/watchexec.json
Mainly for manifest fixing with 64bit architecture
=> watchexec: Update to version 1.13.0

bucket/pandoc-crossref.json
This version fixed compatability with pandoc 2.9.2.1
=> pandoc-crossref: Update to version 0.3.6.3

bucket/pandoc-crossref.json
Updating to pandoc-crossref 0.3.6.3 (see scoop's installation log below): This commit should fix the path to the binary from `pandoc-crossref.exe` to `windows-build/pandoc-crossref.exe`. 
NOTE: The change is untested.
~~~
pandoc-crossref: 0.3.6.2 -> 0.3.6.3
Updating one outdated app:
Updating 'pandoc-crossref' (0.3.6.2 -> 0.3.6.3)
Downloading new version
pandoc-crossref-Windows-2.9.2.1.7z (9,4 MB) [==========================================================================================================================] 100%
Checking hash of pandoc-crossref-Windows-2.9.2.1.7z ... ok.
Uninstalling 'pandoc-crossref' (0.3.6.2)
Removing shim for 'pandoc-crossref'.
Unlinking ~\scoop\apps\pandoc-crossref\current
Installing 'pandoc-crossref' (0.3.6.3) [64bit]
Loading …
=> pandoc-crossref@0.3.6.3: Fix installation

bucket/grpcurl.json
This PR adds grpcurl to the main bucket. This is a cURL-like command-line tool for interacting with gRPC servers.
Tool repository: https://github.com/fullstorydev/grpcurl
The grpcurl project doesn't always include the CLI tool assets for every release, which is why the more customized `checkver` logic is used instead of just `github`.
Thank you!
=> grpcurl: Add version 1.6.0

bucket/tre-command.json
[tre](https://github.com/dduan/tre) is a cross-platform CLI tool that
improves upon the classic `tree` Unix command. It's been distributed
[with Nix][] for a while. It's time to add it to Scoop main!
Unfortunately, in places such as Homebrew and Nix there's an existing
library `tre`. So the `-command` is chosen as part of the package name.
(I'm the author and maintainer of the tool).
[with Nix]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/tre-command/default.nix
=> tre-command: Add version 0.3.1

bucket/naiveproxy.json
[NaïveProxy](https://github.com/klzgrad/naiveproxy) uses Chrome's network stack to camouflage traffic with strong censorship resistence and low detectablility. Reusing Chrome's stack also ensures best practices in performance and security.
=> naiveproxy: Add version 83.0.4103.61-1

bucket/kaf.json
Modern CLI for Apache Kafka, written in Go.
=> kaf: Add version 0.1.38

bucket/gum.json
Gum is a Gradle/Maven wrapper written in Go
Gum automatically detects if the project is Gradle or Maven-based and runs the appropriate command. However, in the case that Gum guesses wrong, you can force a specific build tool to be used.
Shim `gum` is defined because `gm` is not resolved as `gm.exe` but as Powershell commandlet `Get-Members` which is unfortunate.
=> gum: Add version 0.4.0

bucket/msys2.json
This PR updates msys2 to version 20200629.
~~This PR updates msys2 to version 20200517, which is the last version that comes with both `i686` and `x86_64` packages.~~
=> msys2: Update to version 20200629

bucket/unison.json
Fsmonitor is part of package and is used for auto-updating based on disk changes. I can also prepare separate json for fsmonitor only, if cache caches zip from github, it won't re-download same package.
=> unison: Add fsmonitor shim

bucket/vswhere.json
vswhere is a tool commonly with over 6M tracked downloads used in both on-prem and cloud pipelines like Azure DevOps, Visual Studio-related GitHub Actions, boost build pipelines, and more. It is used to locate a suitable Visual Studio 2017 or newer install with required features, and find toolsets within it or set up PATH. It's already in chocolatey but some users have asked for scoop support.
Fixes microsoft/vswhere#122
=> vswhere: Add version 2.8.4

.github/workflows/issue_comment.yml, .github/workflows/issues.yml, .github/workflows/pull_request.yml
Looks like GitHub is moving toward non-racist naming convention on all their actions
=> fix(actions): Migrate to 'main' branch

bucket/ispc.json
- Closes #1054
Adds ISPC (https://ispc.github.io/). For more information:
> Intel's ISPC (Implicit SPMD Program Compiler) is an LLVM-based OSS (BSD-3) compiler for a C-like language designed to be used in conjunction with standard C/C++ programs to provide a reliable and clean means of optimizing programs using appropriate vector processing hardware instructions on the CPU as an alternative to the potentially more cumbersome approaches of inline assembly and compiler intrinsics.
=> ispc: Add version 1.13.0

bucket/mockery.json
[vektra/mockery](https://github.com/vektra/mockery) is a tool for generating mocks of Go interfaces.
Rationale for including in the main bucket:
* a reasonably well-known and widely used developer tool: I believe so. It is one of the two most well known mock generators for Go. Here is a [relatively recent comparison](https://blog.codecentric.de/2019/07/gomock-vs-testify/) which should prove the prominence of this tool.
* the latest stable version of the program: Yes. You can check the [releases](https://github.com/vektra/mockery/releases) page.
* the full version i.e. not a trial version: The program is open source.
* a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts): It is distributed as a single tarball containing a single …
=> mockery: Add version 2.0.4

bucket/zoxide.json
[`zoxide`](https://github.com/ajeetdsouza/zoxide) is a command line filesystem navigator written in rust. It's similar to [autojump](https://github.com/wting/autojump) and [z](https://github.com/rupa/z) with native Windows and PowerShell support.
=> zoxide: Add version 0.4.3

bucket/alass.json
Alass (Automatic Language-Agnostic Subtitle Synchronization) is a command line tool to synchronize subtitles to movies.
=> alass: Add version 2.0.0

bucket/ipopt.json
Ipopt is a widely used command-line software package for large-scale nonlinear optimization. The environment variable `IPOPTWINDIR` allows wrappers such as [cyipopt](https://github.com/matthias-k/cyipopt) to find it.
=> ipopt: Add version 3.13.2

bucket/clink.json
C:> clink autorun
ERROR: Invalid arguments. Run 'clink autorun --help' for info.
=> clink.json: notes: correct the "clink autorun"

bucket/less.json
A new version of `less` is available from jftuga's repository. This version should fix [this bug](https://github.com/sharkdp/bat/issues/1098) in `bat`.
=> Update less version

bucket/envsubst.json
This PR adds the [envsubst](https://github.com/a8m/envsubst) package.
From what I can from the project this package is x64 and I've added it accordingly.
=> ensubst: Add version 1.2.0

bucket/tre-command.json
Release note: https://github.com/dduan/tre/releases/tag/v0.3.2
=> Update tre-command to 0.3.2

bucket/gbt.json
GBT is highly configurable prompt builder for Bash, ZSH and PowerShell written in Go.
=> gbt: Add version 2.0.0

bucket/tinygo.json
Adds tinygo v0.14.1 to scoop.
TinyGo brings a subset of go to micro-controllers & makes tiny things just go awesome!
Added a suggestion for `go` but if you think it's not required, can remove. Feedback welcome.
=> tinygo: Add version 0.14.1

bucket/fossil.json
- Closes #1353
- Closes #1365
- Closes #1373
- Closes #1374
this commit fixes also the error message: 
fossil: couldn't match 'Version ([\d.]+)"' in https://www.fossil-scm.org/index.html/uv/download.js
Root cause is a format change of the title format of download.js, which now also contains a timestamp:
```
"title":     "Version 2.12.1 (2020-08-20)",
```
I have changed the regex to parse the history field now, which may also be more resistant against breaks in future:
```
"history":   "../timeline?p=version-2.12.1&bt=version-2.11&n=all"},
new regex:              "p=version-([0-9.]+)"
```
=> fossil: Update to version 2.12.1

bucket/gcc.json
It seems a good idea to install gcc and gdb together since they are essential for development.
Both of them are provided by mingw in the same repository.
=> Add gdb-9.1-3 for gcc package

bucket/android-clt.json
Android Command Line Tools (`android-clt`, the name can be discussed) is the successor of [`android-sdk`](https://github.com/lukesampson/scoop-extras/blob/master/bucket/android-sdk.json).
If this gets merged we probably want to modify [what `android-studio` suggests](https://github.com/lukesampson/scoop-extras/blob/02d4c9f9a0780e6e7fba618ac929bcd5af0b9466/bucket/android-studio.json#L33) too.
=> android-clt: Add version 6609375

bucket/pypy2.json, bucket/pypy3.json
Bitbucket download url is broken.
Because pypy repository move to https://foss.heptapod.net/pypy/pypy
=> pypy(2, 3): fix download url

bucket/avr-gcc.json
Will update the TinyGo package (#1390) with a suggest of this package so it pops in nicely for tinygo development work.
Using included MD5 the author shares.
As always, feedback welcome.
=> avr-gcc: Add version 10.1.0

bucket/vulkan.json
I am not sure if this is the best method but VULKAN_SDK path should be automatically added so that any tools looking for Vulkan can do so with ease :)
normally something like this works [Environment]::SetEnvironmentVariable("VULKAN_SDK", "$env:USERPROFILE/scoop/apps/vulkan/current/", "Machine")
assuming scoop is in userprofile and not elsewhere.
=> Added VULKAN_SDK path

bucket/poppler.json
Fixes #1046 
The current source (https://blog.alivate.com.au/poppler-windows) has not been updated in over 2 years. This modifies the poppler manifest to download the latest binaries from anaconda.org (https://anaconda.org/conda-forge/poppler/files). Latest version came out a week back.
As mentioned in #1046, anaconda.org only has 64-bit binaries, while the earlier source only has 32-bit. Not sure if this will be an issue.
=> poppler: Update to version 0.90

bucket/pypy2.json
previous URL missed the pypy folder
=> Fix pypy2 7.3.2 URL

bucket/llvm.json
Remove clang-import-test shim because it is not distributed anymore
=> LLVM: Update to version 11.0.0

bucket/pandoc.json
λ  scoop install pandoc
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'pandoc' (2.11.0.1) [64bit]
Loading pandoc-2.11.0.1-windows-x86_64.zip from cache.
Checking hash of pandoc-2.11.0.1-windows-x86_64.zip ... ok.
Extracting pandoc-2.11.0.1-windows-x86_64.zip ... done.
Linking ~\scoop\apps\pandoc\current => ~\scoop\apps\pandoc\2.11.0.1
Creating shim for 'pandoc'.
Creating shim for 'pandoc-citeproc'.
Can't shim 'pandoc-citeproc.exe': File doesn't exist.
=> pandoc: Update to 2.11.0.2 and remove pandoc-citeproc.exe shim

bucket/puppet-bolt.json
Add post-install script for tarball of gems to fix the issue https://github.com/ScoopInstaller/Main/issues/1364
The PowerShell module relies on a registry entry which can't be set without elevated privileges. Therefore it won't be part of this fix.
=> puppet-bolt: fix issue with missing gems

bucket/azure-cli.json
As identified in, e.g., [the Azure Go SDK][1] and [other Azure SDKs][2], the Azure CLI program can be resolved using an environment variable called AzureCLIPath or AZURE_CLI_PATH if the program is not installed to the default locations. Setting this environment variable allows programs which build on the Azure SDKs to resolve the CLI program when it has been installed with Scoop.
[1]: https://github.com/Azure/go-autorest/blob/afe17657e2844fc0def7ffbf572d7d869ffedb4d/autorest/azure/cli/token.go#L151
[2]: https://github.com/search?q=org%3AAzure+AzureCLIPath&type=code
=> azure-cli: Set AzureCLIPath environment variable

bucket/vulkan.json
The current `VULKAN_SDK` environment variable points to the incorrect path. The _persist_ folder does not exist for this scoop install.
Additionally, this PR adds the `VK_SDK_PATH` environment variable.
=> fixes vulkan sdk environment variables

bucket/wkhtmltopdf.json
#150
Release notes state, that the hashes are not provided in this release. I did not removed it as maybe in future it will be available.
It will be removed on next update without hashes.
=> wkhtmltopdf: Update to version 0.12.6-1

bucket/elm.json
To fix this annoying message:
Missing runtime dependencies:
'elm' requires 'nodejs'
=> elm: Change depends to nodejs-lts

bucket/busybox.json
"bash -l" changes directory to the home directory
instead of remaining in the current working directory.
It should not change directory when "bash -c" is executed
to run a command in the current working directory.
=> busybox: do not add '-l' flag in bash shim

bucket/fzf.json
fzf's binary repository moved from junegunn/fzf-bin to junegunn/fzf
From [github.com/junegunn/fzf-bin](https://github.com/junegunn/fzf-bin):
> DEPRECATED
>
> Since 0.24.0, new releases will be available in https://github.com/junegunn/fzf/releases
=> fzf: Updated to version 0.24.1 (+ update url)

bucket/node-chakracore.json, bucket/nodejs-lts.json, bucket/nodejs.json
Since this [issue](https://github.com/lukesampson/scoop/issues/3785) was fixed, the order of the environmental variables has changed.
So `bin` should be above `.`, otherwise `pnpm global install` will create shortcut in `scoop/apps/nodejs/current`, not in `scoop/persist/nodejs/bin`.
=> nodejs(*): reorder env_add_path

bucket/starship.json
starship silently fails running without VCRUNTIME140.dll when installed with scoop (starship/starship#1173).
Suggest installing vcredist on install to prevent users from running into this problem.
=> starship: suggest installing vcredist

bucket/git.json
This PR updates the `post-install` step of the git manifest to set the default `credential.helper` to `manager-core`. This matches the changes performed in Git for Windows 2.29 ([change](https://github.com/git-for-windows/build-extra/pull/305/files#diff-b1bc3036e6b6e15d36f016775a046b33fe502165d659b34611e6f10cb37f7e51R111), [pull-request](https://github.com/git-for-windows/build-extra/pull/305), [announcement](https://github.blog/2020-07-02-git-credential-manager-core-building-a-universal-authentication-experience/)).
=> git: Use Git Credential Manager Core

bucket/rakudo-star.json
taking the the description from https://rakudo.org/star and adding the **_zef_** tool to the bin / path to enable RAKU module management.
=> rakudo-star: Change description and add ZEF to bin

bucket/azure-functions-core-tools.json
Address an issue in #150. `azure-functions-core-tools` has `v1`, `v2` and `v3` releasing parallel, and `v3` is recommended. [GitHub Tag API](https://api.github.com/repos/Azure/azure-functions-core-tools/tags) will return tags sorted by name (big to small), i.e. `v3` series are at the top despite of release date.
=> azure-functions-core-tools: Update to version 3.0.2996

bucket/mongodb.json
Address an issue caused by its seperation with `mongodb-database-tools`. (See #1629 and [the document](https://docs.mongodb.com/database-tools/bsondump/))
=> mongodb: Fix bin

bucket/puppet-bolt.json
Like GEM_HOME, GEM_PATH needs to be reset to use the puppet-bolt gems.   
TODO
(can we have multiple pre_install keys?)
We also should create a $dir\\gem.bat file that resets GEM_HOME and GEM_PATH
=> puppet-bolt: Set GEM_PATH

bucket/caddy.json
Caddy has moved on GitHub to the `caddyserver` org.
=> fix: caddy github organization

bucket/composer.json
improved checkversion following the discussion here: https://github.com/ScoopInstaller/Main/commit/71d7c4398527d1aad1aa240c2974ee1275036f8e to ensure the check always get's the latest version and not the latest release on github.
=> composer: checkver improvements

bucket/tor.json
NOTE: the 32-bit package's signature wasn't updated.
=> tor: Fix URLs

bucket/glab.json
[`glab`](https://github.com/profclems/glab) is an open-source GitLab command line tool
=> glab: add version 1.12.1

bucket/sndcpy.json
sndcpy is a tool for audio forwarding on Android 10 and above. The intended purpose is to be used with scrcpy.
=> sndcpy: Add version 1.0

bucket/objconv.json
https://www.agner.org/optimize/#objconv.
`pre_install` is for flattening a deeply nested folder.
=> objconv: Add version 2020-Jun-08

bucket/gobuster.json
This manifest had auto-update but did not use `$version` and was downloading the old version.
Gobuster now provides SHA256 hashes for releases, so I've added `hash` to `autoupdate`.
https://github.com/OJ/gobuster/releases
=> Fix gobuster manifest

bucket/mob.json
Adds [mob](https://github.com/remotemobprogramming/mob) to scoop. 
Mob is a tool for fast git handover while mob programming.
I hope I included everything which is needed. I also verified that autoupdate works using `checkver.ps1`
In case something is off, let me know.
=> Add mob 1.1.0

bucket/llvm.json
https://github.com/llvm/llvm-project/releases/latest
LLVM is quite possibly now that they have completed a move to GitHub are not maintaining their website.
LLVM 11.0.1 while is listed as a release on GitHub Releases, is not listed as a release on their website
Since they are using GitHub releases, I think it would be best to update the project via GitHub Releases as well.
=> Change LLVM update URL to GitHub Releases and update to 11.0.1

bucket/scoop-search.json
https://github.com/shilangyu/scoop-search is a drop-in search replacement by @shilangyu that makes `scoop search` actually faster than googling the manifest. 
Closes https://github.com/shilangyu/scoop-search/issues/10
=> scoop-search: add version 1.0.1

bucket/redis5.json
- create new entry for redis 5.0.10 (redis5) as default redis 3.2 of main bucket is out dated
- related to #1525
=> Add Redis 5.0.10

bucket/ffmpeg.json
Current download URL is no longer valid (404). Fixes #1826
=> ffmpeg: update download url

bucket/nmap-portable.json
There was no file `npcap-*-oem.exe` which could match. But there is a `npcap-1.00.exe`, so I changed `npcap-*-oem.exe` to `npcap-*.exe` to match it and continues the pre_install step without erroring.
I indeed tested the changes and all is what it should be now.
=> nmap-portable: Fix pre-install step

bucket/nano.json
Looks like the upstream packager changed the names of the folder structure in their zip, this fixes it so it will install with Scoop.
=> nano: fix shim

bucket/coq.json
For VSCode's plugin VSCoq support. Fixes #1716
=> coq: Add coqidetop.opt.exe shim

bucket/git.json
Stop setting the credential manager as `post_install` task.
Resolve #1617, #1126 and #2190
=> git: do not set credential manager as post_install

bucket/cmder-full.json, bucket/cmder.json
When launched from the start menu shortcut, cmder starts in
`%SCOOP%\apps\cmder\current`, which is not ideal behaviour for a
terminal program. This patch makes the shortcut always start
in the home directory with the argument '/start'.
When started from the shim or directly, cmder starts in your
current directory anyway, which is expected behaviour.
=> cmder: shortcut to start in home dir (`%USERPROFILE%`)

bucket/k6.json
Fix link to github project for k6 since [acquired by Grafana Labs](https://github.com/grafana/k6/releases/tag/v0.33.0).
=> k6@0.33.0: Github link fix

bucket/go-jsonnet.json
Moved from scoop-extras to main bucket as instructed in https://github.com/lukesampson/scoop-extras/pull/5957
=> go-jsonnet: Add version 0.17.0

bucket/nvs.json
The current method (before this PR) adds a shim which delegates nvs to the `nvs.ps1` script. 
NVS actually needs to modify the current shell's PATH on-the-fly, so calling the nvs shim from shells other than PowerShell (cmd.exe, Git Bash) does nothing. The solution is to add nvs.cmd, nvs (bash script) and nvs.ps1 all to the PATH so that they can be called directly. This is what the MSI installer of NVS does too.
=> nvs: make it work in non-powershell shells

bucket/gsudo.json
Clear `gsudo` credentials cache on install / upgrade.
Related: gerardog/gsudo#99
Tested with:
```
C:\git\Main\bucket>scoop uninstall gsudo
Uninstalling 'gsudo' (1.0.1).
Removing shim for 'sudo'.
Unlinking ~\scoop\apps\gsudo\current
Removing ~\scoop\apps\gsudo\current from your path.
'gsudo' was uninstalled.
C:\git\Main\bucket>scoop install C:\git\Main\bucket\gsudo.json
Installing 'gsudo' (1.0.1) [64bit]
Loading gsudo.v1.0.1.zip from cache
Checking hash of gsudo.v1.0.1.zip ... ok.
Extracting gsudo.v1.0.1.zip ... done.
Linking ~\scoop\apps\gsudo\current => ~\scoop\apps\gsudo\1.0.1
Creating shim for 'sudo'.
Running post-install script...
'gsudo' (1.0.1) was installed successfully!
```
Also gsudo cache-clear verified ok.
=> gsudo: Add post install script (to clear gsudo credentials cache)

bucket/telegraf.json
The current Telegraf update logic is brittle and currently broken, this PR swaps the logic to use GitHub to detect releases and then a regex to extract the correct checksum. I have tested that this works correctly to automatically generate the last release from the previous one.
Fixes #2082.
Fixes #2191.
Fixes #2224.
Fixes #2286.
Fixes #2299.
Fixes #2441.
Fixes #2555.
Closes #2083.
Closes #2192.
Closes #2225.
Closes #2300.
Closes #2442.
Closes #2443.
Closes #2556.
=> telegraf: Fix update and hash logic

bucket/gdu.json
Disk usage analyzer with console interface written in Go
Ref: https://github.com/dodorz/scoop/blob/master/gdu.json
=> gdu@5.1.0: Add manifest

bucket/cygwin.json
The current implementation of the auto update hash logic for cygwin is brittle, as can be attested by the number of open issues, so should be swapped out for a stable implementation.
Fixes 43 issues and closes 6 PRs.
=> cygwin: Fix and update hash logic

bucket/python.json
This PR add the folders `Scripts` and `Lib\\site-packages` to the list to persist.
Resolve #1680, #772
Overhauls PR #1483
=> python: persist user installed libs and scripts

bucket/winfetch.json
This manifest already exists in the extras bucket. It wasn't very robust and/or popular when this tool was created, but it is now. So I'm thinking of promoting it to the Main bucket. Once this PR gets merged, I'll make a PR to the extras bucket to have it removed from there to avoid any duplication.
Here are some additional reasons why winfetch would fit nicely in the Main bucket:
- No pre/post install scripts
- CLI tool, no GUI
- No dependencies
- No binary blobs/executables (the manifest downloads a single script from GitHub which anyone can read) - this eliminates risk of any malware
- Fairly popular (375 stars, 12 contributors, which, frankly is way more than [some](https://github.com/pviotti/sayit) [of](https://github.com/arsham/rainbow) [the](https://github.com/evansmurithi/cloak) …
=> winfetch: Add v2.2.0

bucket/solidity.json
A manifest for this exists in the extras bucket. However, it is extremely out of date, the download URL gives 404, has no checkver and no autoupdate.
I've fixed those things and updated it to the latest version. I think this is another good fit for the Main bucket as:
- CLI only, no GUI
- Very popular (12000 stars, 415 contributors)
- No pre/post install script
- single binary
Once this gets merged, I'll send a PR to remove the manifest from extras.
=> solidity: Add version 0.8.7

bucket/kubeseal.json
> **Problem**: "I can manage all my K8s config in git, except Secrets."
> 
> **Solution**: Encrypt your Secret into a SealedSecret, which is safe to store - even to a public repository. The SealedSecret can be decrypted only by the controller running in the target cluster and nobody else (not even the original author) is able to obtain the original Secret from the SealedSecret.
> 
> The `kubeseal` utility uses asymmetric crypto to encrypt secrets that only the Kubernetes controller can decrypt.
Source https://github.com/bitnami-labs/sealed-secrets
=> kubeseal: Add version 0.16.0

bucket/mailhog.json
MailHog is an email-testing tool with a fake SMTP server underneath, similar to MailCatcher.
=> MailHog: Add MailHog v1.0.1

bucket/python.json, scripts/python/install-pep-514.reg
fix https://github.com/ScoopInstaller/Main/issues/2633
set all keys and values according to the official sample.
https://www.python.org/dev/peps/pep-0514/
sample:
```
HKEY_CURRENT_USER\Software\Python\PythonCore
(Default) = (value not set)
DisplayName = "Python Software Foundation"
SupportUrl = "http://www.python.org/"
HKEY_CURRENT_USER\Software\Python\PythonCore\3.6
(Default) = (value not set)
DisplayName = "Python 3.6 (64-bit)"
SupportUrl = "http://www.python.org/"
Version = "3.6.0"
SysVersion = "3.6"
SysArchitecture = "64bit"
HKEY_CURRENT_USER\Software\Python\PythonCore\3.6\Help\Main Python Documentation
(Default) = "C:\Users\Me\AppData\Local\Programs\Python\Python36\Doc\python360.chm"
DisplayName = "Python 3.6.0 Documentation" …
```
=> python: Full PEP514 registration

bucket/dnscrypt-proxy.json
Because of https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.0.45, persisting a config folder instead of files should be a better choice to improve compatibility. And this allows to user create their own custom configuration files besides the default ones by just putting them into the `config` folder.
=> dnscrypt-proxy: Fix configuration files persistence

bucket/prs.json
Add a suggestion for `extras/vcredist2015`, required but apparently unavailable on fresh systems.
=> prs: Add extras/vcredist2015 suggest

bucket/rink.json
Version 0.6.1, which is the latest version.
https://github.com/tiffany352/rink-rs
([taken from the criteria list](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket))
=> rink: Add version 0.6.1

bucket/macchina.json
A blazing fast system information pretty-printer. Like neofetch, but written in Rust!
=> macchina: Add version 1.1.6

bucket/ag.json
As mentioned is The Silver Searcher's Readme - https://github.com/ggreer/the_silver_searcher#windows - this fork (the one in this PR) builds and maintains a version of `ag` that is more optimized for Windows. The previous download link for `ag` in the Main bucket manifest just pointed to a repo that hosted builds; it didn't host any `ag` source code. 
Actually, there are a lot more optimizations - a full list can be seen here - https://github.com/JFLarvoire/the_silver_searcher#specificities-of-this-fork
The commandline parameters are exactly the same - so this PR won't bring any breaking changes.
=> ag: Update to version 2.2.4

bucket/uncrustify.json
λ  scoop install uncrustify
Installing 'uncrustify' (0.73.0) [64bit]
Loading uncrustify-0.73.0_f-win64.zip from cache
Checking hash of uncrustify-0.73.0_f-win64.zip ... ok.
Extracting uncrustify-0.73.0_f-win64.zip ... done.
Linking ~\scoop\apps\uncrustify\current => ~\scoop\apps\uncrustify\0.73.0
Creating shim for 'uncrustify'.
Can't shim 'uncrustify.exe': File doesn't exist.
=> uncrustify: Fix path

bucket/git-istage.json
The PowerShell script requires a backtick before the `$` to avoid evaluation of the variable when the script is created.
=> git-istage@0.3.33: Fix environment variable checking script

bucket/pwsh.json
PowerShell uses two installation wide profiles.
You can check them with:
`$PROFILE | Format-List * -Force`
And read about them here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1#the-profile-files
```
AllUsersAllHosts:  $dir\Profile.ps1
AllUsersCurrentHost:   $dir\Microsoft.PowerShell_profile.ps1
... two user profiles ...
```
Those two files should be persisted.
=> pwsh: persist global profiles

bucket/avr-gcc.json
Fixes broken avr-gcc package and updates it to use the official [Zak Kemble](https://blog.zakkemble.net/avr-gcc-builds/)'s repository which is updated regularly.
Fixes issues:
* https://github.com/lukesampson/scoop/issues/4371 (main scoop repo)
* https://github.com/tinygo-org/tinygo/issues/1323#issuecomment-850894969 (Tinygo)
```
$ scoop install avr-gcc.json
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'avr-gcc' (11.1.0) [64bit]
Loading avr-gcc-11.1.0-x64-windows.zip from cache.
Checking hash of avr-gcc-11.1.0-x64-windows.zip ... ok.
Extracting avr-gcc-11.1.0-x64-windows.zip ... done.
Linking ~\scoop\apps\avr-gcc\current => ~\scoop\apps\avr-gcc\11.1.0
Creating shim for …
```
=> avr-gcc: Update to 11.1.0

bucket/legit.json
Resolved https://github.com/ScoopInstaller/Main/issues/1247
"Depends" installs the mentioned manifest. This could be trouble some for other that had get `git` installet out of scoop or other variants such as `mingit`.
=> Updated "git" as depends on legit into suggest

bucket/sbcl.json
I extracted versions 2.0.0 and 2.1.9 with lessmsi and compared the structure.
```
❯ tree
C:.
├───sbcl2.0.0
│   └───SourceDir
│       └───PFiles
│           └───Steel Bank Common Lisp
│               └───2.0.0
│                   └───contrib
└───sbcl2.1.9
└───SourceDir
└───PFiles
└───Steel Bank Common Lisp
└───contrib
```
fixes #2714
=> sbcl: Fix extract_dir

bucket/helix.json
- Adding helix editor to main bucket
- Currently only supports 64bit architecture through GitHub releases
- Requested as by https://github.com/helix-editor/helix/issues/277
=> Helix: Add version 0.4.1

bucket/ffmpeg.json
Fix #2734
https://github.com/BtbN/FFmpeg-Builds/ deleted the build on `2021-09-22`. This fixes the problem.
=> ffmpeg@4.4-154: Fix url

bucket/vim-nightly.json, bucket/win-acme.json
Fix #2844
- vim-nightly : no more win32
- win-acme : path change
=> Correct autoupdate-fix for #2844

bucket/clink.json, bucket/concourse-fly.json, bucket/gawk.json, bucket/just.json, bucket/jx.json, bucket/k3d.json, bucket/lessmsi.json, bucket/macchina.json, bucket/mdcat.json, bucket/neovim-nightly.json, bucket/oh-my-posh3.json, bucket/pandoc.json, bucket/rink.json, bucket/rust-analyzer.json, bucket/s3deploy.json, bucket/tflint.json, bucket/vim-nightly.json, bucket/wasmtime.json, bucket/xmake.json, bucket/yq.json
**Update manifest for** 
* clink.json
* concourse-fly.json
* gawk.json
* just.json
* jx.json
* k3d.json
* lessmsi.json
* macchina.json
* mdcat.json
* neovim-nightly.json
* oh-my-posh3.json
* pandoc.json
* rink.json
* rust-analyzer.json
* s3deploy.json
* tflint.json
* vim-nightly.json
* wasmtime.json
* xmake.json
* yq.json
Tested (install / uninstall )
**Not updated :** 
* terraform-provider-ibm.json
Dependancy to version bucket. Not tested
=> Manifests update 11 01 21

bucket/rust.json
- Update 1.56.0 -> 1.56.1
[https://github.com/rust-lang/rust/releases/tag/1.56.1](https://github.com/rust-lang/rust/releases/tag/1.56.1)
[https://blog.rust-lang.org/2021/11/01/Rust-1.56.1.html](https://github.com/rust-lang/rust/releases/tag/1.56.1)
=> rust: Update to version 1.56.1

bucket/imagemagick.json
- Only update version when checksum is ready
- Use HDRI version as recommend (https://imagemagick.org/script/download.php#windows)
Known Issue:
Hash will be wrong while application is updated and checksum is not ready, and this will last for a few hours.
=> imagemagick: fix `checkver` and use HDRI version

bucket/imagemagick.json
The manifest now downloads the full installer and unpacks it rather than the portable version. It also adds the environment variables and the installation folder to the path. This allows other programs such as Python Wand to find the programs and libraries for their own use. If further environment variables are missing, they can be added from this list: https://imagemagick.org/script/resources.php#environment. The bundled ffmpeg was unused in the portable version but as the manifest now adds the installation directory to the path, the outdated ffmpeg is renamed so that users can continue using the up-to-date ffmpeg downloaded by scoop.
=> ImageMagick - includes DLLs for programming APIs

bucket/pelook.json
[pelook](http://bytepointer.com/tools/index.htm#pelook) is an information tool for 32 and 64 bit Windows EXE, DLL, driver and OBJ files (PE/COFF images). This tool is suitable for reverse engineers or anyone needing to delve into the internals of Windows PE files.
=> pelook: Add version 1.73

bucket/git.json
The default setting for `credential.helper` is `helper-selector` in the Git Portable version. We don't set it to `manager-core` automatically, as it would possibly overwrite an existing user config. 
Thus, this PR adds a note about how to set the `credential.helper` to `manager-core` when installing Git.
Resolves #2894
=> git: Add note for setting GCM Core

bucket/rclone.json
Closes #1634.
Also, I notice many manifests that utilizes the similar tech often omit the `-ItemType File` part, which results in creating an empty directory instead of file. So I decide to put it to guarantee a file, regardless of PowerShell's default.
=> Persist rclone.conf in application directory for portability

bucket/oracle-instant-client.json
Created an app manifest for the Oracle Instant Client. While the `autoupdate` appears to work for the latest version, it's unclear if Oracle's URLs will remain in those formats.
Additionally, at the very least, the `suggest` will need to be manually updated if it changes. For example, currently from the download page (https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html):
> The 19.3 Basic package requires the Microsoft Visual Studio 2017 Redistributable.
=> oracle-instant-client: Add version 21.3.0.0.0

bucket/clink-completions.json, bucket/clink-flex-prompt.json
**Clink**
[Clink](https://chrisant996.github.io/clink/) is an extension framework which incorporates GNU Readline style editing in cmd.exe. It is currently internally used by the popular terminal package [Cmder](https://cmder.net/). The manifest for Clink is already present in Main - https://github.com/ScoopInstaller/Main/blob/master/bucket/clink.json
**Clink Completions**
This provides programmatic completions for various external programs leveraging the Clink framework. This is also used internally by Cmder.
**Clink Flex Prompt**
This is a Clink port of the popular Zsh prompt tool [Powerlevel10k](https://github.com/romkatv/powerlevel10k). This project is quite new, but since it is made by the author of Clink itself, I consider it trusted.
=> Add clink utils

bucket/busybox-lean.json
A manifest for busybox already exists here. However, that manifest creates over 150 aliases! Many of which conflict with Windows internal tools - `sort`, `date`, `whoami`, `echo`, `find`, `mkdir`, `rmdir`, `tar`, `uptime`, `time` etc.
Many users will find this annoying, because these shims will never actually get called (in both cmd and powershell, internal commands have the highest priority).
I have created this 'lean' manifest which does not create these shims. This will also be helpful in small containers/images (like Actions). I have added a note for the existing busybox manifest too.
=> busybox-lean: Add version 4487-gd239d2d52

bucket/fselect.json
> fselect: Find files with SQL-like queries
> https://github.com/jhspetersson/fselect
Relates to #282
=> fselect: Add version 0.7.7

bucket/fossa.json
Since fossa team has migrated to fossa-cli repository for all code development, and releases. This PR changes, the release location, such that scoop user can get the latest releases.
=> fossa: Add au.hash and update to 3.0.0

bucket/neovim-nightly.json, bucket/neovim.json
Ref: https://github.com/neovim/neovim/commit/7bd6f12b3edd5c42956034b2f1c8a9ea14b9bcdc
- Fix https://github.com/ScoopInstaller/Main/issues/2948
- Fix https://github.com/ScoopInstaller/Main/issues/2955
=> neovim-nightly: Remove 32bit and add au.hash

bucket/sget.json
Home: https://github.com/sigstore/cosign#sget
A subcommand from [Cosign](https://github.com/sigstore/cosign) for safer, automatic verification of signatures and integration.
=> sget: Add version 1.3.1

bucket/gcc.json
Change to [WInLibs](https://winlibs.com/) build and update to 11.2.0
Fix #1752 and close #1761
=> gcc: Use WinLibs build and update to 11.2.0

bucket/scrcpy.json
Closes #2988
But unsure why the excavator run didn't pick up the update, any ideas?
=> Update scrcpy to v1.20

bucket/freepascal.json
- Closes #844 
Providing definition file that will allow scoop install `freepascal` compiler (FPC) 
Thanks to https://github.com/shytikov for contribution
=> freepascal: Add version 3.2.2 #845

bucket/kafka.json
Closes #2987 
Deprecated file has been removed
https://issues.apache.org/jira/browse/KAFKA-8405
=> kafka: remove preferred replica election

bucket/oh-my-posh3.json
* Update to version 6.11.2
* Change url, because the filename on oh-my-posh release page has changed from `posh-windows-wsl-amd64.7z` to `posh-windows-amd64.7z` since [v6.9.0 release](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v6.9.0)
=> oh-my-posh3: Update to version 6.11.2 and fix url

bucket/pandoc.json
This is juts an update for the Pandoc manifest so that 2.16.2 is used. 
Current 2.16 is already two versions behind. 
Thanks
=> update pandoc manifest

bucket/get-iplayer.json
Supersedes https://github.com/ScoopInstaller/Extras/pull/3812
This adds [get_iplayer](https://github.com/get-iplayer/get_iplayer/), a tool for downloading TV and radio programmes from BBC iPlayer and BBC Sounds.
NOTES:
* The package has `shortcut` because the installer of **get_iplayer** creates shortcuts too.
* The "profile directory" [can only be specified at runtime](https://github.com/get-iplayer/get_iplayer/wiki/prefs). Therefore I use alternative batch files (`scoop_get_iplayer.cmd`, etc.) to do that.
* I tested the app by `get_iplayer --pid=m0011rxw --type=radio`
* See [previous PR](https://github.com/ScoopInstaller/Extras/pull/3812) for more discussions/details.
=> get-iplayer: Add version 3.27.1

bucket/fd.json
In the latest release of fd, the binary was moved into a subdirectory `fd-v$version-x86_64-pc-windows-msvc`, this PR adds `extract_dir` to fix that. This is basically the same as #2773.
Closes https://github.com/ScoopInstaller/Scoop/issues/4542
=> fd@8.3.0: Fix missing fd.exe

bucket/ffmpeg-nightly-shared-vulkan.json, bucket/ffmpeg-nightly-shared.json, bucket/ffmpeg-nightly-vulkan.json, bucket/ffmpeg-nightly.json, bucket/ffmpeg-shared.json, bucket/ffmpeg.json
close #2611 
close https://github.com/ScoopInstaller/Scoop/issues/4473
This is a workaround for the issue mentioned in https://github.com/ScoopInstaller/Main/issues/2611.
(ffmpeg has problem handling arguments containing `:` if `ffmpeg.ps1` is involved)
Also see upstream issue (closed by the maintainer of *ffmpeg*) : https://trac.ffmpeg.org/ticket/9398
=> ffmpeg: Remove .ps1 shims after installation

bucket/qemu.json
Got this error when updating `qemu`
```
App:         main/qemu
URL:         https://qemu.weilnetz.de/w64/qemu-w64-setup-20211125.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    44b5857f48d26c28bb90073358ba5de28ab7dee9811dca954b3c20dcc7148475
Actual:      c4ab32703d3fb4ce79ecd90b23f41f01ab0602969fad9951544b9ffbf5fb530c
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=qemu%406.2.0-rc2%3a+hash+check+failed
```
changing hash should fix it
=> qemu 6.2.0-rc2: fix hash

bucket/unrar.json
`unrar` is in 6.02, the last stable version of RAR.
6.10 is the beta version.
=> unrar: Correct version

bucket/diffsitter.json
`diffsitter` creates semantically meaningful diffs that ignore formatting differences like spacing. It does so by computing a diff on the AST (abstract syntax tree) of a file rather than computing the diff on the text contents of the file.
=> Add diffsitter 0.6.7

bucket/sourcegraph-cli.json
I created an app for [SourceGraph CLI](https://github.com/sourcegraph/src-cli), a command-line interface for interacting with [SourceGraph](https://about.sourcegraph.com/). I thought it fit the [criteria for being included here](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket), let me know if you think otherwise or have any input on the app itself. The only complex part was the `hash` regexp for `autoupdate`, but I think I got it right and [tested it according to the instructions](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#testing-and-running-autoupdate)
=> Add sourcegraph-cli to bucket

bucket/win-acme.json
Update manifest version and fix auto-update field ( revert to matchHead version variable)
Closes #XXXX
=> win-acme: update to version 2.1.20.1185 & fix autoupdate field

bucket/postgrest.json
On 2021-11-26 was a 9.0.0 release.
- It seems that this version wasn't picked up for the autoupdate
- I spotted release artifact file contains an additional directory path: `"artifacts\\postgrest-windows-x64"`. It's a breaking change from previous release 8.0.0
- In original manifest there was `depends` section with `postgresql` entry. While I agree it's overkill I'd suggest at least to put `postgresql` to `suggest` section as demonstrated by this PR. Reason: postgrest really doesn't even produce any output and exits immediately without libpq.dll on PATH. This can lead to false assumption that program is broken
=> postgrest: Update to version 9.0.0

bucket/msys2.json
msys2 adds a shortcut to open a clang32 environment.
Closes #3048
=> msys2: Add shortcut for clang32 environment

bucket/resharper-clt.json
As announced [here](https://blog.jetbrains.com/dotnet/2021/08/12/sunsetting-dupfinder-command-line-tool/), `dupfinder` is not part of the latest tools anymore.
=> Remove dupfinder binary

bucket/go-containerregistry.json
`crane` and `gcrane` are tools for interacting with remote images and registries.
Lot of useful recipes could be found here https://github.com/google/go-containerregistry/blob/main/cmd/crane/recipes.md
=> go-containerregistry: Add version 0.7.0

bucket/libxml2.json
[Libxml2](http://xmlsoft.org/) is the XML C parser and toolkit developed for the Gnome project. (but usable outside of the Gnome platform)
=> libxml2: Add version 2.9.3

bucket/openssl-mingw.json, bucket/openssl.json
Since v3.0.0 OpenSSL is published under Apache License 2.0
Announcement:
https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/
Relates to #516
=> OpenSSL: license is now Apache-2.0

bucket/diffutils.json
The latest Win32 build is 3.6 (check here https://packages.msys2.org/package/mingw-w64-x86_64-diffutils)
Closes #2933
=> diffutils: Use win32 builds

bucket/ncspot.json
Update from `0.9.0` to `0.9.3`. Add `x86_64` to urls.
=> ncspot: Update to version 0.9.3

bucket/binutils.json, bucket/gawk.json
Note: Starting from 2021, packages from ezwinports require libgcc DLL, which has to be downloaded separately.
=> binutils: Add version 2.37

bucket/libvips.json
Closes #3030.
There is an arm64 build for libvips. Should we add it for Shovel and future Scoop?
=> libvips: Add version 8.12.1

bucket/hopp-cli.json
Fixes #3092.
Relates to #1573.
=> hopp-cli: Add version 0.0.7

bucket/nvm.json
Checking hash of nvm-noinstall.zip ... ERROR Hash check failed!
App:         main/nvm
URL:         https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-noinstall.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    03fdea18df83704d0cc3efc1963b4705
Actual:      20c6eb074c1e1b906acc9e0a32b48f7e
=> nvm hash conflict

bucket/openssl-mingw.json
Update `OPENSSL_CONF` env. variable, location of `openssl.cnf` was moved to the `ssl/` folder.
=> openssl-mingw: Updated openssl.cnf location

bucket/postgresql.json
On most linux distros, you can just install postgresql-dev from whatever package manager.
This PR hopes to replicate that process but for Windows instead, as I believe Scoop can really pave the way for Windows development.
The new env variables provded:
* PG_LIB_DIR
* PG_INCLUDE_DIR
=> Add PG_LIB_DIR and PG_INCLUDE_DIR env vars

bucket/neofetch.json
Many windows usernames contain spaces or single quotes/apostrophe. I accidentally have an apostrophe (') in my username. As a result neofetch fails to run as mentioned in detail [here](https://github.com/dylanaraps/neofetch/issues/2002#issue-1084846469)
I discovered that the fix to this issue is to surround the path of the neofetch script being passed as an argument to bash.exe in double-quotes. This would escape spaces and single quotes in username. Windows does not allow double quotes or backslashes in usernames, so there is no need to consider those.
This is the updated working script: https://pastebin.com/J0zTeNAw
I tried to escape my double quotes in the json file with backslashes, please check if it corresponds to my intent.
Closes [#2002 in …
=> Escape single quotes and spaces in the path of neofetch in "pre_install" property

bucket/ffmpeg-shared.json
Closes #XXXX
Relates to #3113
Let me know if you want GitHub download URL instead
```
PS C:\Users\LazyGeniusMan\scoop-bucket> scoop install ffmpeg-shared
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'ffmpeg-shared' (4.4.1) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: aa7d1c|OK  |   123KiB/s|C:/Users/LazyGeniusMan/scoop/cache/ffmpeg-shared#4.4.1#https_www.gyan.dev_ffmpeg_builds_packages_ffmpeg-4.4.1-full_build-shared.7z
Download: Status …
```
=> ffmpeg-shared@4.4.1: Switch to mirrors

bucket/ffmpeg.json
Closes #3113 
Let me know if you want GitHub download URL instead
```
PS C:\Users\LazyGeniusMan\scoop-bucket> scoop install ffmpeg
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'ffmpeg' (4.4.1) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 3e2dd1|OK  |   107KiB/s|C:/Users/LazyGeniusMan/scoop/cache/ffmpeg#4.4.1#https_www.gyan.dev_ffmpeg_builds_packages_ffmpeg-4.4.1-full_build.7z
Download: Status Legend:
Download: (OK):download …
```
=> ffmpeg@4.4.1: Switch to mirrors

bucket/b2.json
This adds the Backblaze B2 CLI (`b2`) which can be found here:
https://www.backblaze.com/b2/docs/quick_command_line.html
It is licensed as MIT:
https://github.com/Backblaze/B2_Command_Line_Tool/blob/master/LICENSE
=> b2: Add version 3.2.0

bucket/janet.json
Adds Janet programming language.
_Janet is a functional and imperative programming language and bytecode interpreter. It is a lisp-like language, but lists are replaced by other data structures (arrays, tables (hash table), struct (immutable hash table), tuples). The language also supports bridging to native code written in C, meta-programming with macros, and bytecode assembly. There is a REPL for trying out the language, as well as the ability to run script files. This client program is separate from the core runtime, so Janet can be embedded in other programs._
=> janet: Add version 1.19.2

bucket/mosh-client.json
No autoupdate because:
- mosh hasn't had a release in 5 years - https://github.com/mobile-shell/mosh/releases
- the repository of the Windows port is archived
=> mosh-client: Add version 1.3.2

bucket/coursier.json
Coursier always create dummy `null` directory in %USERPROFILE%, I don't know why...
=> coursier: Persist cache and bin

bucket/tealdeer.json
Closes #3153 
https://dbrgn.github.io/tealdeer/usage.html recommends `tldr` as bin name.
=> tealdeer: Add version 1.5.0

bucket/scala.json
- Relates to https://github.com/ScoopInstaller/Versions/pull/382
- Removed bin entries for clis no longer in v3
- Autoupdate moved to github for simplicity
- Note for those who haven't migrated to v3 to use v2 in the Versions bucket (see PR linked above)
=> scala: update to version 3.1.0

bucket/openssl.json
My correction of OpenSSL license information in #3078 was not complete.
I forgot to remove the URL to the old OpenSSL 1.x license
We only need to declare the identifier since it is already known by Scoop.
=> openssl: fix license URL

bucket/miller.json
Miller is a command-line tool for querying, shaping, and reformatting data files in various formats including CSV, TSV, JSON, and JSON Lines.
Homepage: https://miller.readthedocs.io
GitHub: https://github.com/johnkerl/miller
Miller's config file could be set in `MLRRC` EnvVar, but from its docs:
> Any `.mlrrc` in your home directory or current directory is ignored whenever `MLRRC` is set in the environment.
So I don't persist it.
Closes #2245
=> miller: Add version 6.0.0

bucket/bazel-buildtools.json
buildifier is a tool for formatting bazel BUILD and .bzl files with a standard convention.
https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md
=> bazel-buildtools: Add version 4.2.5

bucket/tailwindcss.json
Tailwindcss is a very popular and highly productive CSS framework.
Recently they managed turning node dependent package into standalone utility.
This adds `tailwindcss.eze`.
References:
Web: https://tailwindcss.com
Blog about a standalone cli: https://tailwindcss.com/blog/standalone-cli
=> tailwindcss: Add version 3.0.15

bucket/dbmate.json
Dbmate is a lightweight standalone database migration tool, to keep your database schema in sync across multiple developers and your production servers.
Homepage: https://github.com/amacneil/dbmate
Popularity: 2.3K stars
=> dbmate: Add version 1.13.0

bucket/mpg123.json
mpg123 - Fast console MPEG Audio Player and decoder library
Homepage: https://www.mpg123.org
Status: Very mature
Close #2909
=> mpg123: Add version 1.29.3

bucket/autossh.json
close #1519
[AutoSSH](https://www.harding.motd.ca/autossh/) let the user automatically restart SSH sessions and tunnels, in case they drop.
**NOTES**
* checkver/autoupdate is not needed because the app has not been update since 2019.
**usage/help**:
```
> autossh
usage: autossh [-V] [-M monitor_port[:echo_port]] [-f] [SSH_OPTIONS]
-M specifies monitor port. May be overridden by environment
variable AUTOSSH_PORT. 0 turns monitoring loop off.
Alternatively, a port for an echo service on the remote
machine may be specified. (Normally port 7.)
-f run in background (autossh handles this, and does not
pass it to ssh.)
-V print autossh version and exit.
Environment variables are:
AUTOSSH_GATETIME    - how long must an ssh session be established
before we decide it really was established
(in …
```
=> autossh: Add version 1.4g

bucket/gpac.json
close #1246
**GPAC** ([homepage](https://gpac.wp.imt.fr/)) ([Wikipedia](https://en.wikipedia.org/wiki/GPAC_Project_on_Advanced_Content)) is a multimedia framework developed for research and academic purposes.
**NOTES**:
* More details can be found in [the project Wiki](https://github.com/gpac/gpac/wiki).
* **suggest**: The installer is bundled with *VCRedist 2015*. Since [VCRedist2022 covers the feature of 2015-2022](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), I put `vcredist2022` in suggest.
=> gpac: Add version 1.0.1-rev0

bucket/chkcpu.json
close #1672
[CHKCPU](http://web.inter.nl.net/hcc/J.Steunebrink/chkcpu.htm) is a tool that checks CPU Vendor, Model, Internal speed, and L1 cache mode settings.
**NOTES**:
* **checkver/autoupdate** is not needed because the last update was in 2017.
* **license**: See http://web.inter.nl.net/hcc/J.Steunebrink/chkcpu.htm
```
DOS version: CHKCPU v1.26
Win32 version: CHKCPU32 v2.14
Both programs are dated 06/06/2017, have the same update status regarding the CPU model data, and they are both freeware.
```
* About `chkcpu32.bat`:
- The manual says `CHKCPU32.BAT  ;a batch file for easy use of the program`
- The content is:
```
@echo off
if exist chkcpu32.exe goto run
goto error
:run
chkcpu32.exe /v
goto done
:error
@echo  =====================================================
@echo  = ERROR: The …
```
=> chkcpu: Add version 2.14

bucket/libavif.json
close #2640
**libavif** ([homepage](https://github.com/AOMediaCodec/libavif)) ([Wikipedia](https://en.wikipedia.org/wiki/AVIF#Support)) is tool and library for encoding and decoding AV1 video streams (.avif).
**NOTES**:
* `avifdec.exe` and `avifenc.exe` does not depend on the library (`.lib` files).
However, I think it won't hurt to include them as well, in case that some users may need to develop their programs using the headers and the library. (It is relatively small compared to the binaries, takes only about 100KB)
=> libavif: Add version 0.9.0

bucket/lxc.json
@rashil2000 here is a manifest derived from the sed one using chocolatey as a source.
Some thoughts I had though:
- ~~I'm not sure how the hash regex in autoupdate is supposed to work, there is a hash on the html of the page but it seems to be the hash for `lxc.exe` and some other files rather than the nupkg archive itself. Since this also seemed to be the case for sed as well I left it intact.~~
I was looking in the wrong place 😅 all's good there.
- `lxc.exe` stores its configuration data and files in `~\.config/lxc` when necessary - is there an example of how I can easily persist a directory like that while keeping any potential existing user data from other installs?
Closes #1668
=> lxc: Add version 4.22

bucket/cosign.json
This PR fixed the incorrect checksum calculated for Cosign.
Relates to https://github.com/ScoopInstaller/Scoop/issues/4688
=> cosign: Fix hash

bucket/ninja-kitware.json, bucket/ninja.json
Closes #3243 
Note: ninja (Existing and this fork) provide 64-bit builds only but the manifests don't use `architecture`.
=> ninja-kitware: Add version 1.10.2.g51db2.kitware.jobserver-1

bucket/cosign.json, bucket/sget.json
This PR updates the cosign and sget hash regex patterns to use multiline mode.
=> cosign: Fix hash regex & sget: Fix hash regex

bucket/mongodb.json
This PR:
- Updates the checkver URL. The existing checkver URL ( http://downloads.mongodb.org.s3.amazonaws.com/current.json ) has SSL issues (missing CN). 
- Changes the jsonpath to a regex to restrict the matched versions to stable releases only. Unfortunately I couldn't write a valid jsonpath to do the same.
Closes #3259
=> MongoDB stable only

bucket/scrcpy.json
- New icon was recently made for scrcpy but it was only released as png so could not be added to shortcut
- Now it is included in exe as an ico: https://github.com/Genymobile/scrcpy/commit/cfcbc2ac218612b2e9d2322ceb98ec99d7cd9381
=> scrcpy: add icon to shortcut

bucket/gtypist.json
gnu typist, also known as gtypist, is a typing tutor helps improving type skill.
=> gtypist: Add version 2.9.5

bucket/rustup-msvc.json, bucket/rustup.json
compared to rustup-msvc, we should ensure the host to be `gnu` with this.
Closes #XXXX
=> rustup: Explicitly set toolchain host

bucket/gron.json
gron: Make JSON greppable! 
gron transforms JSON into discrete assignments to make it easier to grep for what you want and see the absolute 'path' to it. It eases the exploration of APIs that return large blobs of JSON but have terrible documentation.
=> gron: Add version 0.6.1

bucket/shadowsocks-rust.json
Content of <https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.13.1/shadowsocks-v1.13.1.x86_64-pc-windows-msvc.zip.sha256>:
```text
35DB8D121B4EC2F54803790E89636AED52DA37A35A9BB1FEE99CC87E9A9E1051  shadowsocks-v1.13.1.x86_64-pc-windows-msvc.zip
```
=> shadowsocks-rust@1.13.1: Fix hash

bucket/pget.json
A command-line utility like wget but with parallel requests.
No persist and no depends.
=> pget: Add version 0.1.1

bucket/rcc.json
closes https://github.com/ScoopInstaller/Extras/issues/7986
[RCC](https://robocorp.com/docs/rcc/overview) is a set of tooling that allows you to create, manage, and distribute Python-based self-contained automation packages - or robots as we call them.
**NOTES**:
* The app is built in **64-bit**.
* persist is not needed because config is saved in project files (which can be created in *current working directory* by `rcc create`)
=> rcc: Add version 11.5.5

bucket/oh-my-posh.json
Based on @JanDeDobbeleer scoop install manifest and redirect/rename, `oh-my-posh3` is now `oh-my-posh`. 
Reference:
https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json
Closes #3321
Relates to #1843
=> oh-my-posh3@7.22.0: rename oh-my-posh3 to oh-my-posh

bucket/castxml.json
Closes https://github.com/ScoopInstaller/Main/issues/3318
**Nodes:**
- No need for persistence
- I am not sure it is possible to implement `autoupdate`, since the download url contains a GUID.
- It is only 64 bit.
=> castxml: Add version 0.4.4

bucket/zoxide.json
Each user should have their own database, and if zoxide is installed globally, it fails to write to the data directory when not running as admin, so the default value set by zoxide (`$Env:APPDATA`) is already ok.
=> zoxide: Remove `env_set` and `persist`

bucket/openssl.json
Required for OpenSSL to locate various modules (aka. providers).
Closes #3335
=> openssl: Set OPENSSL_MODULES environment variable

bucket/dapr-cli.json
Update LICENSE to Apache 2.0
Closes #3346
Related: https://github.com/dapr/cli/commits/master/LICENSE
=> dapr-cli: Update LICENSE to Apache 2.0

bucket/podman.json
Update to version 4.0.2
static binaries name changed
Closes #3348
- [ x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> podman: Update to version 4.0.2

bucket/p4.json
The `Extras` bucket already provide `p4.exe` as part of `p4v.exe`, but it's not always desirable to install the GUI tools to access the CLI. This just adds the CLI by itself.
Closes #3218
=> p4: Add version 2021.2-2252059

bucket/goodbyedpi.json
closes https://github.com/ScoopInstaller/Extras/issues/8094
supersedes https://github.com/ScoopInstaller/Extras/pull/8096
[GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) is a tool to bypass Deep Packet Inspection systems found in many Internet Service Providers which block access to certain websites.
=> goodbyedpi: Add version 0.2.1

bucket/smartmontools.json
=> smartmontools: Fix update-smart-drivedb shim

bucket/waifu2x-ncnn-vulkan.json
Adds waifu2x-ncnn-vulkan version 20210521, a vulkan based image upscaling application.
Cli usage https://github.com/nihui/waifu2x-ncnn-vulkan#example-command.
Closes #3356
=> waifu2x-ncnn-vulkan: Add version 20210521

bucket/gitea.json
Fix broken regex that check against blog entry,
and change against Current version
Closes #XXXX
=> gitea: fix check version autoupdate regex 

bucket/simple-http-server.json
This PR updates simple-http-server to the latest version (0.6.1). Autoupdate doesn't work since release artifacts names have changed since current version 0.4.2.
=> Update simple-http-server to 0.6.1 (download URL changed)

bucket/bitwarden-cli.json, bucket/oh-my-posh.json, bucket/schemacrawler.json
Since https://github.com/ScoopInstaller/Scoop/pull/4619 is now in `master`, we can simplify these manifests.
=> update au.hash in response to Scoop#4619

bucket/ffmpeg-shared.json, bucket/ffmpeg.json
For ffmpeg to work with fonts correctly font folder is needed.
See https://web.archive.org/web/20200511024225/https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=2554
Closes #XXXX
=> ffmpeg: Persist font folder

bucket/apngasm.json
- Update to latest available binary but still not up-to-date (this version released in 2014!)
- No checkver because no Windows binaries are available for 3.3 and up
- I opened an issue about it in the repo here: https://github.com/apngasm/apngasm/issues/99
=> apngasm: update to version 3.1.0

bucket/avrdude.json
- Move homepage to GitHub page, where development has moved to from https://savannah.nongnu.org/projects/avrdude/, but releases are still there
- Old homepage was a fork that hasn't been updated since 2020
- Couldn't find different releases for 32/64bit although I can see they are being built here: https://github.com/avrdudes/avrdude/actions/runs/1974679826 (jobs on the left hand side include mingw32 and mingw64)
- `avrdude.conf` should not be persisted as it is not for user customised prefs
=> avrdude: update to version 6.4

bucket/atomicparsley.json
- Old version was very old - released in 2006 and hasn't been updated since on Sourceforge
- Old version had a critical (!!) severity vulnerability - https://nvd.nist.gov/vuln/detail/CVE-2021-37232
- This fork has been updated recently and is linked to from Sourceforge discussion as the current active fork (& it is used by Homebrew)
- This release is now 64bit only
=> atomicparsley: update to v20210715.151551.e7ad03a

bucket/crc.json
- Relates to Excavator failure at https://github.com/ScoopInstaller/Main/runs/5534119474?check_suite_focus=true#step:3:227
- Releases have been moved from GitHub to their website
=> crc: update to version 1.40.0, new checkver

bucket/bind.json
- Relates to 404 in Excavator: https://github.com/ScoopInstaller/Main/runs/5534119474?check_suite_focus=true#step:3:196
- Also adds note about 9.16.x being the last version of BIND for Windows (checkver was failing because the latest version has no Windows release)
=> bind: update to version 9.16.26, add notes

bucket/1password-cli.json
This PR updates 1password-cli to v2.0.0. Note: v2 is a major release and changes command line API completely: https://developer.1password.com/docs/cli/upgrade/#step-2-update-your-scripts
=> Update 1password-cli to version 2.0.0

bucket/coq.json
- Relates to Excavator update available - https://github.com/ScoopInstaller/Main/runs/5534119474?check_suite_focus=true#step:3:228
- No autoupdate because no stable file names at the moment, raised it as a problem here: https://github.com/coq/platform/issues/164#issuecomment-1067416021
=> coq: update to version 2022.01.0

bucket/cake.json
- Relates to Excavator error: https://github.com/ScoopInstaller/Main/runs/5534119474?check_suite_focus=true#step:3:202
- Adds note explaining what the user should do to upgrade
=> cake: remove autoupdate because no longer updated

bucket/argo.json
- Relates to Excavator error: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:196
- Simplify by removing pre_install because they no longer release the exe without an extension
=> argo: update to version 3.3.0

bucket/force.json
- Relates to Excavator failure: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:255
- No more 32bit release
- Added license
=> force: update to version 0.33.0

bucket/dafny.json
Relates to Excavator failure due to lack of hash in manifest: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:230
=> dafny: update to 3.5.0, add hash

bucket/gauche.json
Relates to Excavator failure due to patch release not being standard name: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:250
=> gauche: update to version 0.9.11-p1

bucket/hopp-cli.json
Relates to Excavator failure due to removal of 32bit release: https://github.com/ScoopInstaller/Main/runs/5606329917?check_suite_focus=true#step:3:261
=> hopp-cli: Update to version 0.0.8

bucket/poetry.json
- Use `install-poetry.py` instead of `get-poetry.py`
> Warning: The previous get-poetry.py installer is now deprecated, if you are currently using it you should migrate to the new, supported, install-poetry.py installer.
> 
> See: https://github.com/python-poetry/poetry#windows-powershell-install-instructions
=> poetry: Update manifest

bucket/memcached.json
Relates to Excavator log, checkver found update but no autoupdate in manifest: https://github.com/ScoopInstaller/Main/runs/5616285619?check_suite_focus=true#step:3:246
=> memcached: Update to v1.6.14, add autoupdate

bucket/avr-gcc.json
I'm in the process of moving my AVR-GCC packages from my website to GitHub and noticed that this project is referencing the soon to be removed files.
=> avr-gcc: Update download locations

bucket/doxygen.json
Relates to Excavator failure to get 32bit version as it has been removed: https://github.com/ScoopInstaller/Main/runs/5650708572?check_suite_focus=true#step:3:264
=> doxygen: Update to version 1.9.3, remove 32bit

bucket/azure-kubelogin.json, bucket/wrangler.json
This PR adds Azure Kubelogin which is required to authenticate with an AKS cluster.
=> azure-kubelogin: Add version 0.11.0

bucket/kapacitor.json
Relates to hash extraction failure due to change to sha256 and new layout: https://github.com/ScoopInstaller/Main/runs/5669304168?check_suite_focus=true#step:3:316
=> kapacitor: Fix hash extraction

bucket/mariadb.json
- Relates to Excavator checkver issue due to jsonpath retrieving a list of all stable versions rather than just the latest: https://github.com/ScoopInstaller/Main/runs/5682704169?check_suite_focus=true#step:3:276
- Remove 32bit as 10.6.5 was the last version with a 32bit release: https://mariadb.org/download/?t=mariadb&o=true&p=mariadb&r=10.6.5&os=windows&cpu=x86&pkg=msi
=> mariadb: Update to v10.7.3, fix checkver, remove 32bit

bucket/1password-cli.json
Add note to the 1password-cli manifest notifying about changes in command schema. Note contains link to the migration guide and informs about 1password-cli v1 is available in Versions bucket.
=> Add note to the 1password-cli manifest notifying about changes in command schema

bucket/knative.json
Relates to Excavator issue getting latest version due to change in release tagging: https://github.com/ScoopInstaller/Main/runs/5699973084?check_suite_focus=true#step:3:254
=> knative: Update to version 1.3.1, fix checkver

bucket/coq.json
Relates to https://github.com/coq/platform/pull/234#issuecomment-1079630937 - a request to fix the wrong license in Scoop's manifest.
I have included most of the licenses used by the packages that Coq Platform includes, see the list for the current version here: https://github.com/coq/platform/blob/2022.01.0/doc/PackageTable%7E8.14%7E2022.01.csv
I put the Proprietary license first because the package `coq-compcert` is licensed under the INRIA Non-Commercial License Agreement, which I link in the manifest.
=> coq: Fix license to include its components

bucket/sftpgo.json
Relates to Excavator failure due to change in file name of portable release: https://github.com/ScoopInstaller/Main/runs/5703245388?check_suite_focus=true#step%3A3%3A327=
=> sftpgo: Update to version 2.2.2, fix autoupdate

bucket/kustomize.json
Relates to Excavator not being able to find latest version, due to checkver not checking releases page: https://github.com/ScoopInstaller/Main/runs/5703245388?check_suite_focus=true#step%3A3%3A272=
=> kustomize: Update to version 4.5.3, fix checkver

bucket/rnr.json
Relates to Excavator autoupdate failing due to lack of 32bit release:https://github.com/ScoopInstaller/Main/runs/5703245388?check_suite_focus=true#step%3A3%3A320=
=> rnr: Update to version 0.4.0, remove 32bit

bucket/openresty.json
Relates to Excavator checkver failing: https://github.com/ScoopInstaller/Main/runs/5703245388?check_suite_focus=true#step%3A3%3A306=
=> openresty: Fix checkver

bucket/unison.json
fix link url for autoupdate
fix shims as excutables are now in a subfolder ./bin
ad shim for GUI (unison-gtk2.exe)
update to version 2.52.0
Closes #3446
- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> Fix unison auto update

bucket/xtensa-esp32-elf.json
- Relates to Excavator checkver not working: https://github.com/ScoopInstaller/Main/runs/5709628840?check_suite_focus=true#step%3A3%3A337=
- Added autoupdate hash extraction - is there a simpler way to not repeat the url?
=> xtensa-esp32-elf: Update to -patch3, fix checkver

bucket/sget.json
- Closes #3453
- Just checkver fix to see whether excavator picks up the latest update (1.6.0)
=> sget: Fix checkver

bucket/helix.json
They changed version tags from `vM.m.p` to `YY.MM` upon the release of `22.03` today.
=> helix: Update to 22.03 and align new tag style

bucket/mls-software-openssh.json
Relates to Excavator checkver not working due to unconventional patch naming: https://github.com/ScoopInstaller/Main/runs/5750847498?check_suite_focus=true#step:3:285
=> mls-software-openssh: Update to 8.9p1-1-v1, fix checkver

bucket/yosys.json
- Relates to Excavator unable to perform checkver: https://github.com/ScoopInstaller/Main/runs/5784628664?check_suite_focus=true#step:3:321
- It looks as if the site where Yosys was previously hosted has been hacked/bought in order to promote some online casinos: https://clifford.at/
- The download page previously looked like this: https://web.archive.org/web/20210622104453/http://www.clifford.at/yosys/download.html
- On the old download page, there was a GitHub link to https://github.com/cliffordwolf/yosys, which redirects to https://github.com/YosysHQ/yosys and links to their new homepage https://yosyshq.net/yosys/
- On their website you can find old links to Yosys' download page - https://yosyshq.net/yosys/download.html - which now says that Yosys is best downloaded as part of OSS CAD …
=> yosys: Remove autoupdate, add archive URL & outdated note

bucket/scaleway-cli.json
Relates to Excavator unable to update to 2.5.1: https://github.com/ScoopInstaller/Main/runs/5830137476?check_suite_focus=true#step:3:318
=> scaleway-cli: Update to version 2.5.1, fix autoupdate

bucket/bind.json
Add dig.exe to bin list for bind.json so it is searchable by `scoop search dig`. 
`dig` is a common tool used for advanced DNS lookup, it is part of `bind`, unless people know this, they might not know to install `bind`. Current `bind.json` adds bind `bin` path user's ENV, so no shim is necessary, this just make `dig` searchable.
Closes #XXXX
=> Add dig.exe to bin list for bind.json

bucket/px.json
Relates to Excavator unable to update because file name format changed: https://github.com/ScoopInstaller/Main/runs/5847467824?check_suite_focus=true#step:3:312
=> px: Update to version 0.6.1, fix autoupdate

bucket/cmder-full.json, bucket/cmder.json
If a Windows user has a name with spaces in it, `cmder` will fail to start.
=> cmder: handle spaces in %USERPROFILE%

bucket/dotter.json
- Relates to Excavator unable to autoupdate again... (see #3401)
- `$version` changed back to `v$version`
=> dotter: Update to version 0.12.10, fix autoupdate

bucket/7zip-helper-19.00.json, bucket/7zip19.00-helper.json
Related:
* https://github.com/ScoopInstaller/Extras/issues/8298
* https://github.com/ScoopInstaller/Scoop/issues/4647
* Also see [extras/winrar-helper](https://github.com/ScoopInstaller/Extras/blob/master/bucket/winrar-helper.json) manifest.
This adds a "helper package" that is only used for **extracting files in other packages**. It creates a specific shim named `7z19.00-helper.exe`, so that it will not affect existing installations of 7-zip.
=> (chore): Add 7-zip 19.00 helper package

bucket/haskell.json
Relates to Excavator error `Property 'name' not valid on JArray.` - https://github.com/ScoopInstaller/Main/runs/6003990163?check_suite_focus=true#step:3:263
=> haskell: Fix JSONPath in checkver

bucket/diff-so-fancy.json
It doesn't work yet but I'll be happy to have some help because this is my first formula.
I currently have the following error:
```
> diff-so-fancy
The system cannot find the path specified.
```
=> diff-so-fancy: Add version 1.4.3

bucket/mob.json
Relates to Excavator unable to extract hash: https://github.com/ScoopInstaller/Main/runs/6084790781?check_suite_focus=true#step:3:261
=> mob: Update hash extraction url

bucket/tor.json
Url has been updated to the most recent torbrowser version 11.0.10 per https://dist.torproject.org/torbrowser/ since 11.0.7 isn't offered anymore and the current download link 404s: https://dist.torproject.org/torbrowser/11.0.7/tor-win64-0.4.6.10.zip .
The underlying tor version is the same `0.4.6.10` but I get different file hashes (that probably should be verified).  
Updating this part of the url seems to be necessary around every three months, given torbrowser following the ESR release schedule, while keeping the three latest stable versions hosted:
https://gitlab.torproject.org/tpo/applications/tor-browser/-/wikis/Release-Schedule
https://wiki.mozilla.org/Release_Management/Calendar
https://dist.torproject.org/torbrowser/
Relates to #3304
=> tor: Update invalid download url (torbrowser version segment /11.0.7/ -> /11.0.10/)

bucket/ctop.json
Adds [ctop](https://github.com/bcicen/ctop) command-line utility
=> ctop: add version 0.7.7

bucket/zoxide.json
https://github.com/ajeetdsouza/zoxide#environment-variables
and `_ZO_DATA_DIR` should be set to $persist_dir, IMO
but i dont think data migration should be done via SCOOP, so i will not make a PR for this at the time.
=> zoxide: Update notes

bucket/aspell.json
closes #3481
[ASpell](http://aspell.net/) is a spellchecker commonly used with *emacs*.
**NOTES**:
* *ASpell* can work properly without installing "dependencies" such as `gcc-libs`, `gettext`, etc.
* *ASpell* requires dictionary files (`mingw-w64-x86_64-aspell-en-2020.12.07-1-any.pkg.tar.zst`) to run spell checks.
* We can test the package by:
```
Invoke-WebRequest 'https://github.com/ScoopInstaller/Scoop/raw/master/LICENSE' -OutFile 'license.txt' 
aspell check license.txt
```
=> aspell: Add version 0.60.8-2

bucket/coq.json
Relates to #3388 where checkver was removed because of the inconsistent release file names, now it has been restored since https://github.com/coq/platform/issues/164 was fixed. My checkver should get the latest Coq version available and shouldn't pick up any beta releases. Also added to the pre_install to remove `Uninstall.exe.nsis`.
=> coq: Update to version 2022.04.0, restore autoupdate

bucket/r.json, bucket/rtools.json
~The existing 4.1.3-win.exe link doesn't work (try it). This is the correct one.~
Update R and RTools to 4.2.x
- Closes #3532
- Closes #3544
=> r|rtools: Update to 4.2.x

bucket/trufflehog.json
Add TruffleHog (utility to find leaked credentials).
More info: https://github.com/trufflesecurity/trufflehog
=> trufflehog: Add version 3.4.3

bucket/android-clt.json
https://developer.android.com/studio/command-line/sdkmanager
"The sdkmanager tool is provided in the Android SDK Tools package (25.2.3 and higher) and is located in android_sdk/cmdline-tools/latest/bin/."
Closes #XXXX
=> fix sdkmanager path

bucket/sccache.json
This PR updates the version of sccache from v0.2.14, released on 2020-12-22, to v0.2.15, released on 2021-01-13.
There will likely be a PR soon for v0.3.0, but prebuilt binaries are not yet available on the GitHub release for that.
=> sccache: Update to version 0.3.0

bucket/algernon.json
Relates to Excavator unable to update due to change in released file name and tag with 'v': https://github.com/ScoopInstaller/Main/runs/6436788672?check_suite_focus=true#step:3:200
=> algernon: Update to version 1.13.0, fix autoupdate

bucket/ccache.json
Relates to Excavator unable to update due to filename change: https://github.com/ScoopInstaller/Main/runs/6485642942?check_suite_focus=true#step:3:207
=> ccache: Update to version 4.6.1, fix autoupdate

bucket/megatools.json
- Relates to Excavator unable to check for updates: https://github.com/ScoopInstaller/Main/runs/6521484107?check_suite_focus=true#step:3:262
- Fixed checkver and autoupdate
- Updated bin. Now all commands are in one binary e.g. `megatools ls` rather than `megals`
=> megatools: Update to v1.11.0.20220519, fix checkver

bucket/oh-my-posh.json
- notes: Link is outdated.
- env_set: Currently `Get-PoshThemes` is not working because `$env:POSH_THEMES_PATH` is not correctly set.
- persist: Allow themes to get updated.
=> oh-my-posh@7.85.4: update env_set and others

bucket/curl.json
This is a fix for error:
Extracting curl-7.83.1_2-win64-mingw.tar.xz ... Could not find 'curl-7.83.1-win64-mingw'! (error 16)
Closes #3600 
Closes #3593 
=> curl@7.83.1_3: Fix 'extract_dir'

bucket/tor.json
Looks like using https://archive.torproject.org for stable download links is the way to go ( https://github.com/ScoopInstaller/Main/pull/3514#issuecomment-1103957218 ), here's the corresponding PR, hashes check out on my end.
=> tor: Use archive.torproject.org for stable download links

bucket/ngrok.json
Closes #3603
This should probably be merged after https://github.com/ScoopInstaller/Versions/pull/536 as I added a note that refers to installing ngrok2 from the Versions bucket.
`v3` is unfortunately hardcoded in the manifest because it's part of the download page url, so it will need updating if there's ever a 4.x version.
=> ngrok: Update to version 3.0.3, fix checkver

bucket/git-lfs.json
The new update puts all files in a git-lfs-3.2.0 folder so I just added `extract_dir` property so things work.
Without this, it was causing an error while updating.
=> git-lfs@3.2.0: Fixed Can't create shim

bucket/qaac.json
Relates to Excavator unable to update (`$version` --> `v$version`): https://github.com/ScoopInstaller/Main/runs/6622488283?check_suite_focus=true#step:3:316
=> qaac: Update to v2.75, fix autoupdate

bucket/avr-gcc.json
* Fixes #3623
* Both `avr-gcc.exe` and `avr-gcc-$version.exe` exists in the package.
Although they are the same thing (SHA-256 is the same), I think `avr-gcc-$version.exe` exists for some reason.
We should keep it as it is, rather than just ignoring `avr-gcc-$version.exe`.
=> avr-gcc: Manually shim avr-gcc-$version.exe

bucket/forcebindip.json
* closes #1630
[ForceBindIP](https://r1ch.net/projects/forcebindip) is a tool that can bind any Windows application to a specific interface or IP address.
**NOTES**:
* There is an [existing manifest](https://github.com/batkiz/backit/blob/master/bucket/forcebindip.json) in a custom bucket.
* *autoupdate* is not needed because last update was in 2017.
=> forcebindip: Add version 1.32

bucket/ktunnel.json
* closes #3626
[KTunnel](https://github.com/omrikiei/ktunnel) is a CLI tool to expose your local resources to Kubernetes.
**NOTES**:
* **persist**: I cannot find any config file being produced after testing the app. Also, according to the app's **usage**, it looks like the app can work fine without any config file.
> https://github.com/omrikiei/ktunnel#-usage-
Expose your local machine as a service in the cluster
This will allow pods in the cluster to access your local web app (listening on port 8000) via http (i.e kubernetes applications can send requests to myapp:8000)
　　ktunnel expose myapp 80:8000
　　ktunnel expose myapp 80:8000 -r #deployment & service will be reused if exists or they will be created
> Inject to an existing deployment
This will currently only work for deployments with …
=> ktunnel: Add version 1.4.7

bucket/ect.json
Relates to Excavator unable to update due to change in download file name: https://github.com/ScoopInstaller/Main/runs/6666958615?check_suite_focus=true#step:3:237
=> ect: Update to version 0.9, fix autoupdate

bucket/kotlin-native.json
- Relates to Excavator unable to update: https://github.com/ScoopInstaller/Main/runs/6722657756?check_suite_focus=true#step:3:252
- Simplifies regex to pick up versions with or without dashes
=> kotlin-native: Update to v1.6.21, fix checkver

bucket/refreshenv.json
[refreshenv](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/redirects/RefreshEnv.cmd) is a script that provides a command to **refresh env variables** in command prompt **(cmd)**.
This script was created by the *Chocolatey* team, and it is "shipped with" Chocolatey. (`refreshenv` will be in PATH after you install Chocolatey)
This script is useful for *Scoop* users as well. For packages involving **env_add_path** (e.g. `gcc`, `perl`, `python`, ...), the changes would not be applied in the current session of **cmd**. *refreshenv* can be a solution to this problem.
**NOTES**:
* More information can be found in [this StackOverflow thread](https://stackoverflow.com/questions/171588/is-there-a-command-to-refresh-environment-variables-from-the-command-prompt-in-w).
=> refreshenv: Add version 2019.03.06

bucket/harfbuzz.json
**[HarfBuzz](http://harfbuzz.github.io/)** is a text shaping engine that supports OpenType and Apple Advanced Typography. 
According to [ReadMe](https://github.com/harfbuzz/harfbuzz#readme), it is used in Android, Chrome, ChromeOS, Firefox, GNOME, GTK+, KDE, LibreOffice, OpenJDK, PlayStation, Qt, XeTeX, and other well-known projects.
=> harfbuzz: Add version 4.3.0

bucket/ntfy.json
- [ x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
=> ntfy: Add version 1.25.2

bucket/hledger.json
Relates to Excavator unable to update due to change in file name: https://github.com/ScoopInstaller/Main/runs/6793470829?check_suite_focus=true#step:3:271
=> hledger: Update to version 1.26, fix autoupdate

bucket/hashcat.json
Relates to #2804 and [hashcat/hashcat/#2403](https://github.com/hashcat/hashcat/issues/2403)
Hashcat cannot be used as a system-wide installed executable. The user needs to cd into the directory hascat binary is in and invoke it from there. Otherwise they will get the following error:
```
./hashcat.hctune: No such file or directory
```
=> hashcat: add a wrapper batch script which will call the executable from the installation folder

bucket/ant.json
Import any extra libs persisted by the user in $persist_dir\lib, such as ant-contrib, that
are not part of the default ant install.
Closes #3662
=> ant@1.10.12: Persist user libs

bucket/pnpm.json
* fixes #3663
* This adds a **checkver script** that checks all release tags, and picks up the latest one (greatest version number).
* I think this is necessary because the "revert" has happened more than once. See [file history](https://github.com/ScoopInstaller/Main/commits/master/bucket/pnpm.json) for example.
* Furthermore, we should probably implement something like this in *Scoop* itself. For example, we can add a **match_all** switch under `checkver` that performs **version comparison** (using Powershell's *System.Version* data type) amongst all regex matches.
=> pnpm: Add checkver script that checks all release tags

bucket/wasmer.json
- Update `bin`
fixes:
```
❯ scoop install wasmer
Installing 'wasmer' (2.3.0) [64bit]
Loading wasmer-windows.exe from cache
Checking hash of wasmer-windows.exe ... ok.
Extracting wasmer-windows.exe ... done.
Linking ~\scoop\apps\wasmer\current => ~\scoop\apps\wasmer\2.3.0
Creating shim for 'wax'.
Creating shim for 'wapm'.
Can't shim 'bin\wapm.exe': File doesn't exist.
```
=> wasmer: Update manifest

bucket/pacparser.json
Add a new app manifest for the [pacparser](https://github.com/manugarg/pacparser) library which also includes a `pactester.exe` command line tool for testing proxy auto-config (PAC) scripts.
=> pacparser: Add version 1.4.0

bucket/nu.json
Nushell changed its Windows artifact naming and ZIP content strategy.
This PR adapts the manifest accordingly.
=> nu: Update to version 0.6.4

bucket/reviewdog.json
Adds [reviewdog](https://github.com/reviewdog/reviewdog) - Automated code review tool integrated with any code analysis tools regardless of programming language
=> reviewdog: Add version 0.14.1

bucket/stern.json
Stern development has moved from https://github.com/wercker/stern to https://github.com/stern/stern. This PR reflects this change.
Closes #3697
=> stern@1.21.0: switch from the abandoned repo to the current one

bucket/imagemagick-lean.json
Change download links to correct ones because it looks like urls have changed after looking on imagemagick website download links listed on imagemagick website
=> imagemagick-lean: fix download urls

bucket/jp.json
* closes #3694
**[jp](https://github.com/jmespath/jp)** is the command-line version of **JMESPath** (https://jmespath.org/).
**NOTES**:
* I tested the app by running this under Powershell:
```
'{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar[1]
```
The app outputs
```
"b"
```
as expected.
=> jp: Add version 0.2.1

bucket/yt-dlp.json
[Configuration file](https://github.com/yt-dlp/yt-dlp#configuration) for yt-dlp can be placed alongside the executable in addition to [youtube-dl's supported locations](https://github.com/ytdl-org/youtube-dl#configuration). This is especially usefull for portable installs like using Scoop. So this PR adds `yt-dlp.conf` as a persistent file
I have also removed `vcredist2010` from dependencies since yt-dlp no longer uses it. Let me know if you'd rather have this in a separate PR
=> yt-dlp: Persistant configuration file

bucket/zoxide.json
zoxide changed its Windows artifact naming in 0.8.2 release.
=> zoxide: Update to version 0.8.2 and fix download url

bucket/grep.json
Rename binary to `grep.exe` so that the filename that grep shows up is the same as its command.
Before:
After:
=> grep: Rename binary before shimming

bucket/sed.json
Same reason with https://github.com/ScoopInstaller/Main/pull/3717.
For sed, however, I'm not sure why it is showing the full path:
But I guess it's better than the latter.
=> sed: Rename binary before shimming

bucket/clash.meta.json
**[Clash.Meta](https://github.com/MetaCubeX/Clash.Meta)** is a fork of Clash ([main/clash](https://github.com/ScoopInstaller/Main/blob/master/bucket/clash.json)), a rule-based tunnel in Go.
**NOTES**:
* Currently the repo has **794 stars** and 4K forks.
* config location: `$Env:UserProfile\.config\clash`.
=> clash.meta: Add version 1.11.2

bucket/qrencode.json
Commonly used CLI utility to generate QR Codes from text.
=> qrencode: Add version 4.1.1

bucket/gitlab-runner.json
Closes #3757
adds:
1. write simply how to get your registration code
2. write about the current directory when you run `gitlab-runner install`
3. inform system-wide git is needed if you didn't specify user info (means use SYSTEM) when installing it
4. warn about the credential helper selector (but it's temporary: needed more info, especially when using SYSTEM user)
=> gitlab-runner@15.1.0: Update notes
