- bucket/tesseract-languages.json
- bucket/tesseract.json
ref and close: https://github.com/lukesampson/scoop/pull/3310
>  tesseract: Update to 4.1.0.20190314

- bucket/nssm.json
ref and close: https://github.com/lukesampson/scoop/pull/3266
> NSSM: Update to 2.24-103

- bucket/unxutils.json
ref and close: https://github.com/lukesampson/scoop/pull/3357
close: https://github.com/lukesampson/scoop/issues/3288
> UnxUtils: Add version 2007.03.01

- bucket/httping.json
ref and close: https://github.com/lukesampson/scoop/pull/3358
close: https://github.com/lukesampson/scoop/issues/3345
> HTTPing: Add version 2.5

- bucket/gallery-dl.json
close https://github.com/lukesampson/scoop/issues/3347
> gallery-dl: Add version 1.8.2

- bucket/osslsigncode.json
- Dup of lukesampson/scoop#3356
- Closes lukesampson/scoop#3356
> osslsigncode: Add version 1.7.1-1

- bucket/frp.json
- Closes lukesampson/scoop#3383
- Manifest fixed
- Added:
- Hashes
- Persist
- Fixed checkver
Co-authored-by: devdevdevdeep <dev@shenqisoft.info>
> Add frp version 0.27.0

- bucket/ffmpeg-shared.json
Hello,
I need the ddl libraries with ffmpeg, which are not provided in the stastic version, for Audacity.
> Add ffmpeg-shared version 4.1.3

- bucket/wget.json
- Close https://github.com/lukesampson/scoop/issues/3331
- Close https://github.com/lukesampson/scoop/issues/3365
- Close https://github.com/lukesampson/scoop/issues/3395
> wget: Fix hash

- bucket/cfr.json
- bucket/dokka.json
- bucket/zookeeper.json
Ref PR https://github.com/lukesampson/scoop/pull/3354
> Update depends and suggests for Oracle Java

- bucket/ziglang.json
- Added hash extraction, description
> ziglang: Move from extras

- bucket/llvm.json
- Closes lukesampson/scoop#3343
lukesampson/scoop#3342
Co-authored-by: Daan De Meyer <daan.j.demeyer@gmail.com>
> llvm: Add binaries instead of appending path

- bucket/avro-tools.json
This is my first contribution to Scoop, so please let me know if there is anything additional I need to do.
> avro-tools: Add version 1.8.2

- bucket/dark.json
ref: https://github.com/ScoopInstaller/Binary/pull/5
> dark: Update to 3.11.1 (Add DLLs)

- bucket/ghostscript.json
> ghostscript: Fix checkver and update to 9.27

- bucket/megatools.json
@r15ch13 - can you restore my write access within `ScoopInstaller` so that I may continue to push manifest fixes?
> megatools: Fix checkver

- bucket/smimesign.json
Current version links were also broken.
> smimesign: Update to version 0.0.13

- bucket/mro.json
- bucket/plex-server.json
- bucket/python.json
This should be merged immediately after https://github.com/lukesampson/scoop/pull/3432.
> Fix 'Expand-DarkArchive' args order

- bucket/duplicacy.json
> duplicacy: Fix au.url and hash

- bucket/acmesharp.json
Current download URL is broken.
> acmesharp: Update to version 0.9.1.326

- bucket/julia.json
`julia-installer.exe` is a NSIS installer.
> julia: Use installer.script instead of original installer

- bucket/tesseract-languages.json
- bucket/tesseract.json
Close #43, close #59, close #76
> tesseract: Fix hash, add post-install and fix hash in tesseract-languages

- bucket/exercism.json
> exercism: Modify url

- bucket/subinacl.json
subinacl is a tool from Microsoft Windows Resource Kits
> add subinacl

- bucket/omnisharp.json
> omnisharp: Fix hashes

- bucket/pdf2djvu.json
Move from 'extra' (https://github.com/lukesampson/scoop-extras/pull/2265)
> pdf2djvu: Move from 'extra'

- bucket/fontreg.json
Please let me know if there are any problems. Thanks.
> FontReg: Add version 2.1.3

- bucket/sox.json
It is a popular tool for audio processing just like ffmpeg for video (and audio, of course).
> Add sox (army knife for audio processing)

- bucket/python.json
All work fine, just for pithy。
> python: Change hash regex

- bucket/ack.json
Sorry, I thought I had tested this.
> ack: Fix autoupdate URL

- bucket/pandoc-crossref.json
- bucket/pandoc.json
Ref: https://github.com/lukesampson/scoop-extras/pull/2310
> pandoc: Move from 'extras'

- bucket/vim.json
> vim: Add 32bit support (fixes #113)

- bucket/v2ray.json
https://github.com/lukesampson/scoop-extras/pull/2314
> v2ray: Move from extras bucket

- bucket/dnscrypt-proxy.json
https://github.com/lukesampson/scoop-extras/pull/2315
> dnscrypt-proxy: Move from extras bucket

- bucket/xmake.json
> xmake: Fix 'extract_dir' and add 64bit

- bucket/xmake.json
Ref: https://github.com/xmake-io/xmake/issues/463
> xmake: Add back 'extract_dir' and add au.hash

- bucket/msival2.json
> msival2: Add version 5.0.18362.1

- bucket/unxutils.json
> unxutils: Fix homepage

- bucket/shortcut.json
Please let me know if there are any problems. Thanks.
> Shortcut: Add version 1.11

- bucket/autoit.json
autoit-script-editor: https://github.com/lukesampson/scoop-extras/pull/2289
Just likes DjVuLibre, it is used mainly as CLI tool, so put it here instead of `extras`.
> autoit: Add bins, shortcuts and suggestion

- bucket/potrace.json
> potrace: Fix checkver, add au.hash

- bucket/haskell.json
Updated version to 8.6.5, which doesn't seem to have a 32 bit version
> Update haskell to version 8.6.5 (by dropping 32bit support)

- bucket/perl.json
> perl: Add au.hash

- bucket/nano.json
Installs and runs fine locally
> nano: Update to 4.2-243 (manually)

- bucket/mtn.json
mtn is used to generate screenshots and thumbnails via the command-line
https://gitlab.com/movie_thumbnailer/mtn/wikis/home#showcase
> 📦 Add mtn app

- bucket/kafka-exporter.json
Moved from https://github.com/lukesampson/scoop-extras/pull/2267
> Add kafka-exporter for exporting Kafka stats to Prometheus

- bucket/chronograf.json
- bucket/influxdb.json
- bucket/kapacitor.json
- bucket/telegraf.json
Also add some auxiliary tools made by InfluxDB: [Chronograf](https://www.influxdata.com/time-series-platform/chronograf/), [Kapacitor](https://www.influxdata.com/time-series-platform/kapacitor/) and [Telegraf](https://www.influxdata.com/time-series-platform/telegraf/)
> influxdb: Add description and change url

- bucket/go.json
Failed to golang download, golang download address changed
> go: Fix download URL

- bucket/radare2.json
Directory struct changed in 3.6.0
> radare2: Fix 'extract_dir'

- bucket/maven.json
archive.apache.org was offline, switch to https://www.apache.org
> maven: Fix download url and au.hash

- bucket/dosbox.json
> dosbox: update to 0.74-3 & add autoupdate

- bucket/php.json
> Updated hashes

- bucket/monero-cli.json
> monero-cli: Add version 0.14.1.0

- bucket/php-nts.json
> php-nts: Fix hashes

- bucket/gifski.json
> gifski: Add version 0.8.5

- bucket/ccl.json
Close https://github.com/ScoopInstaller/Main/issues/205
@priyadarshan Should I rename those bin or add more  path to env?
> Add ccl 1.11.5

- bucket/mill.json
> mill: fix hash, fixes #226

- bucket/go.json
> Go: Update checkver

- bucket/cmake.json
> cmake: Update checkver

- bucket/stack.json
> stack: Add au.hash and fix hashes

- bucket/tor.json
https://github.com/lukesampson/scoop-extras/pull/2471
> Tor: Move from extra, add 64bit and portable

- bucket/git-with-openssh.json
> Add environment variable to git-with-openssh

- bucket/colortool.json
> colortool: Fix homepage (Fixes 279)

- bucket/pdfbox.json
Will add multi update after https://github.com/lukesampson/scoop/pull/3518 being merged.
> pdfbox: Add version 2.0.16

- bucket/php-nts.json
- bucket/php.json
Update PHP from 7.3.7 to 7.3.8.
Also, seems like [the current version](https://windows.php.net/downloads/releases/php-7.3.7-Win32-VC15-x64.zip) is not found.
> Update PHP versions

- bucket/spark.json
Ref: https://github.com/lukesampson/scoop-extras/pull/2545
> spark: Move from 'extras' and add au.hash

- bucket/rustup-msvc.json
- bucket/rustup.json
Also add `rustup-msvc` for stable-msvc toolchains.
> rustup: Add desc, mod url and fix license

- bucket/heroku-cli.json
https://github.com/lukesampson/scoop-extras/pull/2541
> Heroku-Cli: Move from extras

- bucket/mariadb.json
This download URL will not do redirection.
> mariadb: Add desc, fix au.hash and change url

- bucket/scrcpy.json
Closes https://github.com/ScoopInstaller/Main/issues/301
> Scrcpy: fix extract_dir

- bucket/rclone.json
> rclone: Use github URLs

- bucket/flac.json
> flac: Fix checkver/au.url due to 404

- bucket/sacad.json
Ref: https://github.com/lukesampson/scoop-extras/pull/2627
> sacad: Move from 'extras'

- bucket/s.json
Ref: https://github.com/lukesampson/scoop-extras/pull/2628
> s: Move from 'extras'

- bucket/python.json
See https://github.com/lukesampson/scoop/issues/2383#issuecomment-520114024
> Fix virtualenv creation bug

- bucket/fciv.json
https://github.com/lukesampson/scoop-extras/pull/2623
> fciv: move from extras

- bucket/gitea.json
Ref: https://github.com/lukesampson/scoop-extras/pull/2660
> gitea: Move from 'extras'

- bucket/coq.json
https://github.com/lukesampson/scoop-extras/pull/2622
> coq: move from extra

- bucket/bitwarden-cli.json
https://github.com/lukesampson/scoop-extras/pull/2681
> bitwarden-cli: move from extras

- bucket/azure-cli.json
- bucket/azure-functions-core-tools.json
- bucket/azure-ps.json
https://github.com/lukesampson/scoop-extras/pull/2682
> azure-cli, azure-ps, azure-function-core-tools: move from extras

- bucket/tunnel.json
Signed-off-by: Vishal Rana <vr@labstack.com>
> tunnel: update to version 0.3.2

- bucket/1password-cli.json
https://github.com/lukesampson/scoop-extras/pull/2546
> 1password: Add version 0.5.7

- bucket/gifski.json
- bucket/hashcat.json
- bucket/haxe.json
- bucket/helm.json
- bucket/hub.json
- bucket/hugo-extended.json
- bucket/hugo.json
- bucket/ie11webdriver.json
- bucket/imagemagick.json
- bucket/invoke-build.json
- bucket/jruby.json
- bucket/julia.json
- bucket/kotlin-native.json
- bucket/kotlin.json
- bucket/kubectl.json
- bucket/latex.json
- bucket/lcow.json
- bucket/leiningen.json
- bucket/less.json
- bucket/lessmsi.json
- bucket/libwebp.json
- bucket/lilypond.json
- bucket/make.json
- bucket/mediainfo.json
- bucket/mercurial.json
These are the last manifests in main without descriptions.
Descriptions pulled from https://github.com/ScoopInstaller/Main/pull/291/files#diff-49
> Add 25 descriptions

- bucket/cuda.json
Wondering why hash extract not work without au.hash.regex.
> CUDA: fix autoupdate

- bucket/latex.json
https://github.com/lukesampson/scoop/issues/3609
A temporary workaround before https://github.com/lukesampson/scoop/pull/3503 is merged...
> Latex: Fix env add path

- bucket/scrcpy.json
> scrcpy: Add shortcut for scrcpy-noconsole.exe

- bucket/cacert.json
Close https://github.com/ScoopInstaller/Main/issues/383
> cacert: remove au.hash

- bucket/sqlite.json
> SQLite: fix checkver

- bucket/flac.json
> Flac: fix checkver

- bucket/mongodb.json
> MongoDB: fix checkver

- bucket/links.json
> links: fix checkver

- bucket/chronograf.json
> chonograph: Fix hash (fixes #401)

- bucket/aliyun.json
include Alibaba Cloud commandline interface to the main bucket
> add aliyun-cli

- bucket/gifski.json
> gifski: Fix au.url

- bucket/neovim.json
Fix #416 
Fix #419 
Fix #423  
Fix https://github.com/lukesampson/scoop/issues/3641
> neovim: Fix hashes

- bucket/traefik.json
> traefik: Fix au.url

- bucket/bulk-rename-command.json
It redirects from `https` to `http`
> bulk-rename-command: Fix checkver and download.url

- bucket/httpstat.json
Hey,
First contribution. I felt like this tool fits the criteria for Main bucket.
See: https://github.com/davecheney/httpstat
> Add davecheney/httpstat

- bucket/jira.json
> jira: Fix download.url

- bucket/llvm.json
> llvm: Update to 9.0.0

- bucket/buck.json
- bucket/nunit-extension-nunit-project-loader.json
- bucket/nunit-extension-nunit-v2-driver.json
- bucket/nunit-extension-nunit-v2-result-writer.json
- bucket/nunit-extension-teamcity-event-listener.json
- bucket/nunit-extension-vs-project-loader.json
See #150 and https://chocolatey.org/blog/chocolatey-website-redesign
> Fix 6 checkvers due to chocolatey site redesign

- bucket/idris.json
> idris@1.3.2: Hash fix

- bucket/nunit-console.json
> nunit-console: Fix checkver

- bucket/erlang.json
Can it depends vcredist2013? Without vcredist2013 the installer can't work.
> Erlang: suggest vcredist2013

- bucket/dark.json
This is for https://github.com/ScoopInstaller/Binary/pull/9
> dark: Fix checkver

- bucket/fluxctl.json
I've created a package for [fluxctl](https://github.com/fluxcd/flux).
> Add fluxctl package

- bucket/deepstream.json
https://deepstream.io
The open realtime server, a fast and secure data-sync realtime server for mobile, web & iot
> Add deepstream package

- bucket/centrifugo.json
https://centrifugal.github.io/centrifugo/
Centrifugo is a language-agnostic real-time messaging server. Centrifugo supports at moment: Websocket and SockJS
> Add centrifugo package

- bucket/pyflow.json
[Pyflow](https://github.com/David-OConnor/pyflow) is a Python installation and package manager.
> add pyflow

- bucket/emitter.json
https://emitter.io/
Emitter is a real-time communication service for connecting online devices. The Publish-Subscribe messaging API is built for speed and security.
> emitter: Add version 2.678

- bucket/nu.json
> Nu will look for the plugins in your PATH on startup. While nu will have some functionality without them, for full functionality you'll need to copy them into your path so they can be loaded.
> nu: Add version 0.3.0

- bucket/yara.json
> Yara: Update to version 3.11.0-994 and fix au

- bucket/sonar-scanner.json
Added the [sonar-scanner](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/) package to compliment _SonarQube_.
> sonar-scanner: Add version 4.2.0.1873

- bucket/dependency-check.json
Add [dependency-check](https://www.owasp.org/index.php/OWASP_Dependency_Check) package.
> dependency-check: Add version 5.2.2

- bucket/gauge.json
Gauge (https://gauge.org/) is a light weight cross-platform test automation tool developed by  ThoughtWorks.
> Gauge: Add version 1.0.6

- bucket/nvm.json
nvm [has MIT license](https://github.com/coreybutler/nvm-windows/blob/master/LICENSE).
> nvm: Fix license

- bucket/jcli.json
Official Repo is https://github.com/jenkins-zh/jenkins-cli/
> jcli: Add a new cli

- bucket/butterflow.json
I had to use a slightly convoluted checkver because the release tags aren't equal to the version strings used in the file names.
**Copied from README:**
BF is a video manipulation tool that can:
1. Make **motion interpolated videos** (increase a video's frame rate by rendering intermediate frames based on motion using a combination of pixel-warping and blending).
2. Make **smooth motion videos** (do simple blending between frames).
3. Leverage interpolated frames to make **fluid slow motion videos**.
> Add butterflow

- bucket/enomic.json
- Closes lukesampson/scoop-extras#1906
Co-Authored-By: Thomas Sigdestad <tsi@enonic.com>
Co-Authored-By: Richard Kuhnt <r15ch13+git@gmail.com>
> enomic: Add version 1.0.9

- bucket/elm.json
> elm: update to version 0.19.1

- bucket/neko.json
> neko: update to version 2.3.0

- bucket/kubectxwin.json
https://github.com/lukesampson/scoop/issues/3510
- [kubectx](https://github.com/ahmetb/kubectx)
- [kubectxwin](https://github.com/thomasliddledba/kubectxwin)
> kubectxwin: Add version 0.1.1

- bucket/latex.json
> latex: Use arch-spec 'env_add_path'

- bucket/tesseract.json
> tesseract: Fix hashes

- bucket/ntop.json
add ntop, a htop-like system-monitor with Vi-emulation for Windows
> ntop: add ntop

- bucket/mysql-workbench.json
- Get rid of $matches usage for older versions installation
- Property sort
> mysql-workbench: Simplify manifest

- bucket/unison.json
This will add the famous Unison, a file-synchronization tool.
> unison: Add version 2.51.2

- bucket/jd-cmd.json
> jd-cmd: Update to version 1.0.0

- bucket/ravendb.json
Close #511
**RavenDB** ([homepage](https://ravendb.net/)) is a NoSQL database built on .NET Core.
Please let me know if there are any problems. Thanks.
> RavenDB: Add version 4.2.4

- bucket/awsSts.json
> awsSts: add awsSts

- bucket/subinacl.json
> subinacl: fix hash

- bucket/PowerSession.json
from https://github.com/lukesampson/scoop-extras/pull/2996
> PowerSession: Add version 1.1.0

- bucket/mdbook.json
This adds mdbook, which is a tool for making books from markdown files
> mdbook: Add version 0.3.5

- bucket/starship.json
Adds starship to Scoop.
Please let me know if anything is missing from the manifest. 👍
> starship: Add version 0.26.4

- bucket/helm.json
> helm: Update to version 3.0.0

- bucket/win-acme.json
> win-acme: Update to version 2.1.0.539

- bucket/nim.json
> nim: Add additional binaries

- bucket/purescript.json
> purescript@0.13.5: Fix hash

- bucket/azure-ps.json
> azure-ps@3.0.0.30818: Fix hash

- bucket/lua.json
- bucket/srlua.json
Close #576 
~~`autoupdate` is waiting for https://github.com/lukesampson/scoop/pull/3518~~
> lua: Add version 5.3.5 and srlua

- bucket/zstd.json
> zstd: Remove extract_dir

- bucket/selenium.json
> selenium: fix checkver

- bucket/uncrustify.json
> uncrustify: fix checkver

- bucket/kubeadm.json
- bucket/kubelet.json
Let me know if you have any questions!
> kubeadm,kubelet: Add versions 1.16.3

- bucket/velero.json
> velero: Add version 1.2.0

- bucket/tflint.json
> tflint: Add version 0.13.1

- bucket/gifski.json
From: https://github.com/ScoopInstaller/Main/issues/150
> gifski: Fix checkver

- bucket/gnirehtet.json
> gnirehtet: Update to version 2.4

- bucket/sops.json
> sops: Update to version 3.5.0

- bucket/azure-functions-core-tools.json
Close https://github.com/ScoopInstaller/Main/issues/601
> azure-functions-core-tools: fix decompress

- bucket/cmder-full.json
- bucket/cmder.json
> cmder: Update to version 1.3.13

- bucket/pandoc.json
fix https://github.com/lukesampson/scoop/issues/3766
> pandoc: remove extract_dir

- bucket/paket.json
Paket is a popular alternative package manager for .NET
https://fsprojects.github.io/Paket/
> paket: Add version 5.236.6

- bucket/fciv.json
> fciv@2.05: Fix hash

- bucket/sbt.json
> sbt@1.3.4: Fix hash

- bucket/starship.json
Howdy Scoop team! 👋 
Following the advice given in #566, we have gone ahead and added shasums to our releases in https://github.com/starship/starship/pull/649. This PR uses those hashes for verification.
Cheers
> starship: Add hash extraction

- bucket/cuda.json
> cuda@10.2.89_441.22: Fix hash

- bucket/figurine.json
**[figurine](https://github.com/arsham/figurine)**
Description: Print any text using ASCII art in FIGlet.
License: Apache-2.0
Preview:
> figurine: Add version 1.0.1

- bucket/cmder-full.json
- bucket/cmder.json
> cmder: Fix URL

- bucket/rainbow.json
**[rainbow](https://github.com/arsham/rainbow)**
Description: Print text in rainbow pattern.
License: Apache-2.0
Preview:
> rainbow: Add version 1.0.0

- bucket/fake.json
FAKE package manager
https://fake.build/
Similar to Cake:
https://cakebuild.net/
> fake: Add version 5.18.3

- bucket/concfg.json
- bucket/gitignore.json
- bucket/ln.json
- bucket/pshazz.json
- bucket/psutils.json
- bucket/runat.json
- bucket/say.json
- bucket/shasum.json
- bucket/shim.json
- bucket/sudo.json
- bucket/time.json
- bucket/touch.json
- bucket/vimtutor.json
Fix #625
`shim` is moved from `extras`, ref https://github.com/lukesampson/scoop-extras/pull/3298
> psutils: Fix checkver

- bucket/topgrade.json
homepage: https://github.com/r-darwish/topgrade
It could update scoop installed apps :smile:
> topgrade: Add version 3.5.0

- bucket/yori.json
http://www.malsmith.net/yori/
https://github.com/malxau/yori
> yori: Add version 1.11

- bucket/cormanlisp.json
> cormanlisp: Fix checkver url

- bucket/awsQueue.json
Adds awsQueue (https://github.com/NearlyUnique/awsqueue) version 0.0.7
> awsQueue: Add version 0.0.8

- bucket/fx.json
Close https://github.com/lukesampson/scoop-extras/issues/3362
> fx: Add version 16.0.0

- bucket/vim.json
fix https://github.com/ScoopInstaller/Main/issues/650
> vim: remove vim82 directory

- bucket/kustomize.json
> kustomize: Fix au.url

- bucket/jabba.json
> jabba: Add version 0.11.2

- bucket/yori.json
Initialization scripts for yori are stored here.
> yori: Persist YoriInit.d

- bucket/pdfbox.json
Will add `autoupdate` again after https://github.com/lukesampson/scoop/pull/3518 merged.
> pdfbox: Update to 2.0.18

- bucket/cygwin.json
> Cygwin@2.898: Fix hash

- bucket/bat.json
- Closes #460 
Do not know why it was added in ab27b0e832c95cf283ee35baff031c669dfecb56 (lukesampson/scoop#3031)
> bat: Remove suggest to ccat

- bucket/azure-cli.json
> azure-cli@2.0.78: Fix hash

- bucket/gcc.json
I add rev version into version because sometimes there will be rev1.
> gcc: Add bin and autoupdate

- bucket/hexed.json
[hexed](https://github.com/samizzo/hexed): A Windows console-based hex editor
> hexed: Add version 1.0.32

- bucket/win-acme.json
> win-acme: Fix checkver and au.url

- bucket/unrar.json
> unrar@5.80: Fix hash

- bucket/cygwin.json
- Fix #701
- Fix #703 
- Fix #704
> cygwin: Fix hashes

- bucket/ghq.json
> ghq: Update to version 0.99.2

- bucket/dotnet-sdk.json
- bucket/ffsend.json
Since @CarlosDomingues is unresponsive and I cannot make changes in #641, a new PR about `dotnet-sdk` is submitted here.
> dotnet-sdk: Update to version 3.1.100

- bucket/haxe-dev.json
- bucket/haxe.json
- bucket/neko.json
fix https://github.com/lukesampson/scoop/issues/3808
> haxe, neko: fix env path

- bucket/nu.json
> nu@0.8.0: Fix extract_dir

- bucket/dotnet-sdk.json
Add env_add_path and suggest values to include required dependencies.
This a duplicate of #253 since it was closed and old.
> dotnet-sdk: Add path and suggest

- bucket/puppet-bolt.json
If it doesn't fit in here, just tell me and I will PR it into another bucket.
> puppet-bolt: Add version 1.44.0

- bucket/n-m3u8dl-cli.json
A m3u8 downloader.
https://github.com/nilaoda/N_m3u8DL-CLI
https://github.com/nilaoda/N_m3u8DL-CLI/blob/master/README_ENG.md
> n-m3u8dl-cli: Add version 2.4.6

- bucket/k9s.json
> k9s: Update to version 0.13.6

- bucket/kops.json
#150
Someone please test installation. I am under limited and slow connection
> kops: Update to version 1.15.1

- bucket/mysql.json
> mysql: remove bad exes (fixes #729)

- bucket/broot.json
#150
Do not know if this is intentional / was in previous releases
> broot: Update to version 0.12.2

- bucket/eac3to.json
Audio conversion tool
https://forum.doom9.org/showthread.php?t=125966
https://www.videohelp.com/software/eac3to
> eac3to: Add version 3.34

- bucket/tta.json
TTA Lossless Audio Codec - command line frontend
https://web.archive.org/web/20151027213538/http://en.true-audio.com
https://sourceforge.net/projects/tta/
> tta: Add version 2.3

- bucket/wavpack.json
Hybrid lossless audio compression
http://www.wavpack.com
https://github.com/dbry/WavPack
> wavpack: Add version 5.2.0

- bucket/liquibase.json
Database schema change manager (Community Edition)
https://www.liquibase.org/
> liquibase: Add version 3.8.5

- bucket/promtail.json
Originally submitted to scoop-extras https://github.com/lukesampson/scoop-extras/pull/3527
> promtail: Add version 1.3.0

- bucket/govc.json
- Closes #739 
Tested for installation, uninstallation, and updates
> govc: Add version 0.22.1

- bucket/procs.json
[procs](https://github.com/dalance/procs): A modern replacement for ps written in Rust
> procs: Add version 0.9.5

- bucket/say.json
To quiet spurious log entry. See #150
> say: Update to 0.2020.01.26 (version only)

- bucket/cppcheck.json
32-bit support has been dropped
> cppcheck: Update to version 1.90

- bucket/bochs.json
Both 64bit and 32bit installed locally fine
> bochs: Update to 2.6.11 (fix au.url)

- bucket/stern.json
- Closes lukesampson/scoop-extras#3275
- Closes lukesampson/scoop#3510
Co-authored-by: Patrik Akselsson <pakselsson@paypal.com>
> stern: Add version 1.11.0

- bucket/apimtemplate.json
See #150. Hash file is missing in this build
> apimtemplate: Update to version 0.3-gamma

- bucket/yubico-piv-tool.json
> yubico-piv-tool: Fix hashes

- bucket/cygwin.json
> cygwin@2.901: Fix hash

- bucket/trojan.json
Add trojan: https://github.com/trojan-gfw/trojan
> trojan: Add version 1.14.1

- bucket/okteto.json
Adds okteto
https://github.com/okteto/okteto
> okteto: Add version 1.7.2

- bucket/camunda-operate.json
Moved from https://github.com/lukesampson/scoop-extras/pull/3564
> camunda-operate: Add version 1.2.0

- bucket/stoplight-prism.json
Moved from lukesampson/scoop-extras#3569
> stoplight-prism: Add version 3.2.6

- bucket/zeebe.json
Moved from lukesampson/scoop-extras#3565 to Main
> zeebe: Add version 0.22.1

- bucket/z.lua.json
https://github.com/skywind3000/z.lua/releases
#150
> z.lua: Update to version 1.8.4

- bucket/dust.json
du + rust = dust. Like du but more intuitive.
> dust: Add version 0.5.1

- bucket/scrcpy.json
scrcpy.exe is the main command. scrcpy-noconsole.exe is the same but no console.
> scrcpy: Add scrcpy-noconsole to bin

- bucket/uncrustify.json
> uncrustify: Fix autoupdate

- bucket/lynx.json
> lynx: fixed hash

- bucket/rke.json
close https://github.com/lukesampson/scoop/issues/3857
* **RKE** (Rancher Kubernetes Engine) ([homepage](https://rancher.com/products/rke/)) is a CNCF-certified Kubernetes distribution that runs entirely within Docker containers. It solves the common frustration of installation complexity with Kubernetes by removing most host dependencies and presenting a stable path for deployment, upgrades, and rollbacks.
> rke: Add version 1.0.4

- bucket/ripgrep.json
- Closes #892 
- Closes lukesampson/scoop-extras#3704
> ripgrep@12.0.0: Fix extraction

- bucket/coredns.json
Was previously hardcoded to 1.6.5
> coredns: Proper update to version 1.6.7

- bucket/julia.json
- Closes #912
- Closes #911 
- Closes #915
> julia@1.4.1: Fix decompress

- bucket/cygwin.json
Closes #917 
Closes #902 
Closes #889
> cygwin@2.904: Fix 'checkver' and update hashes

- bucket/yubico-piv-tool.json
> yubico-piv-tool@2.0.0: Fix installation

- bucket/bottom.json
[bottom](https://github.com/ClementTsang/bottom) is a single binary TUI process/system monitor with a customizable interface and a multitude of features.
Inspired by both gtop and gotop.
> bottom: Add version 0.2.2

- bucket/gomplate.json
It'd be useful to add `gomplate` to _Scoop_.
> gomplate: Add version 3.6.0

- bucket/gogs.json
- Fix download links
- Fix manifest in general
> gogs: Fix checkver

- bucket/rakudo-star.json
redoing https://github.com/ScoopInstaller/Main/pull/867 again... this time in an extra branch
@Ash258 hope it's ok / better this way...
> rakudo-star: Add version 2020.01-01

- bucket/gauche.json
Add Gauche manifest.
See also: https://github.com/shirok/Gauche/issues/539
> gauche: Add version 0.9.9

- bucket/deno.json
> deno: Update to version 0.38.0

- bucket/fio.json
redoing / moving https://github.com/lukesampson/scoop-extras/pull/3692
@Ash258 hope this was what you asked for...
> fio: Add version 3.18

- bucket/git-filter-repo.json
This is needed for usage contrib-tools in python!
> git-filter-repo: Use contrib-tools

- bucket/perl.json
> perl: Fix checkver

- bucket/chisel.json
> chisel: Update to version 1.4.0

- bucket/win-acme.json
> win-acme: Update to version 2.1.6.773

- bucket/algernon.json
#150
> The Windows and OpenBSD releases does not compile anymore. I want to look into that at some point.
- Tweak manifest
> algernon: Disable checkver

- bucket/jcli.json
> jcli: Update to version 0.0.27

- bucket/gitkube.json
> gitkube: Disable checkver

- bucket/broot.json
> broot: Update to version 0.13.6

- bucket/casperjs.json
- bucket/dark.json
- bucket/forge.json
- bucket/innoextract.json
- bucket/kompose.json
- bucket/lame.json
- bucket/phantomjs.json
- bucket/trid.json
- bucket/wixtoolset.json
> fix(manifest): Change 'http' to 'https'

- bucket/texlab.json
An implementation of the Language Server Protocol for LaTeX
Please consider adding it.
> texlab: Add version 1.10.0

- bucket/rancher-cli.json
The Rancher Command Line Interface (CLI) is a unified tool for interacting with your Rancher Server.
For usage information see: rancher.com/docs/rancher/v2.x/en/cli
The Rancher CLI is widely used with over 1 million total downloads.
> rancher-cli: Add version 2.4.0

- bucket/mysql.json
- Closes #1038
- Closes lukesampson/scoop#3949 
File comp_err.exe does not exist.
> mysql@8.0.20: Fix shim

- bucket/qrcp.json
Includes changes requested by @Ash258 (thanks) under lukesampson/scoop-extras#3940.
> qrcp: Add version 0.6.1

- bucket/rdiff-backup.json
Please add [rdiff-backup](https://rdiff-backup.net), an incremental backup tool
> rdiff-backup: Add version 2.0.0

- bucket/aks-engine.json
> aks-engine: Add version 0.50.0

- bucket/gopass.json
> gopass: Update to version 1.9.0

- bucket/uutils-coreutils.json
#150
Have no idea what happened to the fork releases. Changed source to official repository
> uutils-coreutils: Update to version 0.0.1

- bucket/legit.json
[Legit](https://frostming.github.io/legit/) is a complementary command-line interface for Git optimized for workflow simplicity.
> legit: Add version 1.2.0

- bucket/chroma.json
> chroma: Update to version 0.7.3

- bucket/win-acme.json
> win-acme: Update to version 2.1.7.807

- bucket/highlight.json
> highlight: Fix checkver

- bucket/gitlab-runner.json
> gitlab-runner: Fix checkver

- bucket/pypy2.json
- bucket/pypy3.json
#150
Fix permanent redirect on all URLs
> pypy(2,3): Fix checkver

- bucket/sayit.json
sayit is a text-to-speech command line tool.
<https://github.com/pviotti/sayit/issues/40>
> sayit: Add version 1.1

- bucket/colortool.json
> colortool: Fix checkver

- bucket/fossil.json
> fossil: Add 32bit

- bucket/postgresql.json
> postgresql: Fix checkver

- bucket/libwebp.json
> libwebp: Update to version 1.1.0

- bucket/ffmpeg-nightly.json
- bucket/ffmpeg-shared.json
- bucket/ffmpeg.json
Fix homepage and checkver for all other
#150
> ffmpeg-nightly: Update to version 20200522-38490cb

- bucket/kubens.json
https://github.com/ahmetb/kubectx
kubens is a utility to switch between Kubernetes namespaces.
Ref: https://github.com/ScoopInstaller/Main/pull/995#issuecomment-635066207
> kubens: Add version 0.9.0

- bucket/uutils-coreutils.json
> uutils-coreutils: Update to version 0.0.1.1

- bucket/v2ray.json
Ref: https://github.com/v2ray/v2ray-core/releases/tag/v4.23.4
> v2ray: move to v2fly

- bucket/busybox.json
Add `httpd`, `reset`, `time` and `ts`.
> busybox: Add more bins

- bucket/b3sum.json
license ref: https://github.com/BLAKE3-team/BLAKE3/blob/7f154ceea33c4c8dcc3719836c89b9a79d39319c/b3sum/Cargo.toml#L7
> b3sum: Add version 0.3.4

- bucket/vulkan.json
Introduce the `vulkan sdk` to this `main` bucket.
As there are many types of licenses involved, I cannot determine a proper `identifier` of license, it would be great if someone could help me with that...
> vulkan: Add version 1.2.135.0

- bucket/eventstore.json
> eventstore: Update to version 20.6.0

- bucket/deepstream.json
> deepstream: Fix checkver

- bucket/grails.json
> grails: Fix checkver

- bucket/idris.json
> idris: Update to version 1.3.3

- bucket/rga.json
> rga: Update to version 0.9.6

- bucket/roswell.json
> roswell: Fix checkver

- bucket/sccache.json
> sccache: Fix checkver and manifest

- bucket/shadowsocks-rust.json
> shadowsocks-rust: Update to version 1.8.12

- bucket/ytdl.json
Yet another YouTube downloader
> ytdl: Add version 0.6.3

- bucket/go.json
> #1242: Correcting typo.

- bucket/balena-cli.json
> balena-cli: Add version 12.3.3

- bucket/tokei.json
> tokei: Add version 12.0.4

- bucket/scaleway-cli.json
> scaleway-cli: Update to version 2.0.0

- bucket/sslscan.json
> sslscan: Update to version 2.0.0

- bucket/austin.json
Austin is a Python frame stack sampler for CPython
> austin: Add version 1.0.1

- bucket/prince.json
CLI with non-commercial license, but a logo in output files.
> prince: Add version 13.5

- bucket/gogs.json
#150
https://gogs.io/docs/installation/install_from_binary
> gogs: Update to version 0.12.0

- bucket/imagemagick.json
> imagemagick@7.0.10-29: Fix shimed bin

- bucket/ccache.json
Adds [ccache](https://ccache.dev) to scoop.
> Add ccache manifest

- bucket/kind.json
> kind: Add version 0.8.1

- bucket/ibmcloud-cli.json
ref: https://github.com/lukesampson/scoop-extras/issues/4318
> ibmcloud-cli: Add version 1.1.0

- bucket/gopass.json
> gopass: Update to version 1.10.0

- bucket/pdfbox.json
> pdfbox: Update to version 2.0.21

- bucket/winnfsd.json
Standalone, simple NFS Server for Windows: https://github.com/winnfsd/winnfsd
> winnfsd: Add version 2.4.0

- bucket/beeflang.json
Tested autoupdate and installation. The IDE and the language come packaged together. 
https://www.beeflang.org/
> beeflang: Add version 0.42.6

- bucket/pack.json
Add [Buildpack CLI](https://github.com/buildpacks/pack)
> pack: Add version 0.13.1

- bucket/gnuplot.json
> gnuplot: Update to version 5.28

- bucket/mro.json
> mro: Fix `url` and `rtools` dep

- bucket/csview.json
Added [csview](https://github.com/wfxr/csview).
> csview: Add version 0.3.5

- bucket/gh.json
v1.1.0 was made available today
> gh: Update to version 1.1.0

- bucket/grep.json
> grep: add egrep and fgrep to shim

- bucket/ffmpeg-shared.json
- bucket/ffmpeg.json
Add commit counter to version string like discussed here: #1454
> ffmpeg: add commit number to version string

- bucket/bit.json
Add [bit](https://github.com/chriswalz/bit) -- a git CLI with some goodies (incl. some commands from git-extras)
> bit: Add version 0.5.14

- bucket/diffutils.json
It's my first time contributing here so let me know if something is wrong. Needs testing to see if it works.
> diffutils: Update version to 3.7

- bucket/pandoc.json
This will update the manifest to new release of Pandoc
There is no more 32bits version BTW.
> udpate to pandoc 2.11.0.1

- bucket/lua.json
- bucket/srlua.json
Updated srlua to version 5.4.1 as well
> lua: Update to version 5.4.1

- bucket/boundary.json
Hello everyone !
It's my first PR, please feel free to correct me.
This is a new tool from HashiCorp: https://www.waypointproject.io/
I based myself on some existing manifest for HashiCorp tools: https://github.com/ScoopInstaller/Main/blob/master/bucket/vault.json
Thank you in advance !
> boundary: add version 0.1.0

- bucket/waypoint.json
Hello everyone !
It's my first PR, please feel free to correct me.
This is a new tool from HashiCorp: https://www.waypointproject.io/
I based myself on some existing manifest for HashiCorp tools: https://github.com/ScoopInstaller/Main/blob/master/bucket/vault.json
Thank you in advance !
> waypoint: add version 0.1.3

- bucket/avrdude.json
AVRDUDE is software for programming Atmel AVR Microcontrollers
https://osdn.net/projects/avrdude
> avrdude: Add version 6.3-20171130

- bucket/cuda.json
cuda: Update to version 11.0.3_451.82
> cuda: Update to version 11.0.3_451.82

- bucket/abc.json
https://github.com/appbaseio/abc
> ABC is a command-line tool to interact with appbase.io
> abc: Add version 1.0.0-beta.1

- bucket/puppet-bolt.json
Should fix #1364 by unsetting GEM_HOME before running puppet-bolt
> puppet-bolt: fix GEM_HOME issue

- bucket/xpdf-tools.json
Replace the current invalid URL with a new one.
> xpdf-tools@4.02: Fix URL

- bucket/uncrustify.json
#150
Manual update, as I am not sure if the last dash is permanent or bug.
> uncrustify: Update to version 0.72.0

- bucket/tor.json
> tor@0.4.4.5: Fix url and hash

- bucket/erlang.json
Test in my computer.
[System.Environment]::OSVersion.Version = Microsoft Windows NT 10.0.19042.0
$PSVersionTable.PSVersion = 5.1.19041.610
> erlang: Fix post_install

- bucket/ddev.json
> ddev: Update to version 1.16.0

- bucket/windows-application-driver.json
> windows-application-driver: Update to version 1.2.1

- bucket/PowerSession.json
> PowerSession: Update to version 1.3.0

- bucket/cloudflared.json
> cloudflared: Add version 2020.11.8

- bucket/curl.json
> curl: Update to version 7.73.0_3

- bucket/curl.json
Close #1610
Close https://github.com/lukesampson/scoop/issues/4184
> curl: Fix extract_dir

- bucket/srecord.json
The SRecord package is a collection of powerful tools for manipulating EPROM load files.
> Add srecord

- bucket/php-nts.json
- bucket/php.json
Filenames have changed to reflect using Visual Studio 2019 for compiling.
> php(-nts): Update to version 8.0.0

- bucket/mongodb.json
Fix binary name pattern for `autoupdate`.
> mongodb: Update to version 4.4.2

- bucket/apimtemplate.json
Fix binary name for `autoupdate`.
> apimtemplate: Update to version 0.5

- bucket/xmake.json
> xmake: Fix bin

- bucket/sslscan.json
> sslscan: Update to version 2.0.6

- bucket/lame.json
> lame: Update to version 3.100.1

- bucket/openssl-mingw.json
> openssl-mingw: Fix extract_dir

- bucket/mongodb-database-tools.json
> mongodb-database-tools: Add version 100.2.1

- bucket/julia.json
Add shortcut to launch Julia repl
> julia: Add shortcut

- bucket/stlink.json
> stlink: Add version 1.6.1

- bucket/mosquitto.json
- Closes #1527 
- Closes #1603
> mosquitto: Add version 1.6.12a

- bucket/gping.json
[gping](https://github.com/orf/gping), is a ping tool with graph.
See https://github.com/orf/gping/issues/106
> gping: Add version 0.1.7

- bucket/duf.json
> duf: add version 0.5.0

- bucket/mdcat.json
> mdcat: add version 0.22.1

- bucket/clink.json
- bucket/imagemagick.json
fix https://github.com/chrisant996/clink/issues/24
> clink: Change to chrisant996/clink version

- bucket/pyenv.json
> pyenv: Add version 2.64.3

- bucket/ethr.json
> ethr: add version 1.0.0

- bucket/jid.json
- bucket/jq.json
Add [JSON Incremental Digger](https://github.com/simeji/jid).
> jid: Add version 0.7.6

- bucket/innounp.json
- Closes #1709
- Closes #1637
- Closes lukesampson/scoop-extras#5213
- Closes lukesampson/scoop-extras#5223
- Closes lukesampson/scoop-extras#5225
- Closes lukesampson/scoop-extras#5306
- Closes lukesampson/scoop-extras#5312
- Closes lukesampson/scoop-extras#5345
- Closes lukesampson/scoop-extras#5349
Blocked by ScoopInstaller/Binary#11
> innounp: Update to version 0.50

- bucket/oh-my-posh3.json
Co-authored-by: Jan De Dobbeleer <jan.de.dobbeleer@gmail.com>
Co-authored-by: Ash258 <cabera.jakub@gmail.com>
> oh-my-posh3: Add version 3.64.2

- bucket/scrcpy.json
> scrcpy: Fix link for binary file

- bucket/wasmer.json
This PR adds [Wasmer](https://wasmer.io) to the Scoop project.
> wasmer: Add wasmer 1.0.1

- bucket/deta.json
> deta: add version 1.1.2-beta

- bucket/starship.json
starship v0.49.0 added a 32bit build for windows.
> starship: add 32bit version

- bucket/lychee.json
https://github.com/lycheeverse/lychee
> lychee: Add version 0.5.0

- bucket/kapp.json
> kapp: Add version 0.35.0

- bucket/curl.json
Closes #1811, closes #1812, closes #1813, closes #1814
> Correct extracted directory name for cURL 7.75.0_2

- bucket/glitter.json
Adds support for glitter!
Note I wasn't sure on how to get the hash so that is the commit hash. Please let me know of how to get it :)
> glitter: Add version 1.0.0

- bucket/lynx.json
Fixes #1862.
Referenced this issue for solution: #1862
> lynx: Update Win32OpenSSL_Light link/hash. (#1862)

- bucket/csview.json
Fixes https://github.com/lukesampson/scoop/issues/4297
> csview: Add 'extract_dir' field

- bucket/cutter.json
> cutter: Add 'extract_dir' field

- bucket/yubico-piv-tool.json
Closes https://github.com/ScoopInstaller/Main/issues/1961
> yubico-piv-tool: Fixes and update to version 2.2.0

- bucket/vmaf.json
Closes https://github.com/ScoopInstaller/Main/issues/2001
> vmaf: Add version 2.1.1

- bucket/sdcc.json
Closes https://github.com/ScoopInstaller/Main/issues/1994
> sdcc: Add version 4.1.0

- bucket/helm-docs.json
https://github.com/norwoodj/helm-docs
> helm-docs: Add version 1.5.0

- bucket/xray.json
> xray: Add version 1.4.2

- bucket/flux2.json
> flux2: Add version 0.11.0

- bucket/ticker.json
Add Ticker (Terminal Stock Watcher).
More info: https://github.com/achannarasappa/ticker
> ticker: Add version 4.0.6

- bucket/jfrog.json
address issue in #150
Close #1969
> jfrog: Update to version 1.44.0

- bucket/dapr-cli.json
Add Dapr CLI.
More info: https://github.com/dapr/cli
> dapr-cli: Add version 1.1.0

- bucket/bicep.json
Add Bicep CLI (from Microsoft).
More info: https://github.com/Azure/bicep
> bicep: Add version 0.3.126

- bucket/zstd.json
> zstd@1.5.0: Fix installation

- bucket/git-xargs.json
https://github.com/gruntwork-io/git-xargs
> git-xargs: Add version 0.0.11

- bucket/rtools.json
Hello, I am the maintainer of rtools. Please consider using the latest patch release.
> Update to latest rtools build

- bucket/PowerSession.json
> PowerSession: Update to latest version

- bucket/lynx.json
Fixes #2534 
Fixes #2267 
Fixes #2239 
Fixes #2216 
Closes #2155
> lynx@2.9.0dev.9: Hash fix

- bucket/git-with-openssh.json
> git-with-openssh: add ssh-copy-id

- bucket/hexyl.json
From the author of bat, fd and hyperfine (all in Main bucket)
> hexyl: Add version 0.9.0

- bucket/geth.json
> geth: Add version 1.10.8

- bucket/prs.json
This adds the `prs` package: https://github.com/timvisee/prs
> prs: Add version 0.3.2

- bucket/ncspot.json
Cross platform CLI Spotify player
Like https://github.com/ScoopInstaller/Main/blob/master/bucket/mpxplay.json but for Spotify :)
> ncspot: Add version 0.8.2

- bucket/pastel.json
Another helpful color tool from the {fd,hexyl,bat,hyperfine} author :)
> pastel: Add version 0.8.1

- bucket/cuda.json
Tried to go back in time and the script seems to be broken for more than a year, last working version being 10.1.168_425.25.
> cuda: Fix installation script

- bucket/neovim-nightly.json
Daily builds of Neovim
Inspired by https://github.com/ScoopInstaller/Main/blob/master/bucket/vim-nightly.json
> neovim-nightly: Add version 0.6.0-dev-276-g685cf3981

- bucket/kim.json
https://github.com/rancher/kim - The Kubernetes Image Manager
> kim: Add version 0.1.0-beta.6

- bucket/gobang.json
Add gobang
[gobang](https://github.com/TaKO8Ki/gobang): A cross-platform TUI database management tool written in Rust
> gobang: Add version 0.1.0-alpha.5

- bucket/yt-dlp.json
> yt-dlp: Add version 2021.09.25

- bucket/velero.json
https://github.com/vmware-tanzu/velero/releases/tag/v1.7.0
> velero: Update to version 1.7.0

- bucket/termscp.json
From https://github.com/veeso/termscp
> termscp: Add version 0.6.1

- bucket/imagemagick.json
> imagemagick@7.1.0-13: fix hash

- bucket/dmd.json
Fix for #2565 
dmd64 for architecture 64
> Fix dmd64 bin for 64bits system #2565

- bucket/invoke-build.json
No longer contains releases.
Only tags
#2843
> invoke-build: update checkver

- appveyor.yml
> Update appveyor powershell names & scoop git url

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Package_request.md
- .github/issue_template.md
- .github/pull_request_template.md
- Added a default template message for blank issues
- Improved placeholders and made them more descriptive
- Added a PR checklist
Closes #1017
> feat(chore): Add a default issue template

- bucket/megacmd.json
No releases anymore.
Only tags
#2843
> megacmd: fix checkver

- bucket/mpxplay.json
> mpxplay: Add MPXPTABS.INI to persist

- bucket/mysql.json
> mysql: Suggest vcredist2017 (closes #1074)

- bucket/pwsh.json
> pwsh: Update to 7.2.0

- bucket/xxcopy.json
xxfw3333.zip is identified as the freeware version on http://www.xxcopy.com/xcpydnld.htm
> xxcopy: Fix license

- bucket/rclone.json
Relates to #2908
/cc @CrendKing
> rclone: Update to version 1.57.0

- bucket/railway.json
> railway: Update to version 0.2.49

- bucket/yt-dlp.json
Updated yt-dlp to version 2021.11.10.1
> yt-dlp: Update to version 2021.11.10.1

- bucket/lua.json
Original one is moved to https://github.com/ScoopInstaller/Versions/pull/310
> lua: Change to Lua Binaries's build

- bucket/luarocks.json
Close https://github.com/ScoopInstaller/Main/issues/1708
> luarocks: Add version 3.8.0

- bucket/starship.json
> starship: Update to v1.0.0

- bucket/clangd.json
Language server for C/C++. Inspired by https://github.com/ScoopInstaller/Main/blob/master/bucket/rust-analyzer.json
> clangd: Add version 13.0.0

- bucket/kustomize.json
Autoupdate re-enabled
Relates to #2848 
Thanks @natasha41575
> kustomize: update to 4.4.1

- bucket/oracle-instant-client-odbc.json
- bucket/oracle-instant-client-sdk.json
Additional elements (SDK and ODBC driver) for Oracle Instant Client, should be merged after https://github.com/ScoopInstaller/Main/pull/624
> oracle-instant-client: Add SDK and ODBC

- bucket/modern7z.json
Fix version of https://github.com/ScoopInstaller/Extras/pull/5612
Closes https://github.com/ScoopInstaller/Extras/pull/5612
> modern7z: Add version 1.8.7

- bucket/wormhole-william.json
> End-to-end encrypted file transfer. A magic wormhole CLI and API in Go
> https://github.com/psanford/wormhole-william
> wormhole-william: Add version 1.0.5

- bucket/okteto.json
Update of scoop version.
The `checkver` configuration does not seems to work.
> Update okteto version

- bucket/tectonic.json
Added Tectonic, a self contained latex compiler
> Add tectonic to bucket

- bucket/hugo-extended.json
Update hugo-extended to latest release.
> hugo-extended: Update to version 0.89.4

- bucket/ryzenadj.json
Closes https://github.com/ScoopInstaller/Main/issues/2916
> ryzenadj: Add version 0.8.2

- bucket/ffmpeg-shared.json
- bucket/ffmpeg.json
Signed-off-by: kuni3933 <57650186+kuni3933@users.noreply.github.com>
Fixed URl and hash.
Closes #2982
> ffmpeg and ffmpeg-shared: Fixed URl and hash 

- bucket/tinygo.json
Changed the download link and calculated the new hash.
Closes #XXXX
> tinygo: Update to v0.21

- bucket/lessmsi.json
Changed the download link and calculated the new hash.
> lessmsi: Update to v1.10.0

- bucket/hugo.json
> hugo: Update to version 0.89.4

- bucket/sentinel.json
- Closes #2557 
https://docs.hashicorp.com/sentinel
> sentinel: Add version 0.18.4

- bucket/k9s.json
Look like auto updater not works now?
> k9s: update to version 0.25.7

- bucket/mingit-busybox.json
- bucket/mingit.json
Update `mingit` and `mingit-busybox` to version 2.34.1.windows.1
> mingit & mingit-busybox: Update to version 2.34.1.windows.1

- bucket/postgresql.json
Update postgresql to version 14.1.
I've also changed the checkver regex since the current one no longer matches the website.
> Update postgresql to version 14.1

- bucket/centrifugo.json
close https://github.com/ScoopInstaller/Main/issues/3001
> centrifugo: Update homepage url

- bucket/neovim.json
neovim: update to version 0.6.0
> neovim: update to version 0.6.0

- bucket/kompose.json
Updating kompose to version 1.26 & setting the bin setting to create a shim for command line usage.
> Update to 1.26 and enable exe setting

- bucket/win-acme.json
> win-acme: Fix regex closes #3036

- bucket/yt-dlp.json
yt-dlp: update to version 2021.12.01
> yt-dlp: update to version 2021.12.01

- bucket/gdb.json
> gdb: Update to version 11.1

- .github/workflows/issue_comment.yml
- .github/workflows/issues.yml
- .github/workflows/pull_request.yml
See https://github.com/ScoopInstaller/Extras/pull/7465
> chore(ci): Use Windows Actions to avoid SSL errors

- bucket/nancy.json
Closes #3041
https://github.com/ScoopInstaller/Main/issues/3041
> Added Sonatype Nancy

- bucket/gleam.json
> gleam: Add version 0.17.0

- bucket/ffmpeg.json
> ffmpeg: Fix download URL and update hash

- bucket/docker.json
Closes #3058
The deprecation of `lcow` and `docker-nightly` is being handled in #2972.
/cc @JanPokorny
> docker: Update to version 20.10.11

- bucket/poetry.json
Thanks to the initial work done by @uyha on #1726, I'm proposing the evolution of the pull request.
> poetry: Add version 1.1.12

- bucket/poetry.json
I missed the soft error in the last #3067 RP, the uninstallation process works without problems but with an error in the logs.
> poetry: Fix uninstall soft error

- bucket/v2ray.json
closes https://github.com/ScoopInstaller/Extras/issues/7521
> v2ray: Fix issue in 'path with space'

- bucket/grep.json
- bucket/make.json
- bucket/pcre2grep.json
- bucket/pcregrep.json
- bucket/sed.json
> chore: Update some very old apps

- bucket/sort-uniq-wc.json
> sort-uniq-wc: Add version 9.0

- bucket/htmlq.json
close https://github.com/ScoopInstaller/Main/issues/3073
> htmlq: Add version 0.3.0

- bucket/grep.json
- bucket/sed.json
https://github.com/ScoopInstaller/Main/pull/3080#issuecomment-992718380
> sed, grep: Use choco source

- bucket/gcc.json
- bucket/mingw.json
> gcc: Add version 11.2.0

- bucket/ffmpeg-shared.json
> ffmpeg-shared: Fixed download url

- bucket/smartmontools.json
closes https://github.com/ScoopInstaller/Extras/issues/7532
> smartmontools: use 7z extract and update sha256 hash

- bucket/python.json
> python: Do pip initialization in post_install

- bucket/osquery.json
> osquery: Add version 5.0.1

- bucket/gnupg.json
- bucket/gpg.json
> gnupg: Post 2.3.2 fix for no agent running error

- bucket/nali.json
nali: Update to version 0.3.5, fix version detection in url
> nali: Update to version 0.3.5, fix version detection in url.

- bucket/sftpgo.json
> sftpgo: Add version 2.2.0

- bucket/yarn.json
- url/hash
- extract_dir
- env_add_path
- checkver
- autoupdate
close https://github.com/ScoopInstaller/Main/issues/3125
> yarn: Update manifest

- bucket/snapraid.json
Add SnapRAID package.
Closes #3141
> snapraid: Add version 12.0

- bucket/krew.json
> krew: Add version 0.4.2

- bucket/gibo.json
change  https://github.com/github/gitignore 's
branch name master -> main
Closes #3157
- [* ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
> update gibo 2.2.4 -> 2.2.5

- bucket/cheat.json
`cheat` allows you to create and view interactive cheatsheets on the command-line. It was designed to help remind *nix system administrators of options for commands that they use frequently, but not frequently enough to remember.
Homepage: https://github.com/cheat/cheat
> cheat: Add version 4.2.3

- bucket/argo.json
- Closes #3164
- Unsure whether this is the right name for the package, `argo-workflows` could be better but the bin is named `argo`...
> argo: add version 3.2.6

- bucket/docker-pushrm.json
docker-pushrm:
Docker Push Readme - a Docker CLI plugin to update container repo docs.
homepage: https://github.com/christian-korneck/docker-pushrm
> docker-pushrm: Add version 1.8.0

- bucket/curlie.json
The power of curl, the ease of use of httpie.
> curlie: Add version 1.6.7

- bucket/pueue.json
Pueue is a command-line task management tool for sequential and parallel execution of long-running tasks.
Homepage: https://github.com/Nukesor/pueue
> pueue: Add version 1.0.6

- bucket/q.json
q - Run SQL directly on delimited files and multi-file sqlite databases
Homepage: https://harelba.github.io/q/
GitHub: https://github.com/harelba/q (8.9k Star)
> q: Add version 3.1.6

- bucket/terraform-docs.json
Next to tflint, I've added terraform-docs
> Add terraform-docs.json

- bucket/regula.json
This PR adds [Regula](https://github.com/fugue/regula) to _Scoop_.
> regula: Add version 2.3.0

- bucket/lz4.json
> lz4: Add version 1.9.3

- bucket/winget.json
Closes ScoopInstaller/Extras#4107
Closes ScoopInstaller/Scoop#3992
Relates to #1104
> winget: Add version 1.2.3411

- bucket/pnpm.json
close https://github.com/ScoopInstaller/Main/issues/3177
> pnpm: Add version 6.26.1

- bucket/podman.json
> podman: Add version 3.4.4

- bucket/pester.json
- The package converted to a PS module
close https://github.com/ScoopInstaller/Main/issues/1420
> pester@5.3.1: Fix manifest

- bucket/openapi-generator-cli.json
close https://github.com/ScoopInstaller/Main/issues/1822
> openapi-generator-cli: Add version 5.3.1

- bucket/duckdb.json
DuckDB is an in-process SQL OLAP database management system.
Homepage: https://duckdb.org
Popularity: 4.2K stars on Github
> duckdb: Add version 0.3.1

- bucket/xpdf-tools-lsp.json
close https://github.com/ScoopInstaller/Main/issues/1896
> xpdf-tools-lsp: Add version 2011-Aug-15

- bucket/meson.json
close https://github.com/ScoopInstaller/Main/issues/3205
> meson: Add version 0.61.1

- bucket/lynx.json
Fixed: lynx@2.9.0dev.10: download via aria2 failed #3210
Closes #3210
Relates to #3210
> lynx@2.9.0dev.10: Fixed download via aria2 failed #3210

- bucket/multipass.json
based on https://github.com/HUMORCE/nuke/blob/master/bucket/multipass.json.
personal scripts are removed. (do not have full availability)
Related #1745
> multipass: Add version 1.8.0

- bucket/jenkins-lts.json
- bucket/jenkins.json
close https://github.com/ScoopInstaller/Main/issues/2851
> Add jenkins/jenkins-lts

- bucket/chezmoi.json
Closes #3220 https://github.com/twpayne/scoop-bucket/issues/2
There are files in `completions` folder:
```
./completions:
chezmoi-completion.bash
chezmoi.fish
chezmoi.ps1
chezmoi.zsh
```
Is there something I have to do for those file?
> chezmoi: Add version 2.10.0

- bucket/terraformer.json
> Add Terraformer manifest

- bucket/kopia.json
Relates to [Extras/#7812](https://github.com/ScoopInstaller/Extras/pull/7812)
> Kopia: Add version 0.10.1

- bucket/stylua.json
> stylua: Add version 0.11.3

- bucket/boringproxy.json
> boringproxy: add version 0.8.2

- bucket/ossgadget.json
OSS Gadget is a collection of tools that can help analyze open source projects.
Home page https://github.com/microsoft/OSSGadget
Closes #3248
> ossgadget: Add version 0.1.314

- bucket/gotify-cli.json
- bucket/gotify-server.json
Adding this two new app manifest:
gotify-cli: version 2.2.1
gotify-server: version 2.1.4
Closes #1011
> gotify-cli: Add version 2.2.1 - gotify-server: Add version 2.1.4

- bucket/sget.json
This PR updates sget and fixes the hash logic.
Relates to #3251 & https://github.com/ScoopInstaller/Scoop/issues/4688
> sget: Add version 1.5.0 & fix hash

- bucket/pdfcpu.json
> pdfcpu: Add version 0.3.13

- bucket/mongodb.json
Following up on #3260.
I managed to express the regex in a jsonpath, but I was too late. #3260 was already merged.
Relates to #3259
> MongoDB: Use jsonpath for checkver

- bucket/nomino.json
nomino, a batch rename utility for developers: https://github.com/yaa110/nomino
> nomino: Add version 1.1.0

- bucket/aws-nuke.json
> Added aws-nuke

- bucket/dbmate.json
Just a slight manifest update based on the fix to release artifact name.
https://github.com/amacneil/dbmate/pull/270
> dbmate: Update release artifact name

- bucket/gitea.json
> gitea@1.15.11: Fix hash

- bucket/mongodb-database-tools.json
avoid zip decompression issues
Closes #3279
> mongodb-database-tools@100.5.2: Switch to msi package

- bucket/nerdctl.json
> added nerdctl manifest v0.16.1

- bucket/jo.json
A tool for creating JSON objects from CLI
See https://github.com/jpmens/jo
> jo: Add version 1.6

- bucket/vim.json
Closes #2920 
Relates to #3290
> vim: Do not copy example config files

- bucket/vapoursynth.json
> vapoursynth: Add version 57

- bucket/fq.json
> Add fq 0.0.4

- bucket/imagemagick.json
> imagemagick: Add MAGICK_CONFIGURE_PATH

- bucket/PowerSession.json
> PowerSession: Update repo link

- bucket/x265.json
> Update x265.json manifest

- bucket/pypy3.json
> pypy3: Fix bin

- bucket/vivetool.json
> vivetool: Add version 0.2.1

- bucket/buf.json
This PR adds the [buf CLI](https://buf.build/).
> buf: Add version 1.0.0

- bucket/neo-cowsay.json
> neo-cowsay: Add version 2.0.4

- bucket/qaac.json
> qaac: Update to version 2.73

- bucket/oh-my-posh.json
https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/COPYING
> oh-my-posh: Update license to MIT

- bucket/presentmon.json
> Add presentmon

- bucket/nvs.json
> nvs@1.6.0: Use call operator instead of powershell cli

- bucket/tor.json
- bucket/vim.json
Relates to https://github.com/ScoopInstaller/Scoop/pull/4722
> chore: Fix 'current_dir' error

- bucket/dart.json
/verify
Update dart homepage to https://dart.dev/
> dart: Update homepage

- bucket/spicetify-cli.json
Closes https://github.com/ScoopInstaller/Extras/issues/7962
> spicetify-cli: Add version 2.9.2

- bucket/ntfs2btrfs.json
> ntfs2btrfs: Add version 20210923

- bucket/gogs.json
> gogs: update to version 0.12.5, fix checkver

- bucket/wasm4.json
This PR adds a new package for [wasm-4](https://wasm4.org/), a library to build retro games using WebAssembly for a fantasy console.
> Add new package: wasm4

- bucket/etl2pcapng.json
- Relates to Excavator failure: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:248
- `$version` --> `v$version`
> etl2pcapng: update to version 1.7.0

- bucket/dotter.json
- Relates to Excavator failure: https://github.com/ScoopInstaller/Main/runs/5585775074?check_suite_focus=true#step:3:236
- `v$version` --> `$version`
> dotter: update to version 0.12.9

- bucket/graphviz.json
Relates to Excavator failure due to checkver: https://github.com/ScoopInstaller/Main/runs/5606329917?check_suite_focus=true#step:3:252
> graphviz: update to version 3.0.0

- bucket/cuda.json
Relates to Excavator failure due to checkver: https://github.com/ScoopInstaller/Main/runs/5606329917?check_suite_focus=true#step:3:243
> cuda: update to version 11.6.1_511.65

- bucket/staticcheck.json
> staticcheck: Add version 2021.1.2

- bucket/par2cmdline.json
Closes #3412
I'm not sure about the license ("GPL-2.0-or-later" or "GPL-2.0-only"?). Please help correct if I'm wrong.
> par2cmdline: Add version 0.8.1

- bucket/less.json
> less: Add autoupdate and architecture

- bucket/openssh.json
> Update openssh to 8.9.0.0

- bucket/ie11webdriver.json
Relates to Excavator failure to do change of download location: https://github.com/ScoopInstaller/Main/runs/5650708572?check_suite_focus=true#step:3:270
> ie11webdriver: Update to version 4.0.0

- bucket/k0s.json
Releates to Excavator issue due to checkver hardcoding part of the version: https://github.com/ScoopInstaller/Main/runs/5650708572?check_suite_focus=true#step:3:284
> k0s: Update to version 1.23.3+k0s.1, fix checkver

- bucket/px.json
> px: fix autoupdate

- bucket/kubeseal.json
Relates to Excavator issue due to change of release format: https://github.com/ScoopInstaller/Main/runs/5657032696?check_suite_focus=true#step:3:265
> kubeseal: Update to version 0.17.3, add hash extraction

- bucket/miller.json
> miller: Add extract_dir

- bucket/rakudo-star.json
also changed autoupdate:hash:regex
Closes #XXXX
> rakudo-star: Update to 2022.03-01

- bucket/vmaf.json
Relates to Excavator finding update but no autoupdate: https://github.com/ScoopInstaller/Main/runs/5709628840?check_suite_focus=true#step%3A3%3A335=
> vmaf: Update to version 2.3.0, add autoupdate

- bucket/vultr.json
> Add Vultr CLI tool

- bucket/dagger.json
> dagger: Add version 0.2.4

- bucket/dum.json
> dum: Add version 0.1.19

- bucket/magic-wormhole-rs.json
> magic-wormhole-rs: Add version 0.4.0

- bucket/rust-msvc.json
- bucket/rust.json
> rust: add rls (language server) to bins

- bucket/cheat.json
> cheat: Fix autoupdate

- bucket/gow.json
- Relates to Excavator checkver not working: https://github.com/ScoopInstaller/Main/runs/5968775726?check_suite_focus=true#step:3:265
- Added autoupdate in case of any new releases
- Rearranged bin in manifest to conform to normal structure (https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets)
- Made post_install directory creation silent
> gow: Fix checkver, add autoupdate, rearrange bin

- bucket/containerd.json
Signed off by Hayden Barnes
<hayden.barnes@suse.com>
> containerd: Add message about registering and starting containerd service

- bucket/aqtinstall.json
Added manifest for aqtinstall tool for downloading Qt libraries for different platforms
> aqtinstall: Add version 2.0.6

- bucket/yt-dlp.json
> (chore): Suggest ffmpeg

- bucket/jdtls.json
[+] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
> jdtls: Add version 1.10.0-202204081744

- bucket/nali.json
nali: Update to version 0.3.9, fix version detection in url
> nali: Update to version 0.3.9, fix version detection in url

- bucket/neovim.json
neovim: Update to version 0.7, fix extract_dir
Relates to #3500
> neovim: Update to version 0.7, fix extract_dir

- bucket/neovim.json
> neovim: Remove regex in checkver
